<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>my-app</name>
   <tag></tag>
   <elementGuidId>4aa512fd-b35d-4a0c-943b-4eee5edc4849</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>my-app</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//my-app</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>my-app</value>
      <webElementGuid>fc385542-68a1-4e33-b265-cbcef6da843b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>page</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>0470dab5-70b1-4172-b0e9-6c260a96a1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/my-app[1]</value>
      <webElementGuid>f12f0052-bd68-43de-a5e6-c14be692b1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>my-app</value>
      <webElementGuid>3576112f-165a-44ec-b5d6-0cf3ecd34e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>page</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>5a2dada0-730d-4fc8-9fb8-d44f70c51cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/my-app[1]</value>
      <webElementGuid>3ff26874-2fc8-4f51-bb5f-aa5639dd0c6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//my-app</value>
      <webElementGuid>508640ed-6069-491b-8720-17f9d0eb6660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
