<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rs_lazyOwl item-image</name>
   <tag></tag>
   <elementGuidId>5a8a8bf1-091a-46ed-9154-d35921264ee4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='collapsibleSection']/section[4]/section[2]/div/div/div/div/div[2]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2d81afe1-f6b6-4819-a983-1bff31c59496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyOwl item-image</value>
      <webElementGuid>05dbffd5-8fcf-4b18-8dd0-8a3ad8e3cbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Udaipur</value>
      <webElementGuid>53605537-1934-4a92-a0d1-2f7527f26135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>444c9b7b-ac62-49cf-a461-e46b9b97daaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//www.travelguru.com/ythomepagecms/media/trending_destinations/2017/May/4d13579399c4ee08b1c971ddb327a8bb.jpg</value>
      <webElementGuid>25edf7a9-3798-42fb-8b6b-efef0d536722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapsibleSection&quot;)/section[@class=&quot;fluid-section fluid-full-width&quot;]/section[@class=&quot;fluid-section yt-CommonOffer carousel-module hotel-trending-destinations&quot;]/div[@class=&quot;container hotel-offers&quot;]/div[@class=&quot;ytCarousel row owl-carousel&quot;]/div[@class=&quot;owl-wrapper-outer&quot;]/div[@class=&quot;owl-wrapper&quot;]/div[@class=&quot;owl-item&quot;]/div[@class=&quot;carousel-item package yss-v&quot;]/a[@class=&quot;eventTrackable&quot;]/img[@class=&quot;lazyOwl item-image&quot;]</value>
      <webElementGuid>792b6a52-8a01-4111-b809-aca79ddc9ae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='collapsibleSection']/section[4]/section[2]/div/div/div/div/div[2]/div/a/img</value>
      <webElementGuid>f495fdc4-b37d-453d-b5fd-de9b594d5b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Udaipur']</value>
      <webElementGuid>eff721b2-925b-4df8-aa8c-414e634ca304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/a/img</value>
      <webElementGuid>d83fb0db-6efe-41d2-849c-77dbd2709a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Udaipur' and @src = '//www.travelguru.com/ythomepagecms/media/trending_destinations/2017/May/4d13579399c4ee08b1c971ddb327a8bb.jpg']</value>
      <webElementGuid>2fa26089-8d98-4eeb-9493-38c3598a9ab7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
