<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select</name>
   <tag></tag>
   <elementGuidId>9c198d5f-81c1-4734-89c1-f2c020f29720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ssrContainer']/div/div/div[4]/div[2]/div/div[4]/div[3]/span[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6e025abf-c4c6-49d9-8875-853bb187f97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>under-link color-blue</value>
      <webElementGuid>a6b457c8-e169-44e4-8e99-fd2867961e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>a11d9715-405c-455a-9861-006b252639f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-hide</name>
      <type>Main</type>
      <value>current.ssrTaken[opt.desc]&amp;&amp; opt.isdata</value>
      <webElementGuid>ebee3eba-9b1e-44e4-8028-9e87aba7508c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>da5d4198-9caf-4f10-9fe4-61b5b2c6bafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ssrContainer&quot;)/div[@class=&quot;box-content ssr-container hide-under-overlay ng-scope&quot;]/div[@class=&quot;flat-ssr&quot;]/div[@class=&quot;text ng-scope&quot;]/div[@class=&quot;col-xs-12 fill ssr-list pr ng-scope&quot;]/div[@class=&quot;scroller-ssr&quot;]/div[@class=&quot;scroll-ssr-elem ng-scope&quot;]/div[@class=&quot;ssr-price&quot;]/span[2]/a[@class=&quot;under-link color-blue&quot;]</value>
      <webElementGuid>d4f4827b-23fa-4791-806d-8fcd283ce1d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ssrContainer']/div/div/div[4]/div[2]/div/div[4]/div[3]/span[2]/a</value>
      <webElementGuid>a608f31a-0f77-4db6-8f28-f5ec46cce031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select')])[11]</value>
      <webElementGuid>834c76b7-7e27-426e-a500-469a8093b697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.'])[36]/following::a[1]</value>
      <webElementGuid>72348a2f-ae40-4806-8a6a-23a5f9bab8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[9]/following::a[1]</value>
      <webElementGuid>b02d80d8-1583-42dc-9bc7-5f11efce1708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.'])[37]/preceding::a[1]</value>
      <webElementGuid>ec1e2d52-049f-47b4-8543-f76cda2994fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[11]/preceding::a[1]</value>
      <webElementGuid>64753fd2-b7fb-490a-92f9-ec3bc522ed46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[23]</value>
      <webElementGuid>4c6b1ea3-7ac3-435b-b811-f761d7a6e34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div[3]/span[2]/a</value>
      <webElementGuid>06289626-d023-4bac-857d-31287d6fa29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>6d4e7c01-ec54-49c4-ba2b-07095ead5f84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
