<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Charter</name>
   <tag></tag>
   <elementGuidId>d22e4bcb-4f8d-4896-b373-f3e43aa8dd19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.no-mad > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BE_flight_form_wrapper']/div/div/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a4f52b6-dccb-48d0-89da-e52cf908bf56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.yatra.com/charter-flights</value>
      <webElementGuid>ece36b7d-fd3d-49f0-9393-bec4203ea92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>35f80f40-949f-4cae-8b95-679f0c645bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>308fe3e4-f973-4a4a-9c3d-056dcd8a30ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                              Charter
                            </value>
      <webElementGuid>3b9300fb-ec70-43dc-888c-746f7f8c84cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_flight_form_wrapper&quot;)/div[@class=&quot;journey-details clearfix&quot;]/div[@class=&quot;trip-type mor-option&quot;]/ul[@class=&quot;selc-flight-options&quot;]/li[@class=&quot;no-mad&quot;]/a[1]</value>
      <webElementGuid>8fab1dc2-0f88-482f-8556-2b31ef0db9dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BE_flight_form_wrapper']/div/div/ul/li[4]/a</value>
      <webElementGuid>d7f082fb-460a-4730-b2f0-7bc7ecb85e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Charter')]</value>
      <webElementGuid>e70d3e6b-647f-4cdf-b99c-424342fd0052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Depart From'])[1]/preceding::a[1]</value>
      <webElementGuid>a81507f0-df05-4df6-8532-096d47afe544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Going To'])[1]/preceding::a[2]</value>
      <webElementGuid>9fba11f1-079d-45d3-a750-2df396892621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Charter']/parent::*</value>
      <webElementGuid>158b5f3f-5611-4bfc-9658-a3222fb45247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.yatra.com/charter-flights')]</value>
      <webElementGuid>d5a687ef-d334-438c-92f1-ef1cf9395d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/ul/li[4]/a</value>
      <webElementGuid>bce6ccf3-31ff-40f8-8bac-9c19b15df6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.yatra.com/charter-flights' and (text() = '
                              Charter
                            ' or . = '
                              Charter
                            ')]</value>
      <webElementGuid>1623bd6e-16ca-400b-83e8-025a93993208</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
