<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gift Voucher NEW</name>
   <tag></tag>
   <elementGuidId>953dd448-5b3c-4dac-8b36-94ddf127e7e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#booking_engine_gift_voucher</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='booking_engine_gift_voucher']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>16e11342-a966-465e-8c2b-c3932c339d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>booking_engine_gift_voucher</value>
      <webElementGuid>5ab8f4dd-501c-4e4e-8538-8dace4c4fd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.yatra.com/online/gift-voucher</value>
      <webElementGuid>6c20182a-4601-41ab-b5b9-ff94613cc5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>7812828c-538b-4645-9991-f408409db1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Gift Voucher</value>
      <webElementGuid>dfe40eaf-28cb-4ea1-8d37-68115d480e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>64941d7a-2d91-4a07-b1d1-b90b0b3fc6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative</value>
      <webElementGuid>5f961ec6-a6af-4c5d-adc9-6c0c874beb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Gift Voucher NEW</value>
      <webElementGuid>2f92759b-a6d5-4453-90d6-83db36fafa14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_engine_gift_voucher&quot;)</value>
      <webElementGuid>0175ff5f-01d2-4583-b217-a286d466bee1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='booking_engine_gift_voucher']</value>
      <webElementGuid>4d91d9fe-1bbf-44b9-8af4-2730b5aca089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bEnginePos']/ul/li[7]/div/ul/li[2]/a</value>
      <webElementGuid>c272fd71-423a-4e84-9830-f611fb441672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW'])[6]/following::a[1]</value>
      <webElementGuid>ba3bced0-247c-45be-9852-e3ccf3a1b9a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabs'])[1]/following::a[1]</value>
      <webElementGuid>b211d6f9-cc66-4441-b009-df68dc405e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.yatra.com/online/gift-voucher')]</value>
      <webElementGuid>fb59ea07-ee91-4a5d-878e-bf49c2de2490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/ul/li[2]/a</value>
      <webElementGuid>e9d009f6-6985-4f13-9b17-00d5bd6ae082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'booking_engine_gift_voucher' and @href = 'https://www.yatra.com/online/gift-voucher' and @title = 'Gift Voucher' and (text() = ' Gift Voucher NEW' or . = ' Gift Voucher NEW')]</value>
      <webElementGuid>556e4be3-38e8-4e3d-ba6f-7df77c98f968</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
