<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Keep In Touch_sprite-footer ico-fresh-twitter</name>
   <tag></tag>
   <elementGuidId>29d278ea-d792-4b4e-a577-90c923972828</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.sprite-footer.ico-fresh-twitter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='footer_content']/div/div/div/div[4]/div/ul[2]/li[2]/span[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7471c2a0-f4d2-440e-9a0d-501a63fa28f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>12a14770-2341-49d8-b4f0-d39c78d0d726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Twitter</value>
      <webElementGuid>61f44812-6f3b-4e8c-9631-07c550fd3680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Twitter</value>
      <webElementGuid>d73db49c-6a71-4f4d-a911-08d8cf5185a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://twitter.com/YatraOfficial</value>
      <webElementGuid>1d820c7a-f4ee-48ab-ad6b-31eeec7abc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sprite-footer ico-fresh-twitter</value>
      <webElementGuid>165d169a-4599-471f-9bf5-004744a59de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer_content&quot;)/div[@class=&quot;ytContainerFluid ytNormFooter fluid-section yatra-footer&quot;]/div[@class=&quot;ytContainerFull&quot;]/div[@class=&quot;footsec js-footer-new js-footer-slide&quot;]/div[@class=&quot;yatraSecure&quot;]/div[@class=&quot;ytContainerFull footer-container&quot;]/ul[@class=&quot;Connect-with-us-footer&quot;]/li[2]/span[2]/a[@class=&quot;sprite-footer ico-fresh-twitter&quot;]</value>
      <webElementGuid>6580951d-c709-4325-a749-1fd90e280004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer_content']/div/div/div/div[4]/div/ul[2]/li[2]/span[2]/a</value>
      <webElementGuid>2719cc83-9c06-486f-b152-282661823067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://twitter.com/YatraOfficial')]</value>
      <webElementGuid>91cbee37-edfe-4b1f-8d4c-5c0da81cf424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span[2]/a</value>
      <webElementGuid>9beaf4d0-79e3-45fc-ade0-0dbc6fd04fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Twitter' and @alt = 'Twitter' and @href = 'https://twitter.com/YatraOfficial']</value>
      <webElementGuid>773939e2-f603-4ba2-94e5-67002c6dec48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
