<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Multi-City</name>
   <tag></tag>
   <elementGuidId>9764ab26-d997-4151-b4d6-7285a8baec2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Multicity&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BE_flight_form_wrapper']/div/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b48cadb5-2398-4251-a2e9-a9a493b4f68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>8117b356-299b-4e3c-80aa-53af8a39ca1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Multicity</value>
      <webElementGuid>34185432-04f7-41de-99ad-328086c34ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flighttrip</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>99e0598b-5401-4e9c-9750-5c1198b18bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Multi-City
                            </value>
      <webElementGuid>1ac4cf22-cf8e-4e3f-bb43-8f15863b51f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_flight_form_wrapper&quot;)/div[@class=&quot;journey-details clearfix&quot;]/div[@class=&quot;trip-type mor-option&quot;]/ul[@class=&quot;selc-flight-options&quot;]/li[@class=&quot;desktop-only&quot;]/a[1]</value>
      <webElementGuid>fe46b7f1-7f4b-42b9-826b-1b19d70dff8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BE_flight_form_wrapper']/div/div/ul/li[3]/a</value>
      <webElementGuid>53b82f28-676e-44ae-946c-3b3fa42f3112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Multi-City')]</value>
      <webElementGuid>3e107697-600d-4ade-8110-c291c06c413b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charter'])[1]/preceding::a[1]</value>
      <webElementGuid>dd3564d4-ee87-46af-9a0f-22ef92fe449d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Depart From'])[1]/preceding::a[2]</value>
      <webElementGuid>8ef7aad8-1601-4552-ba11-59bcd0e9a390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Multi-City']/parent::*</value>
      <webElementGuid>91aca77b-c831-4f91-bfdf-7601e9dbec4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[18]</value>
      <webElementGuid>1fbde471-bf7e-450e-a7bb-fb71004d6687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/div/ul/li[3]/a</value>
      <webElementGuid>2f00c681-c831-40d6-ae6b-b01dd0e88b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @title = 'Multicity' and (text() = ' Multi-City
                            ' or . = ' Multi-City
                            ')]</value>
      <webElementGuid>b675dbf1-5baf-4c3d-a9f8-6e2ab09842d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
