<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Multi-City_flight_origin_date</name>
   <tag></tag>
   <elementGuidId>f8fd01df-a0cb-4b84-8090-27284de602be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_flight_origin_date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BE_flight_origin_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f28dec3c-4572-4818-9aac-d5b9f1006eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>e126abeb-560c-408f-b6e1-5302406fb806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>ecca1a81-4459-410c-8a8e-b914f7d0b82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88c37bdb-f47e-41bd-a97b-175ed40d323f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9a8b199-7d3e-43a8-840c-e41ad9d78f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>flight_origin_date</value>
      <webElementGuid>1faa7a31-1cf1-4170-aa47-271dee267040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_flight_origin_date</value>
      <webElementGuid>ca18e059-44af-464f-8b79-2c0000fb2d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-date-input BE_flight_origin_date</value>
      <webElementGuid>02846ae7-70ac-47c7-9f7f-6429d7ffc1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_flight_origin_date&quot;)</value>
      <webElementGuid>0101f160-80ea-4b19-8ab1-aa57720f8bcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_flight_origin_date']</value>
      <webElementGuid>193efd37-015c-4bdd-9f17-5998a74c98ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BE_flight_form_wrapper']/div/div[2]/ul/li[2]/ul/li/section/label/input</value>
      <webElementGuid>bcce9061-6235-4609-aee3-75f167bf4cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/label/input</value>
      <webElementGuid>54a0eba7-a152-4693-8cb9-b54a126ead91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'flight_origin_date' and @id = 'BE_flight_origin_date']</value>
      <webElementGuid>6c8ea1ae-c59d-4352-a3e6-314b9d7cc1ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
