<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Departure Date_flight_destination_date</name>
   <tag></tag>
   <elementGuidId>461331ae-3b28-4f46-a133-cee7c744835e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_flight_arrival_date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BE_flight_arrival_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>743cd8de-173f-48d3-9b10-5f43ffc56b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2ab1b45a-c355-4ba3-86d4-07f0bd37ec6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>203ff526-4591-4676-b249-18a4be095b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0d69c1e-e32a-4902-8e8c-70c96105c97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>204abd0a-dadd-451d-b7a9-27b07629e07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>flight_destination_date</value>
      <webElementGuid>ee70bd1d-5b5c-4a57-9947-69ab4c7837b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_flight_arrival_date</value>
      <webElementGuid>c3c474e1-9448-4991-83e7-7c9d32d0ce3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-date-input BE_flight_arrival_date</value>
      <webElementGuid>0831d837-8991-4179-a1fe-eb2d829faf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_flight_arrival_date&quot;)</value>
      <webElementGuid>01a39893-1f57-4a1c-9de2-4b0c8b0f7ac4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_flight_arrival_date']</value>
      <webElementGuid>6987eaf0-4194-47df-b3db-b51786992170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='BE_flight_ret_cal']/section/label/input</value>
      <webElementGuid>7f659602-b040-4e53-bb7e-e0ce26b78bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/section/label/input</value>
      <webElementGuid>2a20c802-e81e-4c51-9396-e7943880f9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'flight_destination_date' and @id = 'BE_flight_arrival_date']</value>
      <webElementGuid>1a8ae9f7-ef24-48ae-958e-288882c0f91f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
