<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Non Stop Flights_BE_flight_flsearch_btn</name>
   <tag></tag>
   <elementGuidId>120e36a1-9126-44a9-aee2-0408b645e192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_flight_flsearch_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_flight_flsearch_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40d7146e-fa60-40fa-8291-0289e260a567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>c7e04126-e4e9-41b9-9c09-f5a9caf66d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e2e27099-c232-45f6-a43e-04f149240225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Flights</value>
      <webElementGuid>a9031bf3-cf29-4bfc-afce-5b22546db436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_flight_flsearch_btn</value>
      <webElementGuid>f18500e2-0dc5-40d2-ac98-745617407841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js_ripple search-btn </value>
      <webElementGuid>6a634242-e1a1-4b90-a2d0-e4b8f8f63db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_flight_form_wrapper&quot;)/div[@class=&quot;filter-box flight-filter-box&quot;]/div[@class=&quot;booking-btn-flx&quot;]/div[@class=&quot;ripple-parent search-height demo-icon icon-go&quot;]/input[@id=&quot;BE_flight_flsearch_btn&quot;]</value>
      <webElementGuid>3c622cc3-e7a4-46ec-915f-0015edf64b1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_flight_flsearch_btn']</value>
      <webElementGuid>e2869958-f544-4eb9-a3ff-cf165d1b3088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BE_flight_form_wrapper']/div[3]/div[2]/div/input</value>
      <webElementGuid>e8401b40-4534-4b9a-91d5-cf9efd5c4400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>de5a55e9-fc53-49ef-ae17-882fb51c7a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'BE_flight_flsearch_btn']</value>
      <webElementGuid>2f267af8-5721-4110-b15e-ece54e682554</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
