<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Senior citizen_BE_flight_flsearch_btn</name>
   <tag></tag>
   <elementGuidId>b7145124-895a-4cb5-afcd-3b3820b2fb59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_flight_flsearch_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BE_flight_flsearch_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56bec78d-7988-48dd-bfec-7dcfbd3c14bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b59580b0-cb88-4c15-9ff6-dab524ae86a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ac6ca3a4-e391-43e1-a9f6-19de661be1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Flights</value>
      <webElementGuid>763123b1-b5e7-4222-81d7-981648dd25d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_flight_flsearch_btn</value>
      <webElementGuid>379c77dd-2ec0-4624-884d-6f5a00450448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js_ripple search-btn </value>
      <webElementGuid>bc75f35a-2005-48c5-9c2a-16a58c68791d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_flight_form_wrapper&quot;)/div[@class=&quot;filter-box flight-filter-box&quot;]/div[@class=&quot;booking-btn-flx&quot;]/div[@class=&quot;ripple-parent search-height demo-icon icon-go&quot;]/input[@id=&quot;BE_flight_flsearch_btn&quot;]</value>
      <webElementGuid>ad9541ee-6bcf-476b-b1ee-a022712b52cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_flight_flsearch_btn']</value>
      <webElementGuid>0d29c852-15dd-4a4e-a6db-a0059c04760a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BE_flight_form_wrapper']/div[3]/div[2]/div/input</value>
      <webElementGuid>1d0e3a08-8a54-44b6-a03e-da90c0c27814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>03912336-95b0-449e-8ba3-2e346ec51fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'BE_flight_flsearch_btn']</value>
      <webElementGuid>6c6df888-5183-41ef-bb7a-816c0ae975d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
