<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_More</name>
   <tag></tag>
   <elementGuidId>4a1f9099-0db6-4691-b65f-a7a0d69eb528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bEnginePos']/ul/li[7]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.more-arr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>570351a1-19cc-42be-ab3e-277d5a834d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>more-arr</value>
      <webElementGuid>5236f2f8-3b8b-4386-bc82-aa3296619f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ More</value>
      <webElementGuid>b0ebb02c-33b8-4059-87f6-2722b7a45440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bEnginePos&quot;)/ul[@class=&quot;be-tabs-snipe clearfix&quot;]/li[@class=&quot;list-more-tab&quot;]/span[@class=&quot;more-arr&quot;]</value>
      <webElementGuid>4e6eb7a1-60cd-4aff-8f65-7b1ae0ccb415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ac31f73e-2aa6-455b-a79c-42991a91acd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>more-arr</value>
      <webElementGuid>47b42b5b-4bbc-4a4e-9a15-bfaf2c34d04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ More</value>
      <webElementGuid>123042b6-8490-4cb6-9fee-fa7f12366fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bEnginePos&quot;)/ul[@class=&quot;be-tabs-snipe clearfix&quot;]/li[@class=&quot;list-more-tab&quot;]/span[@class=&quot;more-arr&quot;]</value>
      <webElementGuid>6bbd1e85-9f9b-4434-8e6b-bc8971ee12a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1d27cd56-d445-43d1-b43f-72f2d68d4d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>more-arr</value>
      <webElementGuid>7cfed96e-1107-4ef6-bfbd-6cbb6e1ca31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ More</value>
      <webElementGuid>fdcefc37-75bd-40eb-a6a8-ad3b62dcf285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bEnginePos&quot;)/ul[@class=&quot;be-tabs-snipe clearfix&quot;]/li[@class=&quot;list-more-tab&quot;]/span[@class=&quot;more-arr&quot;]</value>
      <webElementGuid>b6242bdf-ab75-418e-b9db-d18afc71c007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>54ecbea8-761a-496b-9f7b-0d2b654ebfc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>more-arr</value>
      <webElementGuid>ef64ed4a-7099-41ed-b559-63bfaa7c2133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ More</value>
      <webElementGuid>642bf026-9984-483d-b283-7415514f062e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bEnginePos&quot;)/ul[@class=&quot;be-tabs-snipe clearfix&quot;]/li[@class=&quot;list-more-tab&quot;]/span[@class=&quot;more-arr&quot;]</value>
      <webElementGuid>a2c573d4-603f-4d6f-9447-0ef48d33f5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>43c6d9c8-fea4-41bf-8c69-ef794ae44f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>more-arr</value>
      <webElementGuid>5c87eae4-d22c-4fb2-a894-88c0321bdd0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ More</value>
      <webElementGuid>269913cc-c78d-4d3a-8d30-05cc02af3003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bEnginePos&quot;)/ul[@class=&quot;be-tabs-snipe clearfix&quot;]/li[@class=&quot;list-more-tab&quot;]/span[@class=&quot;more-arr&quot;]</value>
      <webElementGuid>c55e05ec-634f-4ac4-b8bd-e5e278dacea6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bEnginePos']/ul/li[7]/span</value>
      <webElementGuid>6cb4f48e-b34c-43ea-82d6-5267565088b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW'])[5]/following::span[1]</value>
      <webElementGuid>1f331af8-0ae5-4c5a-a780-b97f640791e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visa'])[1]/following::span[1]</value>
      <webElementGuid>8daef2fb-7cf6-4458-b268-6c4db7b7f1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabs'])[1]/preceding::span[2]</value>
      <webElementGuid>f47c1b52-540f-46b5-ac10-9608bda81070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW'])[6]/preceding::span[3]</value>
      <webElementGuid>4f3b7064-956b-41c3-8061-f2ef6d31eb7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+ More']/parent::*</value>
      <webElementGuid>53b95744-be73-4dd1-809b-092db3e88a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/span</value>
      <webElementGuid>dd09805e-dc4e-4fc3-abf0-6f8d25e29cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '+ More' or . = '+ More')]</value>
      <webElementGuid>63de2a06-06bd-442d-a529-62f2a70ebf47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
