<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Holidays_demo-icon icon-visa</name>
   <tag></tag>
   <elementGuidId>51d31ea8-8ca1-4cb3-a73d-8073a3d80cf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.demo-icon.icon-visa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='booking_engine_visa']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5cf57079-9903-4e28-8c20-2a4b3e7d371c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demo-icon icon-visa</value>
      <webElementGuid>74b9e6ef-7ce7-4817-b53c-36330d34ab57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_engine_visa&quot;)/div[1]/span[@class=&quot;demo-icon icon-visa&quot;]</value>
      <webElementGuid>a8c63f35-c775-48fb-aa10-ab5c9f553ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>39e4ca2a-7c2b-4d2f-84ea-bfebf751fecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demo-icon icon-visa</value>
      <webElementGuid>cc8cc636-4320-4cfc-abf8-cae574869ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_engine_visa&quot;)/div[1]/span[@class=&quot;demo-icon icon-visa&quot;]</value>
      <webElementGuid>b8c3e9af-562d-4bdd-8970-26637e8ea167</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='booking_engine_visa']/div/span</value>
      <webElementGuid>d3971783-e6ca-4259-80b8-806b709f2eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/div/span</value>
      <webElementGuid>69faa19e-7a4e-48cf-9084-088e4ea1becf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
