<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Freight</name>
   <tag></tag>
   <elementGuidId>47053aad-d0a6-499c-9e81-57df138a4821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#booking_engine_freight > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='booking_engine_freight']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d52eb512-fb87-4511-afbd-1a218d249d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Freight</value>
      <webElementGuid>78da0502-3d42-4dc9-b521-c924231b7a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_engine_freight&quot;)/span[1]</value>
      <webElementGuid>fc85f41e-2e36-4602-aca1-862217e4dc4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='booking_engine_freight']/span</value>
      <webElementGuid>a1db115b-ad62-4b05-a6e7-b8ff75789a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cruise'])[1]/following::span[2]</value>
      <webElementGuid>b3afc15f-b2c5-4240-8dee-482b28bb83b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trains'])[2]/following::span[4]</value>
      <webElementGuid>4d2d1694-15a6-40f0-8fde-57d0a4cc684a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adventures'])[1]/preceding::span[2]</value>
      <webElementGuid>61b2b7e7-2a88-43ce-96b5-f84fa0a10b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW'])[8]/preceding::span[3]</value>
      <webElementGuid>4ca704e8-7957-4c2e-9e0e-6a4a957bc3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Freight']/parent::*</value>
      <webElementGuid>0cc2f13f-fcca-42b4-9ce4-21a825466571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/ul/li[5]/a/span</value>
      <webElementGuid>0e26efb1-6281-4644-9006-31b9311412f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Freight' or . = 'Freight')]</value>
      <webElementGuid>83ffc000-7479-4064-bee1-1c2cded5a788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
