<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Flights_demo-icon icon-hotels</name>
   <tag></tag>
   <elementGuidId>7873f30e-55d2-4907-8b96-e03347c61576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.demo-icon.icon-hotels</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='booking_engine_hotels']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>49f1b399-bc66-4914-8693-3c13176f2ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demo-icon icon-hotels</value>
      <webElementGuid>72337009-9624-4a42-bfc4-b5b78150db1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_engine_hotels&quot;)/div[1]/span[@class=&quot;demo-icon icon-hotels&quot;]</value>
      <webElementGuid>b36294a8-2bd2-4276-b917-6d2245112d04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='booking_engine_hotels']/div/span</value>
      <webElementGuid>41840dfd-fd1a-42ee-8824-39a9ac55d786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/span</value>
      <webElementGuid>5033b0e9-8262-42f1-a394-7e9f4224dcfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
