<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cabs</name>
   <tag></tag>
   <elementGuidId>d5812685-37c7-43e5-88d9-c7c79c9c34a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#booking_engine_cabs > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='booking_engine_cabs']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7c9f37b3-825f-40d2-9834-e403c194cdff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cabs</value>
      <webElementGuid>a10d8ab3-0c9f-4c0f-a280-6454ee0a4385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_engine_cabs&quot;)/span[1]</value>
      <webElementGuid>be6cfe77-9960-48e1-a583-95ad11cba0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6681caf2-9d36-4b8e-aeef-319ef5d45e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cabs</value>
      <webElementGuid>fdea491d-bd97-435d-a7d2-44d1f4e342c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_engine_cabs&quot;)/span[1]</value>
      <webElementGuid>649b3bd2-bfb7-4e39-a5c3-5141df64da9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='booking_engine_cabs']/span</value>
      <webElementGuid>6f859588-f128-40ca-90f0-e10c4b754654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ More'])[1]/following::span[2]</value>
      <webElementGuid>851b9a19-24dd-4975-88aa-3ea3a6ea09f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW'])[5]/following::span[3]</value>
      <webElementGuid>af659108-93db-4f3f-bfdf-d39655b9e8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW'])[6]/preceding::span[1]</value>
      <webElementGuid>e65b3d30-7cc7-4c4a-8693-9a1cb7d6bbd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gift Voucher'])[1]/preceding::span[2]</value>
      <webElementGuid>15706843-dae3-4908-aa9b-92419fe3a15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cabs']/parent::*</value>
      <webElementGuid>956fa8a6-ab5b-45bd-a151-898f1de333c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/ul/li/a/span</value>
      <webElementGuid>65487eeb-c9ce-449a-9ed1-146485f5bf83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cabs' or . = 'Cabs')]</value>
      <webElementGuid>7d7cefec-0078-4db0-8967-bf07f2874430</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
