<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Domestic Flights</name>
   <tag></tag>
   <elementGuidId>19db2253-1154-43c3-a900-5e996dc0710f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='themeSnipe']/section/div[2]/section[3]/div/div[2]/div/div/div/a[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cf0e447d-7542-4492-b287-bea4268a8f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Domestic Flights</value>
      <webElementGuid>86e06351-8944-4605-8ed6-870ee810b675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;themeSnipe&quot;)/section[@class=&quot;wrapper&quot;]/div[@class=&quot;right_data&quot;]/section[@class=&quot;carousalModuleArea yt-CommonOffer todays-pick-main todays-pick-main-temp&quot;]/div[1]/div[@class=&quot;ytCarousel&quot;]/div[@class=&quot;VueCarousel&quot;]/div[@class=&quot;VueCarousel-wrapper&quot;]/div[@class=&quot;VueCarousel-inner&quot;]/a[@class=&quot;VueCarousel-slide slide package super-offer eventTrackable js-prodSpecEvtCat&quot;]/div[@class=&quot;image-holder&quot;]/span[1]</value>
      <webElementGuid>a6ccde10-24a3-446c-a1c3-c47535aa610c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='themeSnipe']/section/div[2]/section[3]/div/div[2]/div/div/div/a[2]/div/span</value>
      <webElementGuid>c3c404f6-683e-422a-8c36-7be1d9fd1840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domestic Flights'])[1]/following::span[1]</value>
      <webElementGuid>d1c12299-c851-4304-8331-fdb163f83449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/following::span[2]</value>
      <webElementGuid>8fc886ab-50ee-4812-9d0e-66fd59d91347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='International Flights'])[1]/preceding::span[1]</value>
      <webElementGuid>084b5763-183a-4184-9bc9-15f072343cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domestic Flights'])[3]/preceding::span[2]</value>
      <webElementGuid>d213a8ca-b60d-4c61-8f91-77e208a39e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/span</value>
      <webElementGuid>45836646-fbca-485f-b9e3-b521fa41f8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Domestic Flights' or . = 'Domestic Flights')]</value>
      <webElementGuid>ea5e14c3-4ce6-485a-b6ba-9d5bcd218255</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
