<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_11                                      _41ab78</name>
   <tag></tag>
   <elementGuidId>fcbc1c8e-52ac-47fa-8bcf-30311ae1431c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='11/05/2022']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9f17c391-f68c-4f59-b2a8-1a57d893a744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>11/05/2022</value>
      <webElementGuid>b3438cd8-ca7c-47f5-8224-e8a93e383264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Wednesday, 11 May 2022</value>
      <webElementGuid>c144bc2f-8d8b-42dc-bec0-3deeffa338d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>11/05/2022</value>
      <webElementGuid>c2092765-36bc-4fdf-a2b1-e0d2bfa33f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        11
                                                         8,477</value>
      <webElementGuid>228290f0-e3eb-4f8d-9551-a0ffbb453c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;11/05/2022&quot;)</value>
      <webElementGuid>bd1903c6-219e-441b-93de-e2b88d16e854</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='11/05/2022']</value>
      <webElementGuid>ec9f6d98-75ae-423a-9410-0189af06cece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='month-scroll1']/div/div[2]/table/tbody/tr[2]/td[4]</value>
      <webElementGuid>e8d20eed-1a64-487f-be71-a3097cc6cb1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('May', &quot;'&quot;, ' 22')])[1]/following::td[11]</value>
      <webElementGuid>c73784b1-fa04-43d3-85cb-a55adfe3581c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::td[25]</value>
      <webElementGuid>ee612d81-b0ee-4a50-b904-445e53630690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('June', &quot;'&quot;, ' 22')])[1]/preceding::td[25]</value>
      <webElementGuid>6f22ce04-e0a7-401a-8ba7-59a43390b5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('July', &quot;'&quot;, ' 22')])[1]/preceding::td[60]</value>
      <webElementGuid>2335ef21-5807-4371-99e0-e6889e01bbb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='11']/parent::*</value>
      <webElementGuid>1f11efc6-6926-4ca5-80d7-44a2dab79437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[4]</value>
      <webElementGuid>84a61cc1-b501-42b5-8e4e-c150d935cd49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Wednesday, 11 May 2022' and @id = '11/05/2022' and (text() = '
                                                        11
                                                         8,477' or . = '
                                                        11
                                                         8,477')]</value>
      <webElementGuid>07134ed7-b00d-497d-8683-2054fec33b31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
