<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_2                                       _00edea</name>
   <tag></tag>
   <elementGuidId>47ddb567-9d21-404d-8ed3-e7dacb8c6d54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='02/05/2022']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>488da102-ca95-473d-8f0f-cd1cbe88f2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>02/05/2022</value>
      <webElementGuid>b3c505f3-d08c-4a77-b37d-72b37ff6b20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Monday, 2 May 2022</value>
      <webElementGuid>ead4b2ab-58ac-4787-850e-b99e7d7d7f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>02/05/2022</value>
      <webElementGuid>767afe30-20c1-418b-9f56-ef6adfa14cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        2
                                                         4,678</value>
      <webElementGuid>27291065-d1ed-49e3-a44b-e0ad12513d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;02/05/2022&quot;)</value>
      <webElementGuid>5cf7a5a8-e922-441c-9ae6-eebc1adffb91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='02/05/2022']</value>
      <webElementGuid>4b6748b3-c57d-41a4-8bfe-c62bdafa3407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='month-scroll1']/div/div[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>8ec2383f-2c32-486e-afc5-e1a0f9cb9488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('May', &quot;'&quot;, ' 22')])[1]/following::td[2]</value>
      <webElementGuid>486b0c63-7a23-4f7b-803f-6c759beff04a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::td[16]</value>
      <webElementGuid>dad1466b-2d8d-4df8-87b6-a76d4201b679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('June', &quot;'&quot;, ' 22')])[1]/preceding::td[34]</value>
      <webElementGuid>716aba30-10d2-41d1-a567-6df4e6a610d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('July', &quot;'&quot;, ' 22')])[1]/preceding::td[69]</value>
      <webElementGuid>74090f72-acc8-405b-9cc4-e9c7d91b6f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>8601c6ce-9cff-4ff7-913c-ef44a3fc8263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>fcfa0dfa-1a44-40a9-b273-a76788b375e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Monday, 2 May 2022' and @id = '02/05/2022' and (text() = '
                                                        2
                                                         4,678' or . = '
                                                        2
                                                         4,678')]</value>
      <webElementGuid>ce311c8e-26c3-4d63-adcc-8d3faed3b7e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
