<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__a-z1b7haz0w3ev</name>
   <tag></tag>
   <elementGuidId>b4383beb-c80d-4d96-814d-fb7f9e061396</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-z1b7haz0w3ev&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-z1b7haz0w3ev']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a61568dc-27b7-45ec-9797-00a1319e6478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>69e7fef5-3215-46d3-8b87-da7d9b3e2be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LelHKwaAAAAAAkcYHXGeHd6UYrcnektUrkLfLSY&amp;co=aHR0cHM6Ly9hcHAueWF0cmFmcmVpZ2h0LmNvbTo0NDM.&amp;hl=en&amp;v=QENb_qRrX0-mQMyENQjD6Fuj&amp;size=normal&amp;cb=r7v8m962k59z</value>
      <webElementGuid>c5d47248-cabe-497f-81de-3d3dceeb0086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>0a7175f4-a7f9-46fe-8b88-599766ed05fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>e112dda5-d2ad-454f-b267-c1c927b34b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>40120a88-17de-4131-9d26-29ee16826e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-z1b7haz0w3ev</value>
      <webElementGuid>2b46ef53-ccb7-4953-bff4-398243891bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>87c29270-ff33-4138-8725-8e747f507417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2a7f9209-386d-4a3a-9ad8-999e0f44ce46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>337626a4-b175-4856-b5c2-1832b16631de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>85f4f707-a551-4ecc-98b9-d83e79d7e24f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-z1b7haz0w3ev']</value>
      <webElementGuid>5144c6de-0b1a-4834-8f4a-7947fd9f906a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recaptcha']/div/div/iframe</value>
      <webElementGuid>55f4534d-7de8-4abd-8300-54064aefe2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>823c27ec-abd9-4c80-87df-57164c67ab9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LelHKwaAAAAAAkcYHXGeHd6UYrcnektUrkLfLSY&amp;co=aHR0cHM6Ly9hcHAueWF0cmFmcmVpZ2h0LmNvbTo0NDM.&amp;hl=en&amp;v=QENb_qRrX0-mQMyENQjD6Fuj&amp;size=normal&amp;cb=r7v8m962k59z' and @name = 'a-z1b7haz0w3ev']</value>
      <webElementGuid>c70f4fad-51fd-42d6-8668-87b38a8c65be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
