<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From CityPort_ng-untouched ng-pristin_c68536</name>
   <tag></tag>
   <elementGuidId>af6a3fd2-0afe-4c70-8c4b-a714c2285778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44b3e961-11be-421b-8ec9-42136c74eb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e49906a9-f41f-446e-8cac-93577a243342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c4bca11d-cf9f-460a-960e-200064c6607f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/app-root[1]/div[1]/div[@class=&quot;app-container full-width&quot;]/div[@class=&quot;main-content&quot;]/app-landing[1]/div[@class=&quot;landing&quot;]/div[@class=&quot;content&quot;]/div[1]/core-page-divs[1]/div[2]/div[@class=&quot;flex-1-3 landing-main&quot;]/div[@class=&quot;landing-left-cont&quot;]/div[@class=&quot;flex-row page-div widgets&quot;]/div[@class=&quot;widget&quot;]/div[1]/div[@class=&quot;widget-body&quot;]/landing-widgets-selector[1]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/div[@class=&quot;sections ng-star-inserted&quot;]/landing-quote[1]/div[@class=&quot;flex-row centered&quot;]/div[@class=&quot;middle rfqDiv&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator inline fixMarginTop quote-request-form&quot;]/dff-guest-inquery[1]/div[@class=&quot;ng-star-inserted&quot;]/div[1]/div[@class=&quot;flex-row two&quot;]/div[3]/div[@class=&quot;oa-input&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>0e33ca51-f28a-4fb4-8415-a6eaa28d4088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88faa2f1-f60b-442a-b288-155a6cb7ea52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91aadf97-3710-4f24-b548-9e4936cf4293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c527434a-6bec-454d-bb2e-67f4a6623d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/app-root[1]/div[1]/div[@class=&quot;app-container full-width&quot;]/div[@class=&quot;main-content&quot;]/app-landing[1]/div[@class=&quot;landing&quot;]/div[@class=&quot;content&quot;]/div[1]/core-page-divs[1]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex-1-3 landing-main ng-star-inserted&quot;]/div[@class=&quot;landing-left-cont ng-star-inserted&quot;]/div[@class=&quot;flex-row page-div widgets ng-star-inserted&quot;]/div[@class=&quot;widget ng-star-inserted&quot;]/div[1]/div[@class=&quot;widget-body&quot;]/landing-widgets-selector[@class=&quot;ng-star-inserted&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/div[@class=&quot;sections ng-star-inserted&quot;]/landing-quote[1]/div[@class=&quot;flex-row centered&quot;]/div[@class=&quot;middle rfqDiv&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator inline fixMarginTop quote-request-form&quot;]/dff-guest-inquery[1]/div[@class=&quot;ng-star-inserted&quot;]/div[1]/div[@class=&quot;flex-row two&quot;]/div[3]/div[@class=&quot;oa-input&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>67a84268-eeea-4b72-bcac-485ae7cf78c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>4eee6cd3-b60b-41be-b346-7889e47f1ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>b1d33c51-d2ec-4955-aa8f-e1ac978a55c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>53160c8e-2a89-4b84-a96f-b0b64a6ba1c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
