<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Im not a robot</name>
   <tag></tag>
   <elementGuidId>84a19c4c-38b7-47e1-9870-b066bacd174a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recaptcha-anchor-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='recaptcha-anchor-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0dc04fb0-d2cb-4beb-8e38-1bbe3f9105f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-anchor-center-item rc-anchor-checkbox-label</value>
      <webElementGuid>479f5d14-e6a2-42b3-914d-ec3ac5ca1623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c5ab617-af43-4961-9fe7-c3240eb2eb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>54689844-84a9-4ebf-b2ad-489af8cf200f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recaptcha-anchor-label</value>
      <webElementGuid>e98a4e13-51b7-4427-8b80-90ead5d292c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I'm not a robot</value>
      <webElementGuid>09c51424-3db0-487d-b816-19a662c8f9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-anchor-label&quot;)</value>
      <webElementGuid>07536428-20f3-4cfd-85d4-18187ca7478e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Landing/iframe__a-z1b7haz0w3ev</value>
      <webElementGuid>a26fb24e-a114-4d92-b1b0-7678f211fcd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='recaptcha-anchor-label']</value>
      <webElementGuid>9f25d237-80df-40c7-95d1-8d273847cc34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-anchor-container']/div[3]/div[2]/div/label</value>
      <webElementGuid>45975ea1-7157-49d9-afd2-1e0dc62ffc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='reCAPTCHA'])[2]/preceding::label[1]</value>
      <webElementGuid>facd6a08-2c56-4c7f-8c7f-977eecf8c313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/preceding::label[1]</value>
      <webElementGuid>7fcd970b-cf27-4e0f-953d-193073ccf527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>e6ba6f4a-3347-4e81-8a07-97d1c3ca59e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'recaptcha-anchor-label' and (text() = concat(&quot;I&quot; , &quot;'&quot; , &quot;m not a robot&quot;) or . = concat(&quot;I&quot; , &quot;'&quot; , &quot;m not a robot&quot;))]</value>
      <webElementGuid>7e13e4a0-6da9-4e3a-9d96-0988b83582f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
