<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PROCEED</name>
   <tag></tag>
   <elementGuidId>240a6069-b2ec-4bef-b357-f5f268f580f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3c14579-dec1-4b35-8211-4a81a5b568e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>edb5da92-9092-435f-857f-0e72b7699ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PROCEED</value>
      <webElementGuid>b5a7d9d4-7ff5-4b58-919e-6bbf9f92f91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/app-root[1]/div[1]/div[@class=&quot;app-container full-width&quot;]/div[@class=&quot;main-content&quot;]/app-landing[1]/div[@class=&quot;landing&quot;]/div[@class=&quot;content&quot;]/div[1]/core-page-divs[1]/div[2]/div[@class=&quot;flex-1-3 landing-main&quot;]/div[@class=&quot;landing-left-cont&quot;]/div[@class=&quot;flex-row page-div widgets&quot;]/div[@class=&quot;widget&quot;]/div[1]/div[@class=&quot;widget-body&quot;]/landing-widgets-selector[1]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/div[@class=&quot;sections ng-star-inserted&quot;]/landing-quote[1]/div[@class=&quot;flex-row centered&quot;]/div[@class=&quot;middle rfqDiv&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator inline fixMarginTop quote-request-form&quot;]/dff-guest-inquery[1]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;controls-row&quot;]/button[@class=&quot;mat-focus-indicator mat-raised-button mat-button-base mat-primary cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>d89d5e27-c9e0-4eeb-bf71-43ad49cc3a77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/following::span[1]</value>
      <webElementGuid>aa4ea3da-8657-4bce-823e-520f8dd064b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description of goods'])[1]/following::span[1]</value>
      <webElementGuid>9ba1d7d0-caaf-43f7-8abe-fa2a106aa49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Full Name'])[1]/preceding::span[3]</value>
      <webElementGuid>70117eff-0b94-4d35-ad77-2fb61cc6dc82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PROCEED']/parent::*</value>
      <webElementGuid>a29c4d9d-fcff-4684-83f3-4304f2f355db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>3000f2b3-b06b-4ea5-9099-b2352fcb6ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PROCEED' or . = 'PROCEED')]</value>
      <webElementGuid>80439d47-0b67-42ac-9577-c5dd2e098ff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
