<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>2a3d99a8-ec1c-4bf9-b1f1-29cfc459bdb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://openage.github.io/themes/yatra/v1/icons/main-home/red/personalised-dashboard.svg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0b3f934f-d3b6-484d-b1cd-8e746ece96dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://openage.github.io/themes/yatra/v1/icons/main-home/red/personalised-dashboard.svg</value>
      <webElementGuid>eb1b0e21-5346-48f2-a9a4-5bd40393963c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/app-root[1]/div[1]/div[@class=&quot;app-container full-width&quot;]/div[@class=&quot;main-content&quot;]/app-landing[1]/div[@class=&quot;landing&quot;]/div[@class=&quot;content&quot;]/div[1]/core-page-divs[1]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex-1-3 landing-main ng-star-inserted&quot;]/div[@class=&quot;landing-right-cont ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;align-items-center justify-content-center d-flex tet-borders flex-column landing-banner-content pt-5 pb-5 ng-star-inserted&quot;]/div[@class=&quot;d-flex flex-wrap ng-star-inserted&quot;]/div[@class=&quot;banner-card ng-star-inserted&quot;]/div[@class=&quot;banner-card-inner d-flex flex-nowrap align-items-center ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/img[1]</value>
      <webElementGuid>ee0c87b4-5079-40c9-a6a4-541a5536aeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f4ca6a05-738c-4484-9b8c-af17e51e9907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://openage.github.io/themes/yatra/v1/icons/main-home/red/transportation-rates.svg</value>
      <webElementGuid>3254b4f0-baf6-4ecb-a644-a7162176fcce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/app-root[1]/div[1]/div[@class=&quot;app-container full-width&quot;]/div[@class=&quot;main-content&quot;]/app-landing[1]/div[@class=&quot;landing&quot;]/div[@class=&quot;content&quot;]/div[1]/core-page-divs[1]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex-1-3 landing-main ng-star-inserted&quot;]/div[@class=&quot;landing-right-cont ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;align-items-center justify-content-center d-flex tet-borders flex-column landing-banner-content pt-5 pb-5 ng-star-inserted&quot;]/div[@class=&quot;d-flex flex-wrap ng-star-inserted&quot;]/div[@class=&quot;banner-card ng-star-inserted&quot;]/div[@class=&quot;banner-card-inner d-flex flex-nowrap align-items-center ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/img[1]</value>
      <webElementGuid>f26e5a9c-c8fd-4309-bf1c-b2c2412e5172</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://openage.github.io/themes/yatra/v1/icons/main-home/red/personalised-dashboard.svg')]</value>
      <webElementGuid>a0536009-ca22-41b4-b1b7-c4b71d25d1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/img</value>
      <webElementGuid>7ed33707-307c-4b4a-90d6-7ec36b4ed135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://openage.github.io/themes/yatra/v1/icons/main-home/red/personalised-dashboard.svg']</value>
      <webElementGuid>e28ca74f-060b-4af9-b5b6-e3fb058bf225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://openage.github.io/themes/yatra/v1/icons/main-home/red/transportation-rates.svg')]</value>
      <webElementGuid>57c5809d-81db-4685-b792-0c42068ebbc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>43540113-8d8d-4a82-b9a2-24eb4f55b67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://openage.github.io/themes/yatra/v1/icons/main-home/red/transportation-rates.svg']</value>
      <webElementGuid>e1f97423-b5ab-4a88-9a02-9c6ef9d44f47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
