<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_s_BE_flight_flsearch_btn</name>
   <tag></tag>
   <elementGuidId>1a6f60bc-a0c1-4352-b9fe-efa965f2f0dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_flight_flsearch_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_flight_flsearch_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d460600-f6a9-4dd4-825d-08e3ae4de662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>41a2620f-4083-4736-b177-626c4fb64cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f2a8bbf4-6b69-483a-b254-689ef5521ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit Request</value>
      <webElementGuid>d22ecd7f-7e0b-4200-90bf-987dd13a3188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_flight_flsearch_btn</value>
      <webElementGuid>686e7084-1b85-44ec-8f0b-162436319c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js_ripple search-btn </value>
      <webElementGuid>ad6e7868-5f1b-4d1d-9709-e6381bc89fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_flight_flsearch_btn&quot;)</value>
      <webElementGuid>9aadbfa1-dd7a-4b0c-92f6-53dbe4fb358f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_flight_flsearch_btn']</value>
      <webElementGuid>d7cba3b1-ab8d-4dc5-98da-aa0854d7a1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BE_flight_form_wrapper']/div[3]/div/input</value>
      <webElementGuid>6e4e353c-d64e-459e-9d1b-0e9547bb4d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>d90c036e-b6b9-4348-a6e7-87e7bb5a5122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'BE_flight_flsearch_btn']</value>
      <webElementGuid>2173de7f-df6f-4121-8981-9160bc03fe4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
