<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Save upto 40 with usage based pricing_bca950</name>
   <tag></tag>
   <elementGuidId>200c72dc-c958-46e2-ab98-658965ebac7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_hotel_checkin_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_hotel_checkin_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afb3cd15-438b-47d9-b98a-01f68b3ac7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>1b16a692-3950-4c68-9a2f-895d077d3381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>aa2019e0-e909-4b0a-9b6c-47ecbd6b6035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95999e4e-4594-4f94-bb4a-1541693b9f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1e750587-1828-4ec4-8761-03e20b0d8094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hotel_checkin_date</value>
      <webElementGuid>4492303d-1a45-4865-af39-05e5b2048aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_hotel_checkin_date</value>
      <webElementGuid>96482642-1c73-47d5-a6fe-b97116afd457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-date-input BE_hotel_checkin_date</value>
      <webElementGuid>6b895fc9-4d5b-4f49-94b4-dd8155f3d960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_hotel_checkin_date&quot;)</value>
      <webElementGuid>dc827229-7385-447b-b3f5-a5c891f8c0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8228aa0-2e2a-4b34-8d54-e35c19b8b82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>43ee0716-7de8-4e9a-bec5-f8be708da884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>688df1ba-d891-4eb8-8a1e-87b09a129dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11eeb0f4-13ec-415f-be39-45a948b7610f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>09485539-f58f-476d-a9ad-e2cf889de4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hotel_checkin_date</value>
      <webElementGuid>cff38390-ee8c-4e25-a7d9-ca4191e44b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_hotel_checkin_date</value>
      <webElementGuid>6f4707ef-23f4-4fd0-88f5-c573e49e2262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-date-input BE_hotel_checkin_date</value>
      <webElementGuid>c874488b-bce5-43bf-a5a6-76b51cb78fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_hotel_checkin_date&quot;)</value>
      <webElementGuid>69d3f565-bfcc-483b-9f6a-9f38fd5da6be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_hotel_checkin_date']</value>
      <webElementGuid>9ca8ff0e-0ae6-4e78-b305-91daaaf830e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div/div[2]/ul/li[2]/ul/li/section/label/input</value>
      <webElementGuid>f1ef121e-89a9-43b7-b3cc-85275f60723f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/label/input</value>
      <webElementGuid>de589a6d-07ca-42cc-acd3-a27e7e81bdd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'hotel_checkin_date' and @id = 'BE_hotel_checkin_date']</value>
      <webElementGuid>0bd0b903-56ef-44fe-88a6-a1d826a30385</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
