<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Done_BE_hotel_htsearch_btn</name>
   <tag></tag>
   <elementGuidId>dbbda55e-dd30-49d8-a0d4-ec61655a4f5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_hotel_htsearch_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_hotel_htsearch_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42c9a2d4-cf5e-4887-928c-291f49b6356f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>f6817630-1e06-4a20-9a71-a72b985c401f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6fff66f2-e598-4188-a8a0-c34f1e39f82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Villas</value>
      <webElementGuid>5ce9501f-5b22-41db-b8c0-3fdfc1d71ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackcategory</name>
      <type>Main</type>
      <value>Home Page</value>
      <webElementGuid>40143e08-6fca-46a8-9631-8132daf3ec6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackaction</name>
      <type>Main</type>
      <value>Booking Engine</value>
      <webElementGuid>d9caefbf-da07-4e84-b053-e998b22abf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackvalue</name>
      <type>Main</type>
      <value>Hotels Tab - Find Hotels</value>
      <webElementGuid>48930387-5e3c-4246-8e8d-3d2feb2a1188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_hotel_htsearch_btn</value>
      <webElementGuid>ed258521-904c-4b88-8218-b3581b1539f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js_ripple search-btn search-flights-btn eventTrackable js-prodSpecEvtCat</value>
      <webElementGuid>7ac69d1a-d289-4ada-84bd-cfbe78fb992b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_hotel_htsearch_btn&quot;)</value>
      <webElementGuid>dd97ac31-ce14-45ad-baa3-c99b5a1a6bd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_hotel_htsearch_btn']</value>
      <webElementGuid>2fef7d36-1fba-4941-9ec5-f0bee30d3575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div[2]/div[2]/input</value>
      <webElementGuid>ce4398e1-cbd2-4203-8e63-3268f6f35b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>3321d4cf-40af-4f75-8b6e-ab32a489d28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'BE_hotel_htsearch_btn']</value>
      <webElementGuid>0a68a912-af6a-4bd0-9cbb-8333460ca2c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
