<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_10</name>
   <tag></tag>
   <elementGuidId>b053d052-d7f2-4563-88ed-c27971eb51d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='10/05/2022']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9d39af34-380f-4153-b6f6-6fbabf69c653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>10/05/2022</value>
      <webElementGuid>6f954544-64b7-4ebd-b471-d6af0f865647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tuesday, 10 May 2022</value>
      <webElementGuid>79098223-4fef-4279-bc90-b8dfe80ed424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>10/05/2022</value>
      <webElementGuid>8cb1437e-c72c-414a-9f38-61f7a994522c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        10
                                                         </value>
      <webElementGuid>a15fd61b-bc81-445c-a14f-9382cacc013a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;10/05/2022&quot;)</value>
      <webElementGuid>21ed7e03-c91f-4b3d-8aa1-c5aae1f3cd04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='10/05/2022']</value>
      <webElementGuid>66f78700-4e8f-4a10-b0f9-5fd5aebe1058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='month-scroll1']/div/div[2]/table/tbody/tr[2]/td[3]</value>
      <webElementGuid>f0e1eb84-8eec-4cc7-b970-7d9dea29550e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('May', &quot;'&quot;, ' 22')])[1]/following::td[10]</value>
      <webElementGuid>fd379786-617b-4dee-9c1e-c42e5822a114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::td[24]</value>
      <webElementGuid>27802ad8-30c9-40fe-a28a-b55e8ba72edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('June', &quot;'&quot;, ' 22')])[1]/preceding::td[26]</value>
      <webElementGuid>70808022-5e6b-4683-9cba-4f5367cf520b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('July', &quot;'&quot;, ' 22')])[1]/preceding::td[61]</value>
      <webElementGuid>90107057-a507-43a9-ade8-0cc8de1bf709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10']/parent::*</value>
      <webElementGuid>f1f5ab5b-2303-47a2-b8ab-0f342ca1e6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[3]</value>
      <webElementGuid>40cbe495-18fd-4b3a-a445-f00531087326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Tuesday, 10 May 2022' and @id = '10/05/2022' and (text() = '
                                                        10
                                                         ' or . = '
                                                        10
                                                         ')]</value>
      <webElementGuid>94f329e0-fff5-492f-9b75-2a1bd69c9ef8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
