<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pune-Hyderabad</name>
   <tag></tag>
   <elementGuidId>d1c0d538-0700-4c09-91c2-296916db5a00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-tabs__div.mobile-tab > a.v-tabs__item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='busDesktop']/div/div[6]/div[101]/div/section/div[2]/div/div/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a66965aa-e5e1-479f-aab0-73c386be1d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#city</value>
      <webElementGuid>90c9bc69-d3e4-41c6-86cc-4ea30c36e7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-tabs__item</value>
      <webElementGuid>ad3ce00b-d437-4fc7-a6e1-a2b5ceafec1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-previous-position</name>
      <type>Main</type>
      <value>static</value>
      <webElementGuid>4404de69-1017-4b41-9757-faf62bdf17de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Pune-Hyderabad
               </value>
      <webElementGuid>d31aadb5-906d-45a4-a1f6-d4e026819a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;busDesktop&quot;)/div[@class=&quot;bus-srp-list-view&quot;]/div[@class=&quot;srp-body&quot;]/div[@class=&quot;menu-modal&quot;]/div[@class=&quot;menu-body&quot;]/section[1]/div[@class=&quot;col-right hideSmall&quot;]/div[@class=&quot;v-tabs&quot;]/div[@class=&quot;v-tabs__bar theme--dark&quot;]/div[@class=&quot;v-tabs__wrapper&quot;]/div[@class=&quot;v-tabs__container&quot;]/div[@class=&quot;v-tabs__div mobile-tab&quot;]/a[@class=&quot;v-tabs__item&quot;]</value>
      <webElementGuid>f394d8f1-d6b7-4137-894a-ea99c50bb45c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='busDesktop']/div/div[6]/div[101]/div/section/div[2]/div/div/div/div/div[2]/a</value>
      <webElementGuid>ba657428-6667-44f3-a2e1-e54c33bde2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pune-Hyderabad')]</value>
      <webElementGuid>55770dd7-2418-48cc-aaf7-084c9c0046a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/following::a[1]</value>
      <webElementGuid>725534dd-c156-4a12-aee4-f87bffadf260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Male'])[1]/following::a[1]</value>
      <webElementGuid>6fc1d1b9-02b7-46bf-9f49-92bf72fb46f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boarding Points'])[2]/preceding::a[1]</value>
      <webElementGuid>9eab8f9f-6be9-4331-b4bd-020fa0433ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropping Points'])[2]/preceding::a[2]</value>
      <webElementGuid>5f9464da-0af4-4415-bc56-dacb0c639032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pune-Hyderabad']/parent::*</value>
      <webElementGuid>b64e10ed-19a7-4143-811a-02868d2e4ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#city')]</value>
      <webElementGuid>67e89d08-c6bf-4600-95b2-dff5ce6cf820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/a</value>
      <webElementGuid>79c9b5d6-13b7-47a7-ae7b-8ba52bc75469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#city' and (text() = '
                  Pune-Hyderabad
               ' or . = '
                  Pune-Hyderabad
               ')]</value>
      <webElementGuid>4316c7fb-a6f5-4999-81e5-06debcc5f2b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
