<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select Seat</name>
   <tag></tag>
   <elementGuidId>12d37c37-01e7-433f-be9a-d72dce9aea4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f8fd349b-a497-4387-bf7a-a3fb06d06c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>563dabfb-f97b-4674-b2d4-5b1c2a8ff799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-red mr0 v-btn theme--light</value>
      <webElementGuid>872adeff-b2db-48ad-8419-9984657df526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Seat</value>
      <webElementGuid>34430cd2-d3a0-4c0f-b93c-7057eea3945e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;busDesktop&quot;)/div[@class=&quot;bus-srp-list-view&quot;]/div[@class=&quot;srp-body&quot;]/div[@class=&quot;v-card__text srp-touple&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;flex txt-r xs2 hide-md&quot;]/button[@class=&quot;btn-red mr0 v-btn theme--light&quot;]</value>
      <webElementGuid>621bcd4a-f7f4-494a-909f-1cbe55b85768</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[13]</value>
      <webElementGuid>0d73d44c-2ad9-446b-9d71-78103bdd5192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='busDesktop']/div/div[6]/div[12]/div/div[6]/button</value>
      <webElementGuid>76824175-d0ef-4dfc-999e-542a543cae19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[10]/following::button[1]</value>
      <webElementGuid>b95133c9-5f7a-4321-a392-548d091bc869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boarding/Dropping Points'])[10]/following::button[1]</value>
      <webElementGuid>7645ade5-9dca-40a7-b0f8-14235327126c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancellation Policy'])[10]/preceding::button[1]</value>
      <webElementGuid>de987b52-a502-4631-b76d-091e99135921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[6]/button</value>
      <webElementGuid>d911855f-e11d-4d1e-a45b-e385885d0356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Select Seat' or . = 'Select Seat')]</value>
      <webElementGuid>b9a82e26-9484-4d10-9cc3-075140b7bacc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
