<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Upper Deck_ico-sprite ico-default_1</name>
   <tag></tag>
   <elementGuidId>37d749ab-bc19-4a06-b51a-673aa0a3ac9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-lower']/div/div/div[2]/ul[5]/li[6]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cbd4587b-0ff2-42ca-a0a5-033bf179c261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-sprite ico-default</value>
      <webElementGuid>13b28662-a72e-483d-bbc7-7d408ac12693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-lower&quot;)/div[@class=&quot;v-card v-card--flat v-sheet theme--light&quot;]/div[@class=&quot;v-card__text&quot;]/div[@class=&quot;seat-body&quot;]/ul[@class=&quot;seat-map&quot;]/li[@class=&quot;sleeper Sleeper&quot;]/i[@class=&quot;ico-sprite ico-default&quot;]</value>
      <webElementGuid>a0ee544e-75f9-43cb-9504-e62166cd27c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-lower']/div/div/div[2]/ul[5]/li[6]/i</value>
      <webElementGuid>095795e2-9b8c-4a78-8247-4139a5803771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[5]/li[6]/i</value>
      <webElementGuid>95b73092-1879-462b-a336-0228b27a8e1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
