<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Dropping Points Sangareddy  (_d8e2c5</name>
   <tag></tag>
   <elementGuidId>a006e8f3-b8c3-40de-9fff-87cc7b114eb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='city']/div/div/div[2]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7a5fc51e-b037-4ee5-91e7-cc3ece1cadb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Dropping Points Sangareddy  (Sangareddy)- 03:30 AMPatancheru  (Patancheru)- 03:45 AMRamachandra Puram  (R C Puram)- 04:00 AMMiyapur  (Allwyn)- 04:10 AMMiyapur  (Miyapur)- 04:20 AM</value>
      <webElementGuid>555fa7c4-46e8-4bd6-996b-5c1fb513151f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)/div[@class=&quot;travel-detail v-card v-card--flat v-sheet theme--light&quot;]/div[@class=&quot;v-card__text&quot;]/div[@class=&quot;select-group&quot;]/div[@class=&quot;drop-down&quot;]/select[1]</value>
      <webElementGuid>357fa93b-a64f-4112-ae33-dd9a217f92b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='city']/div/div/div[2]/div/select</value>
      <webElementGuid>db725258-a0d7-4f03-bee9-f60474ad3e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Dropping Point'])[1]/following::select[1]</value>
      <webElementGuid>1ca6316e-99b8-4cae-a779-458fe3caf348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Boarding Point'])[1]/following::select[2]</value>
      <webElementGuid>d1513688-4064-4948-81d6-cbdadcf09254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>b95f564b-feb9-4a7f-b511-e0d31774d616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Select Dropping Points Sangareddy  (Sangareddy)- 03:30 AMPatancheru  (Patancheru)- 03:45 AMRamachandra Puram  (R C Puram)- 04:00 AMMiyapur  (Allwyn)- 04:10 AMMiyapur  (Miyapur)- 04:20 AM' or . = 'Select Dropping Points Sangareddy  (Sangareddy)- 03:30 AMPatancheru  (Patancheru)- 03:45 AMRamachandra Puram  (R C Puram)- 04:00 AMMiyapur  (Allwyn)- 04:10 AMMiyapur  (Miyapur)- 04:20 AM')]</value>
      <webElementGuid>f3fe7074-f0eb-443e-b527-5db0fc68a858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
