<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Hi_paymentDesktopLogo</name>
   <tag></tag>
   <elementGuidId>a1644af3-8f06-4fbb-ad6b-db51fab2c5ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paymentDesktopLogo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='paymentDesktopLogo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c98a0ea5-07bc-47ec-b3ca-16b8cc0af2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentDesktopLogo</value>
      <webElementGuid>226a5670-9f56-40bd-98e8-065937902a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-newHeaderLogo </value>
      <webElementGuid>49946c93-5370-41fc-a511-e98cccce5e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentDesktopLogo&quot;)</value>
      <webElementGuid>950c89d2-710a-41a1-863e-98fd98a30d97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='paymentDesktopLogo']</value>
      <webElementGuid>778828db-9e76-443e-a8b7-1b221139342a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frescoHeader']/div/div/div/a/i</value>
      <webElementGuid>ddb51d7f-4149-40f6-bee0-0e359640f77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>85921b33-48fc-42c6-9090-611223450686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'paymentDesktopLogo']</value>
      <webElementGuid>b8537c2e-7edf-4a1a-9d90-67c5f8f02a02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
