<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Details_additionalContactEmail</name>
   <tag></tag>
   <elementGuidId>4008fc3c-bbf1-4e03-8481-cedc5a80fc47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#additionalContactEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='additionalContactEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f792044-d13c-4573-95fa-95a3eba81c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3bc0715-bf36-42c9-9ceb-41fef28633cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>additionalContactEmail</value>
      <webElementGuid>9612b1b9-5cab-4cbd-a877-1ed125b58c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>additionalContactEmail</value>
      <webElementGuid>e1c843f4-6fc4-421d-b01d-8c09012c4bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>additionalContact.email</value>
      <webElementGuid>84f922ee-3df0-40d8-8d34-c0f267742844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>cadbe69c-0623-4ef4-8dba-b1cc95af02a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/</value>
      <webElementGuid>833c4fe3-954c-4919-ba57-7ad9804edb0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isloggedIn &amp;&amp; additionalContact.email !=''</value>
      <webElementGuid>e54a8ecc-88be-491b-b8fa-d6c6d41051f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-pattern</value>
      <webElementGuid>10b1dc0b-0783-4b93-ae62-628c98099ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>travellerForm.additionalContactEmail.$valid ? checkForPlatinumUserAjax(additionalContact.email):null</value>
      <webElementGuid>fdd0d7e4-8153-4136-8158-2761f4f3f58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;additionalContactEmail&quot;)</value>
      <webElementGuid>576c81a9-01bd-49d0-bd0a-20581e5a883b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='additionalContactEmail']</value>
      <webElementGuid>b8d26e21-cd60-4e93-abca-064591479752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='traveller-dom']/form/div/div/div/article/div[2]/input</value>
      <webElementGuid>98c03d89-1b5c-43d3-8e30-75386a9d3ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2f4c818c-0849-4c2b-900c-dcdd2ce6e6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'additionalContactEmail' and @id = 'additionalContactEmail' and @placeholder = 'Email']</value>
      <webElementGuid>c975c757-6b78-4ddc-b99c-4732fd20f351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
