<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Room 1_fname0</name>
   <tag></tag>
   <elementGuidId>391feef6-7be9-44a0-a5e6-a074848d1f73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#travellerf0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='travellerf0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7a42c1f-f2fd-423b-bfbe-eb14c43f1542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>67ce2eac-637a-4580-bb21-23e6fbb16992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fname0</value>
      <webElementGuid>9b79b788-2685-4ce9-9433-14634d7c2da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>traveller.travellerDetails.firstName.disabled</value>
      <webElementGuid>48a8af43-268f-403f-91ac-adf32525a32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>traveller.travellerDetails.firstName.value</value>
      <webElementGuid>975cf9c9-4112-4394-b55a-4ea714cff04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^[A-Za-z\s]+$/</value>
      <webElementGuid>72282d79-87f1-45de-80ec-c3a8b4f8c284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name and Middle Name</value>
      <webElementGuid>429ef5ab-aac0-4f4f-b6ab-0a707e748a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>traveller.travellerDetails.firstName.isMandatory</value>
      <webElementGuid>9721e09a-4f0b-4942-af7e-24c1405caf5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-autocomplete</name>
      <type>Main</type>
      <value>onAutoNameSelect</value>
      <webElementGuid>36028652-f484-485a-bd7c-b66ab2853529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>autoSearch(); triggerAutoComplete('travellerf'+travellerIndex, travellerIndex);</value>
      <webElementGuid>540c235f-aa42-4e8b-8db6-3a67fed9e2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>auto-len</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>60e8e5ac-4913-4172-a379-d31208fe7f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>auto-obj</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>374f968f-f880-4c18-961f-e5bcbc9f7bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isclick</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ebc04115-275f-49a6-8be7-bb7f849910d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>travellerf0</value>
      <webElementGuid>924e6bb6-61d4-489d-b6d4-fb9f5641e47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>auto-title</name>
      <type>Main</type>
      <value>[&quot;Mr&quot;,&quot;Mrs&quot;,&quot;Ms&quot;]</value>
      <webElementGuid>99ae0ffa-28be-40b7-bd78-179ffaa77166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-scope ng-empty ng-invalid ng-invalid-required ng-valid-pattern</value>
      <webElementGuid>d64ab4cd-00da-46fc-8259-52a76549f90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ef3d8db0-a74b-4ad6-b791-4eae419d19bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;travellerf0&quot;)</value>
      <webElementGuid>61e8cff7-8042-488e-ba75-82c7b464a81b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='travellerf0']</value>
      <webElementGuid>d8bf1499-9a65-4c76-802c-3f7dc36aacba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='paxNum0']/div[2]/div[2]/div/input</value>
      <webElementGuid>e12af599-af1a-44f8-b745-5456f6a0c467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>fe044ccb-ce86-46ba-ae92-66d2e9e9c33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fname0' and @placeholder = 'First Name and Middle Name' and @id = 'travellerf0']</value>
      <webElementGuid>8b24d103-5be5-475e-9c43-9c00cbd72b6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
