<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Provide valid email address_additiona_ae992a</name>
   <tag></tag>
   <elementGuidId>a62660de-be94-450b-aa9d-ffa12990e69f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#additionalContactMobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='additionalContactMobile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18075cbc-6364-479b-9f4a-7819dc7cc79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e9b7723-dfd1-4051-b171-436839a64d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>additionalContactMobile</value>
      <webElementGuid>45d4a298-298a-4eca-9d77-792ae4a54d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>additionalContactMobile</value>
      <webElementGuid>6a2502b4-4499-4404-a015-5403470eb20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^[0-9]*$/</value>
      <webElementGuid>b296070f-bfe5-4cb7-9d63-df6cd8625f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>additionalContact.mobile</value>
      <webElementGuid>a95e7cf8-7ad8-4536-ba3e-8718555a1f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile Number</value>
      <webElementGuid>2ad5af3f-d532-4550-b05f-452216df3903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-minlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>30cea1be-d0e0-436a-9365-b04d6f238c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>157bfd43-e924-491b-a63b-a4331febc77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>8831b6fa-506d-4e58-b083-1e88a9749c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keypress</name>
      <type>Main</type>
      <value>onlyNumbers($event)</value>
      <webElementGuid>3f844274-5066-4ea7-8ec2-6342168df2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>validateMobile = false</value>
      <webElementGuid>8ba9873e-0ab0-4aba-8e83-5737e054cb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>validateMobile=true</value>
      <webElementGuid>2459551f-a961-4540-baa7-9bf4ece6f9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isloggedIn  &amp;&amp; additionalContact.mobileReadonly</value>
      <webElementGuid>8fcf123a-a2b4-444d-9c1a-21e025ec8ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-pattern ng-valid-minlength ng-valid-maxlength</value>
      <webElementGuid>fc916f4e-d9f6-4398-8a0f-34e8200bd3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;additionalContactMobile&quot;)</value>
      <webElementGuid>8baf2331-03a2-4d53-a23e-267536603d58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='additionalContactMobile']</value>
      <webElementGuid>9292cb85-8938-4836-bdfe-b7b8ae405a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='traveller-dom']/form/div/div/div/article/div[3]/input</value>
      <webElementGuid>158695be-6aa3-4539-a0b4-1f3fc67fad1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div[3]/input</value>
      <webElementGuid>c9616506-d91e-4d95-bb93-d3e317ac2dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'additionalContactMobile' and @name = 'additionalContactMobile' and @placeholder = 'Mobile Number']</value>
      <webElementGuid>ec52b0cd-2afa-403b-a19d-c4b71e29968d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
