<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Provide valid  middle name_lname0</name>
   <tag></tag>
   <elementGuidId>9bc070eb-0671-4afe-a5d4-35741f2babd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#travellerl0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='travellerl0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c943b797-b428-4a06-9851-851be29d5b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef8be8a3-4700-4a1f-a423-162028441762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lname0</value>
      <webElementGuid>ba0423e9-f8da-48d9-af0c-cb2621e8f59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>travellerl0</value>
      <webElementGuid>1bab00bf-95ec-460f-b6a9-a50cd1ba7819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>closeAutoComplete(travellerIndex)</value>
      <webElementGuid>b695ce5a-968e-4ab9-b758-912ad0a69280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>traveller.travellerDetails.lastName.value</value>
      <webElementGuid>2bc49d33-d9be-4065-98d6-df3c496cb413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^[A-Za-z\s]+$/</value>
      <webElementGuid>91a45891-7c54-4057-870f-6242fddb4b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>7222a60a-7520-46b0-baba-4b75a93bd5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>traveller.travellerDetails.lastName.isMandatory</value>
      <webElementGuid>4e08da80-f640-4556-8828-4640e1942361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keyup</name>
      <type>Main</type>
      <value>copyTravellerName(travellerIndex, 'lastName')</value>
      <webElementGuid>741e1bec-c981-47bd-b178-7357b08b9631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-pattern</value>
      <webElementGuid>7f35864e-24df-42c3-a87a-f0dbcf53924d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ca7becf7-5339-4384-94f8-05bee64469d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;travellerl0&quot;)</value>
      <webElementGuid>b67dedb9-2027-437e-88f0-4c9f5d32c293</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='travellerl0']</value>
      <webElementGuid>4ccc0de5-f938-4774-af79-3aa1e72b1227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='paxNum0']/div[4]/input</value>
      <webElementGuid>0538b5a6-5594-4112-be2f-2c782520d883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>afea527f-2a64-4fa6-ac76-a99e0d4dc3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'lname0' and @id = 'travellerl0' and @placeholder = 'Last Name']</value>
      <webElementGuid>1f7e9c29-fde0-4e84-9fd7-e776a38669d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
