<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Title                        Mr.Mrs.Ms</name>
   <tag></tag>
   <elementGuidId>25d31b69-0479-4695-ba9c-f4d0ea5a7e1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;title0&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='title0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e9b6d4e9-d9c8-4674-a640-a39d5b28c788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>traveller.travellerDetails.title.value</value>
      <webElementGuid>ebad164c-1af8-4f14-9bf2-2d10cae85d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>title0</value>
      <webElementGuid>a32664ef-b870-498b-aedc-d22cd6c683fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>traveller.travellerDetails.title.isMandatory</value>
      <webElementGuid>ca229159-5e75-453a-9cee-6def5eccd220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>copyTravellerName(travellerIndex)</value>
      <webElementGuid>daa1385b-ec91-4e8c-a252-85bc1205830d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>traveller.travellerDetails.title.isReadonly</value>
      <webElementGuid>82304aa4-16db-417a-8131-76d7ca1effce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>fbd62759-bed3-47b2-9357-a81e653deda3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>6d9725bc-bf57-4b24-9e31-f0cdb5d34659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Title
                        Mr.Mrs.Ms.
                    </value>
      <webElementGuid>5220e08e-86b5-47c1-ad01-b26c2560c7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paxNum0&quot;)/div[@class=&quot;col-md-5 col-md-offset-0 joint&quot;]/div[@class=&quot;sel-joined&quot;]/span[@class=&quot;ui-select&quot;]/select[@class=&quot;ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>863a61f2-1fff-4743-981a-ce852f4284ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='title0']</value>
      <webElementGuid>2d0d2b90-17de-4a88-81ea-59fadf1ef814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='paxNum0']/div[2]/div/span/select</value>
      <webElementGuid>e65b4a9a-4d27-4cb5-89d1-7541aa0b9c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room 1'])[1]/following::select[1]</value>
      <webElementGuid>c4472945-974c-4a7e-9002-44d234871da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provide valid mobile number.'])[1]/following::select[1]</value>
      <webElementGuid>03caa210-14e9-4b2b-8a7e-b411264fc2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required.'])[1]/preceding::select[1]</value>
      <webElementGuid>cdc2faab-17c4-47ef-8499-046eb5f83d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name is required.'])[1]/preceding::select[1]</value>
      <webElementGuid>9ad3777c-2374-46a5-ac0e-732ef8a99dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/select</value>
      <webElementGuid>b6a43bb5-53d6-4d14-add6-f86e149fd74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'title0' and (text() = '
                        Title
                        Mr.Mrs.Ms.
                    ' or . = '
                        Title
                        Mr.Mrs.Ms.
                    ')]</value>
      <webElementGuid>68660e2e-c790-43e9-9d82-8f65cc7d37bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
