<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Query (Optional)_recaptcha_response_field</name>
   <tag></tag>
   <elementGuidId>978cfe1d-52c7-4db6-86d8-4b76dda63422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recaptcha_response_field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recaptcha_response_field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56e7ea99-1f4c-4aff-9815-a21544c4c790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>930feac3-8557-4b25-a2be-8290fd0ef609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recaptcha_response_field</value>
      <webElementGuid>d42d051e-e635-4a78-8d7e-c7ec69748400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required_field texType w-captcha flR formInput-faq</value>
      <webElementGuid>e5087a3f-d19a-4d76-ac74-ded2cd012bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>recaptcha_response_field</value>
      <webElementGuid>8967deec-f1c7-472c-a7a8-83f808f911b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter the captcha</value>
      <webElementGuid>2b40e4dd-67c7-4fc4-9c70-f305d386cab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-errormsg</name>
      <type>Main</type>
      <value>Please enter captcha</value>
      <webElementGuid>4495f8d1-2f23-458f-81f4-7362e609be85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-captcha</name>
      <type>Main</type>
      <value>{challenge_field:config.recaptcha_challenge_field, url:config.captchaurl, captchamsg:config.captchaValidateMsg}</value>
      <webElementGuid>a43122f1-a5ea-4a5b-b182-8674ecaa7c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4114049d-631a-458b-92f1-50add3310c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha_response_field&quot;)</value>
      <webElementGuid>4a348c8e-4b04-492e-8ca0-852c8b6d14f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recaptcha_response_field']</value>
      <webElementGuid>a7b61d75-12f8-4268-a897-34915d65d25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recaptcha_widget']/div[2]/input</value>
      <webElementGuid>2a8268cc-aa50-4ebf-85a1-4e6804371d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2061f9d7-ff82-4c73-8ea9-ed35b69a0b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'recaptcha_response_field' and @name = 'recaptcha_response_field' and @placeholder = 'Enter the captcha' and @type = 'text']</value>
      <webElementGuid>cccc011d-a160-435b-a001-3f4a27b4ecad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
