<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Query (Optional)_yt-btn yt-btn-orange_aa043b</name>
   <tag></tag>
   <elementGuidId>cd3d071a-b9d0-46ef-b0c6-6cf7cb238937</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.yt-btn.yt-btn-orange.formInput-faq.formbtn-faq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d138c33-28bc-4970-8d07-9d63ad941291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>350348d1-71f8-4d83-af0b-094d0f295741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>5c7aaa33-b8dd-4dca-a1a9-646072659615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yt-btn yt-btn-orange formInput-faq formbtn-faq</value>
      <webElementGuid>03331c81-60a4-4c14-8a05-b2fc30e519ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rescheduleRequest&quot;)/ul[1]/li[6]/input[@class=&quot;yt-btn yt-btn-orange formInput-faq formbtn-faq&quot;]</value>
      <webElementGuid>6723e990-5719-469f-8f5c-51e0e087d3ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Submit']</value>
      <webElementGuid>edc94895-b156-409c-bc75-f5026ce23021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='rescheduleRequest']/ul/li[6]/input</value>
      <webElementGuid>10b16927-b241-4bba-b8a8-64cd2271c528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/input</value>
      <webElementGuid>6799821c-d87d-475d-bd51-c72bd95af028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>86e26f2a-65e2-413e-bc32-96134f064306</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
