<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select Seat</name>
   <tag></tag>
   <elementGuidId>70f4f36a-c956-479e-8c41-b914941a2591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>611d8687-0acc-4fbc-ac5d-a0252a62022f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>772f22d0-29da-47a0-b04e-a3c444e5fb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-red mr0 v-btn theme--light</value>
      <webElementGuid>32dfcdc3-fb88-485f-9bcf-53e7a0addba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Seat</value>
      <webElementGuid>8cb9c8a6-9767-4433-9eb6-3a24d1aa4640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;busDesktop&quot;)/div[@class=&quot;bus-srp-list-view&quot;]/div[@class=&quot;srp-body&quot;]/div[@class=&quot;v-card__text srp-touple&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;flex txt-r xs2 hide-md&quot;]/button[@class=&quot;btn-red mr0 v-btn theme--light&quot;]</value>
      <webElementGuid>15645072-a0ab-431a-a0d7-33b600a4f790</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>eadafd74-fcd2-43a0-abd9-b3596f261519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='busDesktop']/div/div[6]/div[4]/div/div[6]/button</value>
      <webElementGuid>8345e666-6bd4-4c27-88a0-9b704e343f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[2]/following::button[1]</value>
      <webElementGuid>7de8dd57-ac7e-4b68-9235-e9c76fe0a356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boarding/Dropping Points'])[2]/following::button[1]</value>
      <webElementGuid>ae50b413-9a4e-4f7a-8f3f-b61eb7505a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancellation Policy'])[2]/preceding::button[1]</value>
      <webElementGuid>48c1dca5-cc94-4c6c-a659-417e70acfb37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[6]/button</value>
      <webElementGuid>22817ebb-1ab6-45dd-8647-8ccfb4e475bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Select Seat' or . = 'Select Seat')]</value>
      <webElementGuid>f120646e-3d42-4717-8998-1a1a1df78df5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
