<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Upper Deck_ico-sprite ico-default_1_2</name>
   <tag></tag>
   <elementGuidId>be77a11a-40ac-424c-9308-c64f26b39a64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-lower']/div/div/div[2]/ul[4]/li[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a03f070a-0064-4479-b3e9-0e96067eb497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-sprite ico-default</value>
      <webElementGuid>0caa66af-75e8-41b8-bd71-468672d0bb66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-lower&quot;)/div[@class=&quot;v-card v-card--flat v-sheet theme--light&quot;]/div[@class=&quot;v-card__text&quot;]/div[@class=&quot;seat-body&quot;]/ul[@class=&quot;seat-map&quot;]/li[@class=&quot;sleeper&quot;]/i[@class=&quot;ico-sprite ico-default&quot;]</value>
      <webElementGuid>cc98b04d-dd01-4dbf-a469-e0b1aeef1a0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-lower']/div/div/div[2]/ul[4]/li[2]/i</value>
      <webElementGuid>fe0c129f-3b90-40ed-b3a3-49ef2bcd41c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[4]/li[2]/i</value>
      <webElementGuid>176ef512-acae-43a7-b23b-5609403f5e7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
