<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Boarding Points  Gujarat trav_e0a7ea</name>
   <tag></tag>
   <elementGuidId>ce1312cd-095d-406b-8601-5151a60c8eea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='city']/div/div/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f7051760-d4d4-4403-9c61-222e21223945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Boarding Points  Gujarat travels,mauli hotel,vasai phata,next to parmar industries,vasai  - 04:50 AM western hotel kashimira 022-28918668  - 05:30 AMBorivali (e) no. 1, tiwari estate, opp. National park 022-28918668  - 05:40 AMAndheri bridge end hunaman road bus stop  - 06:10 AMGujarat travels,shop no. 4,sion bridge end,opp. Highway app.chunabhatti sanjay gandhi nagar sion  - 06:30 AMChembur - opp. Yogi hotel, s.t. Road, 022-28918668  - 06:35 AMVashi -  sector 17,opp. Vashi plaza,opp.amber hotel vashi  - 06:50 AMNerul (w) l.p bus stand  - 06:55 AMCbd(belapur) after fly over  - 07:00 AMKharghar-hiranandani building,near three star hotel  - 07:10 AMMansarovar,kamotte signal  - 07:25 AM</value>
      <webElementGuid>d2b5dbaf-6386-49fb-b64f-908941b2c15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)/div[@class=&quot;travel-detail v-card v-card--flat v-sheet theme--light&quot;]/div[@class=&quot;v-card__text&quot;]/div[@class=&quot;select-group&quot;]/div[@class=&quot;drop-down&quot;]/select[1]</value>
      <webElementGuid>9fccceb0-2546-4a66-b88c-4b2d31921566</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='city']/div/div/div/div/select</value>
      <webElementGuid>1b4a799b-60a1-40b0-8d2b-4e54854008fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Boarding Point'])[1]/following::select[1]</value>
      <webElementGuid>eb70dde6-5bb7-4ee2-abdc-d5393a7b6239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time:'])[1]/following::select[1]</value>
      <webElementGuid>daac988e-e207-4567-be76-363f4843b06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Dropping Point'])[1]/preceding::select[1]</value>
      <webElementGuid>b3b5b455-7ad5-497b-9aa6-874d582e4a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>db81184a-4ff7-4898-b10b-295b0b1ce263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Select Boarding Points  Gujarat travels,mauli hotel,vasai phata,next to parmar industries,vasai  - 04:50 AM western hotel kashimira 022-28918668  - 05:30 AMBorivali (e) no. 1, tiwari estate, opp. National park 022-28918668  - 05:40 AMAndheri bridge end hunaman road bus stop  - 06:10 AMGujarat travels,shop no. 4,sion bridge end,opp. Highway app.chunabhatti sanjay gandhi nagar sion  - 06:30 AMChembur - opp. Yogi hotel, s.t. Road, 022-28918668  - 06:35 AMVashi -  sector 17,opp. Vashi plaza,opp.amber hotel vashi  - 06:50 AMNerul (w) l.p bus stand  - 06:55 AMCbd(belapur) after fly over  - 07:00 AMKharghar-hiranandani building,near three star hotel  - 07:10 AMMansarovar,kamotte signal  - 07:25 AM' or . = 'Select Boarding Points  Gujarat travels,mauli hotel,vasai phata,next to parmar industries,vasai  - 04:50 AM western hotel kashimira 022-28918668  - 05:30 AMBorivali (e) no. 1, tiwari estate, opp. National park 022-28918668  - 05:40 AMAndheri bridge end hunaman road bus stop  - 06:10 AMGujarat travels,shop no. 4,sion bridge end,opp. Highway app.chunabhatti sanjay gandhi nagar sion  - 06:30 AMChembur - opp. Yogi hotel, s.t. Road, 022-28918668  - 06:35 AMVashi -  sector 17,opp. Vashi plaza,opp.amber hotel vashi  - 06:50 AMNerul (w) l.p bus stand  - 06:55 AMCbd(belapur) after fly over  - 07:00 AMKharghar-hiranandani building,near three star hotel  - 07:10 AMMansarovar,kamotte signal  - 07:25 AM')]</value>
      <webElementGuid>fa5e6526-4e5b-4bf0-91e5-f1bf853b9139</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
