<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Hi_paymentDesktopLogo</name>
   <tag></tag>
   <elementGuidId>9d6a25c6-3833-4888-a5bc-0113178f95b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paymentDesktopLogo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='paymentDesktopLogo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>662819ae-23ab-4922-90da-8f0f55ed312e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentDesktopLogo</value>
      <webElementGuid>4a7568db-49fb-4c51-856e-a57dbebaefbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-newHeaderLogo </value>
      <webElementGuid>15a3c2ee-837f-428b-9720-80187b8744f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentDesktopLogo&quot;)</value>
      <webElementGuid>07a3797f-f570-49b6-a223-fb9d110fbf0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9db8a974-e749-4730-80c8-acf36ce99679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentDesktopLogo</value>
      <webElementGuid>bba42ca1-d0c5-4922-9756-5c2e9cac2455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-newHeaderLogo </value>
      <webElementGuid>74d8b83b-da75-4e90-8d44-293f882d6d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentDesktopLogo&quot;)</value>
      <webElementGuid>b6b160aa-cdf7-48fe-af3f-8d85dcbe62b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='paymentDesktopLogo']</value>
      <webElementGuid>de1c4809-4574-4d35-b466-9a82c91c1624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frescoHeader']/div/div/div/a/i</value>
      <webElementGuid>60e66010-6879-4c61-b76e-43f358a59805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>42ebf603-ba2b-439b-923d-13a003c18849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'paymentDesktopLogo']</value>
      <webElementGuid>14f68f46-859c-4584-ad92-d87fcbbfe139</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
