<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Please enter Sender, , s Last _aa706e</name>
   <tag></tag>
   <elementGuidId>f91207cf-9405-4e31-bc70-6cbbeebee7bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6986b5b-dd37-4610-b41c-f8fc38ae481e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>4e29bed0-fbba-4225-bea0-eb0e5fe91cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>711eb8e9-4b81-4f9b-9586-50588dd0b517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7f6c49d-24d8-4c4f-8c2b-f3f19c20b3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>customInput border  form-control</value>
      <webElementGuid>df42f3b6-8eb1-41a8-979b-8b946ad9da47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;App__MainDiv-sc-yyfnye-0 jPHkWF container-fluid mainContainer&quot;]/div[@class=&quot;minHeight&quot;]/div[1]/div[2]/div[@class=&quot;productContainer row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;justify-content-center mb-2 row&quot;]/div[@class=&quot;col-12 col-sm-10 col-lg-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;mt-md-0 mt-0 col-12&quot;]/div[@class=&quot;mb-4 row&quot;]/div[@class=&quot;col-12 col-sm-6&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-12&quot;]/div[@class=&quot;has-float-label form-group&quot;]/input[@id=&quot;email&quot;]</value>
      <webElementGuid>fc6e0ff2-dd00-4bfa-80fe-03aacfd7bb47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email']</value>
      <webElementGuid>23f429cf-8eaf-4ea7-9a32-1d44709f2de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div[7]/div/div/div/div[2]/div/div/div/div[2]/div/div[3]/div/input</value>
      <webElementGuid>20706de7-6452-4b8e-9cee-3708e29617fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>d5f7d75d-c935-4be2-800a-b7f8e6bd6958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @id = 'email' and @type = 'text']</value>
      <webElementGuid>3fabff23-ae0e-4e0b-b639-58c39985165d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
