<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Sender, , s First Name)_lastname</name>
   <tag></tag>
   <elementGuidId>47ead6df-ae51-4231-a45f-f9b3791e26c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lastname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lastname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>483884d2-cff3-45a8-8882-947b9a168b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>1fe2a32a-bcf5-4421-8517-7bd9d543f760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>58648bdc-5374-409e-9698-ec28ede84e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>119f8c75-90c3-4f86-84bb-18ee9a91cfcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1cfa2077-8839-4f7e-97d5-d70835b3c9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>customInput border  form-control</value>
      <webElementGuid>806afad9-c7df-4df7-a73b-102a275f6da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>afd9ac73-e4df-4266-abc7-e3b9e491fb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;App__MainDiv-sc-yyfnye-0 jPHkWF container-fluid mainContainer&quot;]/div[@class=&quot;minHeight&quot;]/div[1]/div[2]/div[@class=&quot;productContainer row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;justify-content-center mb-2 row&quot;]/div[@class=&quot;col-12 col-sm-10 col-lg-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;mt-md-0 mt-0 col-12&quot;]/div[@class=&quot;mb-4 row&quot;]/div[@class=&quot;col-12 col-sm-6&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-12&quot;]/div[@class=&quot;has-float-label form-group&quot;]/input[@id=&quot;lastname&quot;]</value>
      <webElementGuid>e69c32ad-26a4-4a1b-a8e6-859f8f1ddf96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lastname']</value>
      <webElementGuid>ff0a7697-710a-4591-bb2a-993d070a81c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div[7]/div/div/div/div[2]/div/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>ec7ec6c3-6bf8-404f-9d75-9bb82fbb1861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>0713dfb7-ce08-493b-bc4e-282c4b61258c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'lastname' and @id = 'lastname' and @type = 'text']</value>
      <webElementGuid>3231f78c-edd9-40ca-8a67-ac486353699e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
