<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yatra Hotels  Holidays Vouchers_denomination</name>
   <tag></tag>
   <elementGuidId>03dd6cde-7f58-488e-83f1-a315cfdcacb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#denomination</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='denomination']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bac77b13-cd0f-40cc-9295-d063ae2ccf86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>denomination</value>
      <webElementGuid>86a22d5e-09e1-4304-8dcf-8ef8eb4bdfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>denomination</value>
      <webElementGuid>8645aaeb-177a-4c60-9817-848138198e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>56ad5f26-f2c4-4deb-8dd1-64eed262e14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5a9fd945-2e44-4f14-81dc-5a84a63aa873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>customInput border  form-control</value>
      <webElementGuid>123f5897-2bdb-42ef-81cd-322ff1580048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;denomination&quot;)</value>
      <webElementGuid>542ab80c-d5d8-446d-bc08-1f63fab50289</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='denomination']</value>
      <webElementGuid>fd402414-cecf-4f17-a4a3-b39ae2c59bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>52590927-db1a-49e3-bf72-6fc8a90bf7db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e05b901f-2b0e-4540-bd2c-c0ddc7150080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'denomination' and @id = 'denomination' and @type = 'number']</value>
      <webElementGuid>1f687079-2447-4301-a31f-da9a0a2c4503</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
