<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Sender, , s Details)_firstname</name>
   <tag></tag>
   <elementGuidId>b866dfaa-38aa-4ed9-b89d-5720ee05a1fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#firstname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f26234f-676f-4c97-8fa9-c27bc95e3203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstname</value>
      <webElementGuid>5c30a339-e48a-4e8d-8aee-84d848a28a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstname</value>
      <webElementGuid>f4b364a2-0a09-4fa5-bcd4-eade5b4f6e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>9eebe750-eacf-41f4-bf22-6f5fab930066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71d3d123-687b-4a04-a4ad-63d6c6dcb339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>customInput border  form-control</value>
      <webElementGuid>2fa7943d-8707-468b-bef4-cb1ac95a83ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;App__MainDiv-sc-yyfnye-0 jPHkWF container-fluid mainContainer&quot;]/div[@class=&quot;minHeight&quot;]/div[1]/div[2]/div[@class=&quot;productContainer row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;justify-content-center mb-2 row&quot;]/div[@class=&quot;col-12 col-sm-10 col-lg-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;mt-md-0 mt-0 col-12&quot;]/div[@class=&quot;mb-4 row&quot;]/div[@class=&quot;col-12 col-sm-6&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-12&quot;]/div[@class=&quot;has-float-label form-group&quot;]/input[@id=&quot;firstname&quot;]</value>
      <webElementGuid>299bb966-9142-4610-b98f-15ed33b8711b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstname']</value>
      <webElementGuid>925a439c-15a4-4b3f-b96d-77cbb0632459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div[7]/div/div/div/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>21d92c3f-f704-4216-84f5-99c1cf916c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>51f0b72b-07ad-4cd8-9386-55aaa144e206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'firstname' and @id = 'firstname' and @type = 'text']</value>
      <webElementGuid>6e4896e6-8c73-4e3a-b083-588900dd4d87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
