<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Mobile Number</name>
   <tag></tag>
   <elementGuidId>527c5ac5-b59f-4688-861f-0a243a719b68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.fontSize.customIntlLabel.placeholder-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div[2]/div/div[7]/div/div/div/div[2]/div/div/div/div[2]/div/div[4]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0cde15a3-aed1-4609-bbb7-b70817075b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>telephone</value>
      <webElementGuid>fdd7172e-206a-4687-bdf3-ea74e318b7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fontSize customIntlLabel placeholder-label</value>
      <webElementGuid>e92a3130-b8f2-4b51-bdd8-cbf4d58d5b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobile Number*</value>
      <webElementGuid>4bf15482-54c8-4dd6-ba16-64d0a6184c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;App__MainDiv-sc-yyfnye-0 jPHkWF container-fluid mainContainer&quot;]/div[@class=&quot;minHeight&quot;]/div[1]/div[2]/div[@class=&quot;productContainer row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;justify-content-center mb-2 row&quot;]/div[@class=&quot;col-12 col-sm-10 col-lg-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;mt-md-0 mt-0 col-12&quot;]/div[@class=&quot;mb-4 row&quot;]/div[@class=&quot;col-12 col-sm-6&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-12&quot;]/div[@class=&quot;has-float-label form-group&quot;]/label[@class=&quot;fontSize customIntlLabel placeholder-label&quot;]</value>
      <webElementGuid>469beb19-c3cc-4a09-801b-fd1a58c6ceb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div[7]/div/div/div/div[2]/div/div/div/div[2]/div/div[4]/div/label</value>
      <webElementGuid>000f4699-2c31-44c4-a24d-ea3fa0bb3f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ 358'])[2]/following::label[1]</value>
      <webElementGuid>9f3a1192-4660-4128-b7eb-2169bce7b86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Åland Islands'])[1]/following::label[1]</value>
      <webElementGuid>88d6704a-938a-4131-8e94-c004e8030160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter Mobile no'])[1]/preceding::label[1]</value>
      <webElementGuid>4e5cfe56-30e9-476e-a146-904e32f2fe21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Receiver', &quot;'&quot;, 's Details')])[1]/preceding::label[1]</value>
      <webElementGuid>cdbcf307-43be-498e-8108-0984e2e9af4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mobile Number*']/parent::*</value>
      <webElementGuid>9c8c1a76-e940-4463-9fd1-ef9729cc1910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label</value>
      <webElementGuid>45a3756d-8c05-4971-8f26-8f84fb124abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Mobile Number*' or . = 'Mobile Number*')]</value>
      <webElementGuid>78cda45c-84c8-4408-af02-c3bde73d9a0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
