<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_How can I use Yatra gift voucher_faq_e0064e</name>
   <tag></tag>
   <elementGuidId>d5482d41-1b7c-4bdc-9158-1d89d2f76faa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#faq1disLike</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='faq1disLike']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6f54f4c-d3c7-4c9b-b641-4b52d1f7b6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feedback-thumbs__button feedback-thumbs__button--dislike</value>
      <webElementGuid>7366f622-3f44-4f10-9bfc-14808433dc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>187e921b-d29c-43ea-aff8-dc9f8758369d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>faq1disLike</value>
      <webElementGuid>37152915-d88a-44b9-8ca2-b49b8bc0222d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Needs improvement</value>
      <webElementGuid>2cd3454a-836f-4363-bce6-f39e32b4efd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>disLike('faq'+$index)</value>
      <webElementGuid>8cd3cbe8-cf53-40b1-9a24-e9ce740af099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;faq1disLike&quot;)</value>
      <webElementGuid>3ab097af-0550-4e00-900c-ce7762a88346</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='faq1disLike']</value>
      <webElementGuid>1423e1bb-4846-4619-8215-56f68c80c0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='answer-footer_1']/div/div/button[2]</value>
      <webElementGuid>04f94b4e-e426-4cc1-9f0e-03ca5ff6260a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How can I use Yatra gift voucher?'])[1]/following::button[2]</value>
      <webElementGuid>8128fdf2-d8bd-44c1-8e18-50d2008bd16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabs - OLA : No offer'])[1]/following::button[4]</value>
      <webElementGuid>1387a7d7-c773-4dbc-90ac-f94a7ef6c466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How do I login to My Bookings section on Yatra.com?'])[1]/preceding::button[1]</value>
      <webElementGuid>78403256-eace-4995-a0b9-f5da321355ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Bookings'])[3]/preceding::button[1]</value>
      <webElementGuid>6100d9c0-8cac-4100-8f26-45b991108c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div/div/button[2]</value>
      <webElementGuid>826cfe90-2dcb-4821-9e8b-6735c43a4373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'faq1disLike' and @title = 'Needs improvement']</value>
      <webElementGuid>e36404cf-886b-411b-a214-70db9dbf5e62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
