<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit_1</name>
   <tag></tag>
   <elementGuidId>a414de5c-1a03-408f-9101-10df83f08de7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.main-btn.mt15</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b6c1e5a1-611b-494f-b1d1-957f4106e89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1868adc0-e79e-4291-a81e-ca84df4fce98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-btn mt15</value>
      <webElementGuid>9aec222d-e1bf-403c-a1a8-ac5761863304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>verifyOtp()</value>
      <webElementGuid>8f8fb19c-ddf2-46b9-b760-d68e53376bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>a18a285a-6168-4361-aa95-2795a31af44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths ng-scope&quot;]/body[@class=&quot;hldy-content-display ng-scope hideOverflow&quot;]/div[@class=&quot;ng-scope&quot;]/section[@class=&quot;mob-popup fadeIn&quot;]/div[1]/section[@class=&quot;otp-section-overlay&quot;]/div[@class=&quot;form-container&quot;]/form[@class=&quot;login-form ng-valid ng-dirty&quot;]/p[4]/button[@class=&quot;main-btn mt15&quot;]</value>
      <webElementGuid>f50d6efe-5ba2-4e4c-ae2f-895e0d9cfaf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>b67feb11-2c65-4187-8376-d7be1c322607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Mobile OTP'])[2]/following::button[1]</value>
      <webElementGuid>49cb305a-6dc7-48e7-a1b8-006c7a6f66d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Mobile OTP'])[1]/following::button[1]</value>
      <webElementGuid>33f0e3e1-a9bc-454c-b5ca-be1bef1f60b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>92839473-e92e-4238-9448-8a2e73663a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/button</value>
      <webElementGuid>45d4c67e-ed0c-4277-b2c4-e9d96d9cf56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>554164f4-b3ba-45f1-acda-9123004976d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
