<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Call 91-9990-614-615_customerName</name>
   <tag></tag>
   <elementGuidId>ed73a364-da16-466b-b9a1-1290effa3477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;customerName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='customerName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10033069-a4ea-488e-bd89-e67bb8abec1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ae2663b-e278-4247-80f4-4cecf1cf96c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerName</value>
      <webElementGuid>de975628-1f98-4b71-a7eb-f05325609f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^[a-zA-Z\s\']+$/</value>
      <webElementGuid>a030d5d9-a3db-44e9-982b-aef7aa9b1ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your Name</value>
      <webElementGuid>54a017c3-e97e-414d-bdf7-ca0e4de74a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>leadFormData.customerName</value>
      <webElementGuid>e59c85b0-2a2e-410f-b107-22c19ad996b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-requirederrormessage</name>
      <type>Main</type>
      <value>Please enter your name</value>
      <webElementGuid>4d6de6b7-7101-4faf-a1bb-37920e771158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-patternerrormessage</name>
      <type>Main</type>
      <value>Please enter a valid name. Only letters with spaces are allowed</value>
      <webElementGuid>cbfbba21-af56-470f-9a7b-20deca0628ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d4accd00-d96a-4572-be94-4eb7777aab40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-invalid ng-invalid-required ng-valid-minlength ng-valid-pattern</value>
      <webElementGuid>f4838654-108f-4248-aa50-3d2a3c165c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths ng-scope&quot;]/body[@class=&quot;hldy-content-display ng-scope hideOverflow&quot;]/div[@class=&quot;ng-scope&quot;]/section[@class=&quot;mob-popup fadeIn&quot;]/div[@class=&quot;sm-popup enq-form&quot;]/div[@class=&quot;step-one clearfix&quot;]/div[@class=&quot;left-column&quot;]/div[1]/form[@class=&quot;form clearfix ng-pristine ng-invalid ng-invalid-required&quot;]/input[@class=&quot;ng-pristine ng-invalid ng-invalid-required ng-valid-minlength ng-valid-pattern&quot;]</value>
      <webElementGuid>f433d223-41f0-4858-93cf-44fd1e9fe5bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='customerName']</value>
      <webElementGuid>11c1b8cf-e714-4857-acdc-a67edc90bc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input[2]</value>
      <webElementGuid>ffb64789-9206-4092-8adb-aae8f7f2b03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customerName' and @placeholder = 'Your Name']</value>
      <webElementGuid>9ff30b85-cf01-41bb-9ad2-337cbd95cffd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
