<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_THANK YOU FOR YOUR QUERY_submitQuery-_f10800</name>
   <tag></tag>
   <elementGuidId>433fb426-a18d-44c0-a025-202f444fc5a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitQuery-otp-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submitQuery-otp-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>574397da-06dc-462a-b05f-47f85394928d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input ng-pristine ng-valid</value>
      <webElementGuid>b5eb2f53-b3e9-4b93-a1c0-951f98cb9976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitQuery-otp-input</value>
      <webElementGuid>582d7ad1-f249-474b-8379-52c0bb15184c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ee8831b-25d2-43cf-9093-8f8f396519c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>validateOtp()</value>
      <webElementGuid>5d568b49-2398-4b45-97c6-9b70219ece5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>243e6243-12a1-4265-bdda-f5e8c0d5f014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>otp</value>
      <webElementGuid>8209aee4-9f96-446c-b50e-97e7537a3c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitQuery-otp-input&quot;)</value>
      <webElementGuid>d26b50b5-96a5-4aa1-8fea-c00bc951bf8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submitQuery-otp-input']</value>
      <webElementGuid>054ed7ab-246a-4694-995e-4ea551b2bd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>660545dd-9dc4-45b8-a46d-4ee018945c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'submitQuery-otp-input' and @type = 'text']</value>
      <webElementGuid>5147c2c5-92f6-487b-b9be-106ab8ee4cd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
