<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Call 91-9990-614-615_mailId</name>
   <tag></tag>
   <elementGuidId>ce9eff22-0c21-4cb9-bc64-375e303cfaa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;mailId&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='mailId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce0231b5-5900-4b35-aeda-13df22d2a550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5b89905-ceab-4402-b827-5cc594982590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mailId</value>
      <webElementGuid>393ba557-8298-4754-bffb-b35cbdbb77f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email ID</value>
      <webElementGuid>d2b483c3-18c5-4bb4-bbd3-ae44c23a8103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,6})+$/</value>
      <webElementGuid>836428ec-2300-4ec2-95ec-7ee27c06256f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>leadFormData.customerEmailId</value>
      <webElementGuid>1de7f1d2-2354-404c-9fa7-24887e62c6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-requirederrormessage</name>
      <type>Main</type>
      <value>Please enter your email ID</value>
      <webElementGuid>16cdef33-3b10-45ba-9f20-c3bd323d9ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-patternerrormessage</name>
      <type>Main</type>
      <value>Please enter a valid email id</value>
      <webElementGuid>01d26823-0921-40b9-b8e9-496e5271fdc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-invalid ng-invalid-required ng-valid-pattern</value>
      <webElementGuid>88f6b217-d960-4513-90ce-0ba278a81ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths ng-scope&quot;]/body[@class=&quot;hldy-content-display ng-scope hideOverflow&quot;]/div[@class=&quot;ng-scope&quot;]/section[@class=&quot;mob-popup fadeIn&quot;]/div[@class=&quot;sm-popup enq-form&quot;]/div[@class=&quot;step-one clearfix&quot;]/div[@class=&quot;left-column&quot;]/div[1]/form[@class=&quot;form clearfix ng-invalid ng-invalid-required ng-dirty ng-valid-minlength&quot;]/input[@class=&quot;ng-pristine ng-invalid ng-invalid-required ng-valid-pattern&quot;]</value>
      <webElementGuid>c8535407-dc66-4849-ab01-5f0c460444de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='mailId']</value>
      <webElementGuid>4de9c042-0aa1-4125-904d-bc760fc9bf8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>261f3b5d-e3d5-40ab-97eb-76bf096ee7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'mailId' and @placeholder = 'Email ID']</value>
      <webElementGuid>6dea3906-cc09-4840-83bf-c4a49a94663e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
