<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Quick View</name>
   <tag></tag>
   <elementGuidId>a4737cb1-6636-4eba-a95a-b461beea8984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.quick-view.bdr3.hidden-sm.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='imgWrapper_00062751']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>93e555de-c088-49fd-a4e9-ed096b168ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>utilities.hasQuickView</value>
      <webElementGuid>f24fbb5f-8c78-4e19-b79c-3b8a8604a0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>491ee86d-b85c-4399-b3ea-86ec5b2904bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quick-view bdr3 hidden-sm ng-scope</value>
      <webElementGuid>111f346a-9329-4651-9b77-58319d675e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to Quick View</value>
      <webElementGuid>c9371324-9a4d-42b7-b920-1a7a20c21ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-live-data</name>
      <type>Main</type>
      <value>quick_view**quick_view</value>
      <webElementGuid>d2839aee-cfce-4798-8d2e-0c6ca23e770a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>getQuickViewUrl(hotel, $index, 'Quick View')</value>
      <webElementGuid>24214074-1a33-43f1-b47c-012926d6bf95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quick View</value>
      <webElementGuid>8c19dbff-02b7-4a94-8da3-b669b1be5d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgWrapper_00062751&quot;)/div[@class=&quot;full img-wrapper&quot;]/a[@class=&quot;quick-view bdr3 hidden-sm ng-scope&quot;]</value>
      <webElementGuid>ba0fb61d-178d-4f78-8dac-c3a29e0d3442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='imgWrapper_00062751']/div/a</value>
      <webElementGuid>0924fd52-95d2-4c39-b724-074e17bde75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Quick View')]</value>
      <webElementGuid>e978ff7c-d702-44c3-a39b-92113f7f4e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(taxes extra)'])[1]/following::a[1]</value>
      <webElementGuid>c9093f7a-b941-4fdc-9158-548731c00c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shivganga Cottage'])[1]/preceding::a[1]</value>
      <webElementGuid>8b6441fd-2300-4be2-91c4-f24f66246846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quick View']/parent::*</value>
      <webElementGuid>2dc85006-7327-489c-a8a6-7180a6195e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[16]</value>
      <webElementGuid>76ad4207-425e-4888-8dc0-e218797439df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/a</value>
      <webElementGuid>14b76588-0964-40cb-a8e2-45cd35724947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @title = 'Click to Quick View' and (text() = 'Quick View' or . = 'Quick View')]</value>
      <webElementGuid>9bbf5457-9797-4c49-b5b3-5fae89d84a89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
