<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Book Now</name>
   <tag></tag>
   <elementGuidId>432e72a7-fb3b-482a-a643-149f2354a979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='roomWrapper0001881953']/div[2]/div[5]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6a9d19a3-ddc0-4166-8fe9-2115c4006c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!isAppFor.destranet &amp;&amp; room.bookable</value>
      <webElementGuid>5cf2fe9a-fb51-48ef-8b1f-cfaef39198a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>new-blue-button newBtn  choose-room-button </value>
      <webElementGuid>63d56c3b-a235-453c-8e71-c3d862f1e251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>checkInstantBook(room)</value>
      <webElementGuid>e25ce8ad-08cf-41e0-842d-6195e5c61bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'mb15':isAppFor.byop}</value>
      <webElementGuid>bd8392b7-1871-4ddb-959b-387015361daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book Now
                                    
                                    </value>
      <webElementGuid>56c09a28-ad24-42ca-974b-fc2ae75fca41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;roomWrapper0001881953&quot;)/div[@class=&quot;cr-rightWrp&quot;]/div[@class=&quot;cr-submit&quot;]/button[@class=&quot;new-blue-button newBtn  choose-room-button&quot;]</value>
      <webElementGuid>f0c4a863-a8fa-4246-aa8d-704c41a8f7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d54bf875-f9d0-4f1c-9612-1dcf0de22bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!isAppFor.destranet &amp;&amp; room.bookable</value>
      <webElementGuid>fe5553db-ef09-4a06-998e-0be5805801dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>new-blue-button newBtn  choose-room-button </value>
      <webElementGuid>66aecfbd-24aa-406d-b806-cf386d491d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>checkInstantBook(room)</value>
      <webElementGuid>7ff1168e-452b-4b09-beed-9cb5926033f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'mb15':isAppFor.byop}</value>
      <webElementGuid>3d352784-a2e0-436a-95ec-d4544b17c280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book Now
                                    
                                    </value>
      <webElementGuid>53e6f032-f582-4db6-a3bd-eddf0a48492e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;roomWrapper0001882231&quot;)/div[@class=&quot;cr-rightWrp&quot;]/div[@class=&quot;cr-submit&quot;]/button[@class=&quot;new-blue-button newBtn  choose-room-button&quot;]</value>
      <webElementGuid>7a86cc9c-4d3e-4231-a650-3adbcce7b36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>190ecc17-967d-4d6c-8f50-980301bb4353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!isAppFor.destranet &amp;&amp; room.bookable</value>
      <webElementGuid>b2352c98-270c-45e8-b2f6-4a1d6c65911e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>new-blue-button newBtn  choose-room-button </value>
      <webElementGuid>be53cf42-44ad-4451-b09e-0ea072ac5666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>checkInstantBook(room)</value>
      <webElementGuid>58207db5-3aaa-459a-937b-c8bb1bd75b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'mb15':isAppFor.byop}</value>
      <webElementGuid>d69c1be0-b99d-421c-acff-3c25156dd75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book Now
                                    
                                    </value>
      <webElementGuid>02f8cd4e-d516-4704-a461-2570f5ce601a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;roomWrapper0000537133&quot;)/div[@class=&quot;cr-rightWrp&quot;]/div[@class=&quot;cr-submit&quot;]/button[@class=&quot;new-blue-button newBtn  choose-room-button&quot;]</value>
      <webElementGuid>400d60d2-3395-45c6-bf37-d829174af06d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='roomWrapper0001881953']/div[2]/div[5]/button</value>
      <webElementGuid>62964cac-7b2c-4dd1-8192-9eae34710153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.'])[16]/following::button[1]</value>
      <webElementGuid>0d4ce167-e591-44ec-90bc-9faa9cf1cff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Amount'])[3]/following::button[1]</value>
      <webElementGuid>558bc261-3121-4281-b1da-204a79e60368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.'])[17]/preceding::button[1]</value>
      <webElementGuid>4f357363-681e-45e0-8208-4d0e4a847004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/preceding::button[1]</value>
      <webElementGuid>ebbd819e-d2b0-4d76-b73b-cc594be74022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Book Now']/parent::*</value>
      <webElementGuid>d23275a0-b21d-4189-bc2e-8e37525a95ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>db747c4c-4600-47b5-8049-ac52d8f7fff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Book Now
                                    
                                    ' or . = 'Book Now
                                    
                                    ')]</value>
      <webElementGuid>61cecf7a-8cf3-4f70-b246-6e5d9b36a35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='roomWrapper0001882231']/div[2]/div[5]/button</value>
      <webElementGuid>6ed4b7ad-0452-4987-80bc-cb2d4f837e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.'])[19]/following::button[1]</value>
      <webElementGuid>1f0f7a29-be54-463d-a89a-8ec073f064b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.'])[20]/preceding::button[1]</value>
      <webElementGuid>750e8506-1df2-4e1d-a210-0cc77d71d95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='roomWrapper0000537133']/div[2]/div[5]/button</value>
      <webElementGuid>c70d2fb8-4a14-4616-a24f-db0e02e35b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.'])[62]/following::button[1]</value>
      <webElementGuid>e54afd9f-f329-4eb3-821f-6cdf40dc519a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.'])[63]/preceding::button[1]</value>
      <webElementGuid>1aa4fdae-6943-482b-adc2-0df2c7154e80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
