<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Logout_ico-newHeaderLogo</name>
   <tag></tag>
   <elementGuidId>33c6ab9a-7db1-4ed6-a72d-e44849cb6c85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.logo > i.ico-newHeaderLogo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerSnipe']/div/div/div[3]/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>39ca142a-62c7-4d54-b2ac-6a10e351de05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-newHeaderLogo</value>
      <webElementGuid>309752a1-960b-4d33-8d9b-829b071ef725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerSnipe&quot;)/div[@class=&quot;yatra-header service-header&quot;]/div[1]/div[@class=&quot;header-container desktop-only&quot;]/div[@class=&quot;header-left-menu ftL&quot;]/a[@class=&quot;logo&quot;]/i[@class=&quot;ico-newHeaderLogo&quot;]</value>
      <webElementGuid>641af318-d027-4301-b377-6cdefdf39254</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerSnipe']/div/div/div[3]/div/a/i</value>
      <webElementGuid>87c3acab-9a80-4c4c-ae36-0a770e0b044c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
      <webElementGuid>b33d90e2-e031-4a6d-aa5f-00a9b773ee29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
