<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Homestay_checkin</name>
   <tag></tag>
   <elementGuidId>f0eed6c8-7ecb-4788-8d74-af5d0551f2f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkInDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkInDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>406321d6-54ef-4fbc-9979-d06cb58dbf61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa16478c-ee5d-4f67-9e38-11100fe85420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input checkInDate ng-pristine ng-untouched ng-valid ng-valid-required</value>
      <webElementGuid>0a5a4eaf-83d9-4c8c-b83e-26d7c5c8fd33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkInDate</value>
      <webElementGuid>d3adddcb-f484-4694-8a4a-078718f76362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkin</value>
      <webElementGuid>c647775b-8f9f-4376-9f39-14a9d49227e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cal-pos</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>ebf2b27c-6b97-4d42-97bc-39f4aa1eb836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-next</name>
      <type>Main</type>
      <value>checkOutDate</value>
      <webElementGuid>5d0e55e2-b7cf-4d9a-8454-e41589cab669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dtid</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>55bbbdc9-f8da-41f0-9024-00ee316a668b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>modifyParams.checkinDate</value>
      <webElementGuid>9b630f88-1a07-4927-9d57-0106f018f608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Check-in</value>
      <webElementGuid>abae43c8-18ca-463c-9a6d-d3d7d3ee577b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>updateCheckAvail()</value>
      <webElementGuid>23510ed5-124a-435f-afa4-57b20115f8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resettime</name>
      <type>Main</type>
      <value>resetTime</value>
      <webElementGuid>c19ff105-6afc-45e5-b5fd-130e12509fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkInDate&quot;)</value>
      <webElementGuid>fbf10888-4935-4576-9334-01a4cdb8c4da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkInDate']</value>
      <webElementGuid>ecfbda4b-bfe2-4e0f-b81d-95058c4245f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MSF']/div/div[2]/ul/li[2]/div/div/input</value>
      <webElementGuid>ee0a5e8e-4af2-4365-b98f-757f0f1069ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/input</value>
      <webElementGuid>4110511c-a316-4ef9-bf6c-23454e8d666b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'checkInDate' and @name = 'checkin' and @placeholder = 'Check-in']</value>
      <webElementGuid>4dd7ad9f-e991-40f9-a9f5-baf281d788ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
