<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Homestay_new-blue-button</name>
   <tag></tag>
   <elementGuidId>8a607765-a5d7-485d-95a7-d5fe9135bb98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.new-blue-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Search Again']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d0eebe2-d838-4477-9f5a-2fd280411063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>637ee08f-50cb-40cb-b5af-1011ad7f20b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>new-blue-button</value>
      <webElementGuid>d259fea4-a4dd-45d9-82ef-f8d181fc7f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Again</value>
      <webElementGuid>3b9f4571-ee89-4f68-acac-f5ce761275a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>getResults(MSF);</value>
      <webElementGuid>90d3689e-ef82-4428-b43c-f9108e50bef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MSF&quot;)/div[@class=&quot;overlay-inner&quot;]/div[@class=&quot;full mt-20&quot;]/input[@class=&quot;new-blue-button&quot;]</value>
      <webElementGuid>30827d02-e6aa-4da5-b72b-77ae52c3f827</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Search Again']</value>
      <webElementGuid>e43ced2f-7c36-4e6f-aa6b-9f588632ca2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MSF']/div/div[3]/input</value>
      <webElementGuid>9444a2a2-e805-4a03-9227-6524a9c8f997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>74221038-1cfd-4696-beaf-ee5025fd9bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>44f7879f-61bb-4e70-ad1a-cc406aa1718c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
