<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Choose Room_1</name>
   <tag></tag>
   <elementGuidId>9bf71a75-cbb1-4958-a9c6-4e5e5174b938</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choose-room-disable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='choose-room-disable']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a823c3ba-4e7c-45a1-8268-5e54f8107341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choose-room-disable</value>
      <webElementGuid>76f0a833-0e43-4b35-80f0-e225e7c4aacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fr btn new-blue-button</value>
      <webElementGuid>9f174f71-76c5-4ae9-9389-d4db9c9f94a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>scrollSection('view-room')</value>
      <webElementGuid>21bbe2d4-7176-4de6-b5af-ab47b6b6978f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-ga</name>
      <type>Main</type>
      <value>Select Room|Hotel:Gautham Villa Home Stay:Room:Standard Room.:Price:15998</value>
      <webElementGuid>bc9bc074-a226-4292-a03d-6f354d8bee78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose Room</value>
      <webElementGuid>65dd842b-8c2d-4771-aa5a-49c6050e5a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choose-room-disable&quot;)</value>
      <webElementGuid>5e378b3d-f579-4676-9549-3c622553a820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>381ff084-51f1-438c-98fd-b1fedda4dc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choose-room-disable</value>
      <webElementGuid>92ffbef4-2e9a-4165-8a36-3e85562a42c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fr btn new-blue-button</value>
      <webElementGuid>c3849ee8-8ed4-4900-b54d-4169ac5129cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>scrollSection('view-room')</value>
      <webElementGuid>db6b346d-cb3b-427b-8893-e96041cec031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-ga</name>
      <type>Main</type>
      <value>Select Room|Hotel:Berrylane Homestay:Room:Standard Room.:Price:62199.8</value>
      <webElementGuid>4c05b083-13b7-4e9d-9c87-aaec6500d509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose Room</value>
      <webElementGuid>59f96d42-98e6-4c67-a784-9d6985f89205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choose-room-disable&quot;)</value>
      <webElementGuid>b3ec53e8-6c3e-463b-9654-84085518ed43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='choose-room-disable']</value>
      <webElementGuid>c6a303ed-667c-4fa5-9bfd-0a0b3fef02f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-nav-wrapper']/div/div/div[2]/span</value>
      <webElementGuid>9bbe7e03-1320-40d1-bd31-7e0d742816ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Madikeri,'])[1]/following::span[1]</value>
      <webElementGuid>d7deedb9-cd10-45ed-9aac-1da6e784f317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gautham Villa Home Stay'])[1]/following::span[4]</value>
      <webElementGuid>7cbb7716-6059-496f-bcea-bf4c00e4f205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.'])[1]/preceding::span[1]</value>
      <webElementGuid>c6b1a136-5647-488c-93d0-53d2354c3566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photos'])[1]/preceding::span[2]</value>
      <webElementGuid>fc40af20-bb9b-4fdc-bcf7-940655614a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Choose Room']/parent::*</value>
      <webElementGuid>cd6c9475-56ed-42a4-805d-21547e194d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/span</value>
      <webElementGuid>7c140827-b815-43c9-bf89-d6a7e798e95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'choose-room-disable' and (text() = 'Choose Room' or . = 'Choose Room')]</value>
      <webElementGuid>94fee1eb-2636-4f8c-8330-babeda496c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berrylane Homestay'])[1]/following::span[4]</value>
      <webElementGuid>a7e9306d-d115-47cb-8deb-09dac78afc46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
