<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Save upto 40 with usage based pricing_bca950</name>
   <tag></tag>
   <elementGuidId>39bae702-9f02-4f82-bc0d-efb650fa928b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_hotel_checkin_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_hotel_checkin_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73b0e3f1-b3cd-4cf3-bb13-138bd0e1818f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>9adf542d-f5be-4ebe-a1e6-b48731c6303c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>5c8356de-d7fa-4c55-aad2-0f91eda72174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e47427b3-bc1a-4274-bfb7-9fc140e013cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7b6eba55-3e41-4830-ae16-82e57bc96ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hotel_checkin_date</value>
      <webElementGuid>4a5cef3e-8c23-4508-a0a7-3ce5bb79a93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_hotel_checkin_date</value>
      <webElementGuid>023e41a0-6be4-4231-96d2-4aefb4ba8b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-date-input BE_hotel_checkin_date</value>
      <webElementGuid>49a6a75b-70f1-45e6-938f-427b28c447eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_hotel_checkin_date&quot;)</value>
      <webElementGuid>00950803-e4b4-4b95-8875-4ee10fe54783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c75b67e-bbbc-4047-831c-52a30ca3a354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a7b02299-3979-4243-ac4b-1182d45e0195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>dafb2044-9f77-43f5-a845-971463278b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a25551f0-d8a3-49e6-9762-c791cb0d4fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b6fa2264-5ac9-4fb5-900b-4be71b90c658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hotel_checkin_date</value>
      <webElementGuid>3e506c2c-d240-4d29-8010-bcb5bc180577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_hotel_checkin_date</value>
      <webElementGuid>b91faa31-ca4d-4bca-aab1-f6dccc576e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-date-input BE_hotel_checkin_date</value>
      <webElementGuid>eec8b748-4efc-4ec1-9301-f06566415d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_hotel_checkin_date&quot;)</value>
      <webElementGuid>8b2980c4-e999-42a3-a62d-b38461a62fd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_hotel_checkin_date']</value>
      <webElementGuid>27d32446-4401-465e-94d2-db1cc2439f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div/div[2]/ul/li[2]/ul/li/section/label/input</value>
      <webElementGuid>b207b9e3-fd71-4389-b75c-5a7866ec676d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/label/input</value>
      <webElementGuid>ff2587ac-bb7e-49eb-bb79-9540a1503795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'hotel_checkin_date' and @id = 'BE_hotel_checkin_date']</value>
      <webElementGuid>8cf64327-9d73-41c3-a427-12aad4bbf9ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
