<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Domestic  International Hotels_BE_hot_7e54bf</name>
   <tag></tag>
   <elementGuidId>c2a0d5a8-7b98-42c3-9d2c-f8e606a50570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_hotel_destination_city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_hotel_destination_city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68abc544-86e2-4dc9-b3ee-a0eec627c5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>15c98066-07f2-45cd-9cc6-767324e593ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1098a832-bd95-41e7-b170-fbaa2eb5fd53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BE_hotel_destination</value>
      <webElementGuid>94615a73-31d6-48e3-b23f-93c5f47e8bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a5bb3ab-6616-4735-b9cd-ca35c66ac2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_hotel_destination_city</value>
      <webElementGuid>e5600abe-9acd-442a-820c-b3853b0533a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.setSelectionRange(0, this.value.length)</value>
      <webElementGuid>920abd6b-4e2f-4e9e-bfa3-d3736183d3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required_field ac_input hotel_destInput origin_ac</value>
      <webElementGuid>ab6e0ce2-73be-42d9-8932-9dfdf628ef70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_hotel_destination_city&quot;)</value>
      <webElementGuid>cb255ea6-8b6e-4b2f-96ed-daa03c2f67df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_hotel_destination_city']</value>
      <webElementGuid>b69fae97-b141-4fbd-b9fa-fb9461c951d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div/div[2]/ul/li/div/label/input</value>
      <webElementGuid>ebdbb7c7-912b-4ede-bc51-c039384de318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>60cad77d-37c9-4c31-b858-8df0004ed84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'BE_hotel_destination' and @type = 'text' and @id = 'BE_hotel_destination_city']</value>
      <webElementGuid>85048bc8-1cdc-4073-8c93-e3d27dd0a64a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
