<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_s_BE_hotel_htsearch_btn</name>
   <tag></tag>
   <elementGuidId>91bd072e-064f-4ce1-b427-9a11e04d76be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_hotel_htsearch_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_hotel_htsearch_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7339e26d-fbd4-4dd8-990a-156e3e4fdaab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>8f31bec0-cc69-4508-b001-5a9e5ed8687f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6fae1656-34a9-46ad-b289-5c930705d6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Hotels</value>
      <webElementGuid>2c0f9a06-5a5a-41a6-b892-4d40879b7360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackcategory</name>
      <type>Main</type>
      <value>Home Page</value>
      <webElementGuid>b0132d04-19ca-4854-919f-1dd94de21f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackaction</name>
      <type>Main</type>
      <value>Booking Engine</value>
      <webElementGuid>6b8f36b6-21f3-4c7e-8663-81942d2130dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackvalue</name>
      <type>Main</type>
      <value>Hotels Tab - Find Hotels</value>
      <webElementGuid>73ebc5a6-0ad5-43fd-be8b-6969b700bddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_hotel_htsearch_btn</value>
      <webElementGuid>3df65d19-6071-4953-b1ae-cc105143e3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js_ripple search-btn search-flights-btn eventTrackable js-prodSpecEvtCat</value>
      <webElementGuid>88dbdfac-e959-4201-8c76-0b050ac8822c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_hotel_htsearch_btn&quot;)</value>
      <webElementGuid>2db835e3-1c4e-41e1-810d-d32855194e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc41d82b-4a57-4b06-a469-e2196dd3ba48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>197d8277-e81a-469c-9609-fa6553388741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d893bc1d-cb5b-4e77-8b1e-3b8ace7a98c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Hotels</value>
      <webElementGuid>adc2232f-91d9-43ff-adce-67550ddd7e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackcategory</name>
      <type>Main</type>
      <value>Home Page</value>
      <webElementGuid>4b4f1a7f-2efa-4bf6-bc5d-1012b08202da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackaction</name>
      <type>Main</type>
      <value>Booking Engine</value>
      <webElementGuid>b7185059-7b75-43df-ab6d-05bc89a030ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackvalue</name>
      <type>Main</type>
      <value>Hotels Tab - Find Hotels</value>
      <webElementGuid>175f2496-2f9f-4f9e-b54f-b45e0783617f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_hotel_htsearch_btn</value>
      <webElementGuid>ec14e2ee-b060-4f02-9a11-415bb9cacfd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js_ripple search-btn search-flights-btn eventTrackable js-prodSpecEvtCat</value>
      <webElementGuid>e88bc3c5-b78c-4bb7-94f4-cb040b53bd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_hotel_htsearch_btn&quot;)</value>
      <webElementGuid>d58788ac-be27-453f-8229-3dfca3fb79a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_hotel_htsearch_btn']</value>
      <webElementGuid>2d6e5dde-4805-43c9-86ae-ccce46969361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div[2]/div[2]/input</value>
      <webElementGuid>dbfc1eb3-8b13-4453-80f1-e4a67823c043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2e055b62-56e4-43e5-9266-d579e49a24f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'BE_hotel_htsearch_btn']</value>
      <webElementGuid>00ef2872-668a-4ccf-8ba1-5d851da5bd50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
