<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Traveller and Hotel 2 Travellers , 1 Rooms</name>
   <tag></tag>
   <elementGuidId>ae01e770-6f38-45e6-8db8-6600d466a7e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.txt-ellipses.hotel_passengerBox.travellerPaxBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BE_Hotel_pax_info']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3ebbcfb0-c5fc-4059-b95e-eefab358b457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt-ellipses hotel_passengerBox travellerPaxBox</value>
      <webElementGuid>70a312d8-bacd-4f44-8491-a0cf403dd073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Traveller and Hotel 2 Travellers , 1 Rooms</value>
      <webElementGuid>20163a04-a899-4347-b92a-3fc444c6897c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_Hotel_pax_info&quot;)/span[@class=&quot;txt-ellipses hotel_passengerBox travellerPaxBox&quot;]</value>
      <webElementGuid>91ab2991-e60e-481f-b2f0-587c386b126b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BE_Hotel_pax_info']/span</value>
      <webElementGuid>990b50e2-aae3-43cc-882b-e46c8b72f410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Check-Out Time'])[1]/following::span[1]</value>
      <webElementGuid>194a3fd0-2b36-4de2-b50c-0e757f21c7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time'])[2]/following::span[2]</value>
      <webElementGuid>974d14f7-b914-4c93-8f20-74a9f670bcc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>b7fe1b46-c1d9-44fe-bddc-5ceff90d1ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Traveller and Hotel 2 Travellers , 1 Rooms' or . = 'Traveller and Hotel 2 Travellers , 1 Rooms')]</value>
      <webElementGuid>ec429526-8bf0-456e-af33-bbca709291b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
