<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_20</name>
   <tag></tag>
   <elementGuidId>32852105-8ea0-4874-9f2d-100a0fbd7ad5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='20/05/2022']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>cff8be33-0ecc-4173-9d0d-6d2dc40e81da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>20/05/2022</value>
      <webElementGuid>9eb89961-eb6a-4896-b678-5522ed0ad75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Friday, 20 May 2022</value>
      <webElementGuid>d0864e3e-ba36-4030-8d3c-9c2b57d9c1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>20/05/2022</value>
      <webElementGuid>26bacbe8-358a-4960-bfea-3b4419f1cece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        20
                                                         </value>
      <webElementGuid>5cf3f1a4-2cd9-4251-abd0-b79fe6b677f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;20/05/2022&quot;)</value>
      <webElementGuid>f33726c0-cd26-4ddb-b00c-28d22b02df80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='20/05/2022']</value>
      <webElementGuid>fa2b7567-53db-4b2b-b9f3-8dfacbaec689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='month-scroll1']/div/div[2]/table/tbody/tr[3]/td[6]</value>
      <webElementGuid>1b2f9de3-e445-4782-a954-7518aa4e06e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('May', &quot;'&quot;, ' 22')])[2]/following::td[20]</value>
      <webElementGuid>e2313a29-cae7-422f-bfe4-46fa61d15e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::td[34]</value>
      <webElementGuid>26b6a705-ee2a-4eff-84c4-4d54927938ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('June', &quot;'&quot;, ' 22')])[1]/preceding::td[16]</value>
      <webElementGuid>8eaef7b2-84e0-408c-9668-0945a9e12f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('July', &quot;'&quot;, ' 22')])[1]/preceding::td[51]</value>
      <webElementGuid>a51dda36-56ee-42d5-9fdd-080618ad2613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20']/parent::*</value>
      <webElementGuid>80bf44c9-7097-45ec-90ab-dab9587d85b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]</value>
      <webElementGuid>f4a35303-2e62-469d-aff0-c52ef6ac5b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Friday, 20 May 2022' and @id = '20/05/2022' and (text() = '
                                                        20
                                                         ' or . = '
                                                        20
                                                         ')]</value>
      <webElementGuid>2c9ed39a-a66c-4cef-bbf5-b06ac05e7a14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
