<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Going To_train_depart_date</name>
   <tag></tag>
   <elementGuidId>47876a56-b9f5-46eb-b058-dd48925737c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_train_depart_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_train_depart_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ce301bd-6f44-47c7-ac4d-d6bc2e30a02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>fd5d83d8-8727-4df1-9aa2-824741c771f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>fe5a733c-6157-4892-9381-5a3c6eb68759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8bf78c99-1d13-46b6-91c7-706e784f84fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>99cf9bf3-b4d1-4ee7-9c0c-fbdd2102bc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>train_depart_date</value>
      <webElementGuid>3cf55b3a-f280-4143-b487-a5d358dd7140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_train_depart_date</value>
      <webElementGuid>94fe6309-9600-47b8-a39a-2f6443e958c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-date-input BE_train_depart_date</value>
      <webElementGuid>540508b6-5158-4696-920f-83c7b05ca26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_train_depart_date&quot;)</value>
      <webElementGuid>c0fbddaa-cd4c-4468-b463-59ca0cd86939</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_train_depart_date']</value>
      <webElementGuid>4e9bde70-dd0d-4eb6-b94b-6acaf9dae119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div/div/ul[2]/li/section/label/input</value>
      <webElementGuid>ce543261-98b5-4efc-8871-af5ee21ec1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/label/input</value>
      <webElementGuid>d7f8b200-52d9-4fda-8cbe-06bd6afdb7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'train_depart_date' and @id = 'BE_train_depart_date']</value>
      <webElementGuid>f0e409e3-f37a-4d45-a723-d3cacf7c6bf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
