<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Book Train Tickets_train_from_station</name>
   <tag></tag>
   <elementGuidId>8731bea5-043d-459f-a442-1522491a75a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_train_from_station</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_train_from_station']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a96ffae-2702-4509-90f8-e25fb44d615b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8aeeb313-4a0f-4cbe-a020-209df41b8052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f1cee9fd-ed69-4d52-affe-ad013c25ff04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>train_from_station</value>
      <webElementGuid>1a870812-4a1c-4a3d-aca8-a568b1bd816f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f31a96e3-c33f-4e7a-bdfd-7f5634122e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_train_from_station</value>
      <webElementGuid>9de23d1b-973a-4f7c-9d27-637b5c537615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.setSelectionRange(0, this.value.length)</value>
      <webElementGuid>9733e9ee-6832-4258-b4ff-6eaa3a5d79bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required_field cityPadRight ac_input origin_ac</value>
      <webElementGuid>7f43ff12-1af5-4046-b527-7bc815fef296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_train_from_station&quot;)</value>
      <webElementGuid>9108fc17-db03-4ea8-99e6-c8b53e47fb09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_train_from_station']</value>
      <webElementGuid>8b5b7c2d-4efe-49cf-b3bc-b565fec5991d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div/div/ul/li/div/label/input</value>
      <webElementGuid>388d01eb-dfed-40c9-b75a-cdd30b8cf3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>29910d0a-8c60-43af-9aa7-97ca529d6e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'train_from_station' and @type = 'text' and @id = 'BE_train_from_station']</value>
      <webElementGuid>5ded55b0-98e5-41bd-9b11-e19cf3758cb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
