<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit Query</name>
   <tag></tag>
   <elementGuidId>21dc67d3-38c1-4f83-95b4-add8f222a965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.hidden-md.btn.black-button.fs-16.hidden-md.pnapop.submitReq_js.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='showleadform({});']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0f3aeef-60ba-44bf-b328-0c6cdf643abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>(showSpeakToAnExpert)</value>
      <webElementGuid>056a1f4f-a963-4256-a1fa-f439c2e91bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showleadform({});</value>
      <webElementGuid>3d0b3d4e-ee2b-4d23-bda4-88d245016bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden-md btn black-button fs-16 hidden-md pnapop submitReq_js ng-scope</value>
      <webElementGuid>5b8fb402-0ed2-4b7f-8b3f-42868a19e641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit Query</value>
      <webElementGuid>16f79e59-47cb-4e0a-bba6-4d04916bf5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;my-header&quot;]/div[@class=&quot;topbar row&quot;]/div[@class=&quot;route row&quot;]/div[@class=&quot;offer flL&quot;]/button[@class=&quot;hidden-md btn black-button fs-16 hidden-md pnapop submitReq_js ng-scope&quot;]</value>
      <webElementGuid>2692e261-6988-484d-82f8-c6eed0f6bfe4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='showleadform({});']</value>
      <webElementGuid>c3f9a989-0b71-4109-a902-ca61fbbf6268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[2]/div/div/div[2]/button[2]</value>
      <webElementGuid>1954d903-cdfb-48aa-9ce7-35082fbc22ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Now'])[1]/following::button[1]</value>
      <webElementGuid>99d744fc-398d-414e-a253-d56a5b589063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yatra.com'])[2]/following::button[2]</value>
      <webElementGuid>47f17913-f4f4-4fb1-b349-1b5be13a17aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photos'])[1]/preceding::button[1]</value>
      <webElementGuid>e38b83bf-7536-4d6f-bde3-315197db8bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotels &amp; Transport'])[1]/preceding::button[1]</value>
      <webElementGuid>b16f8e95-ebc4-42a7-9f17-c3e8fc11ac43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit Query']/parent::*</value>
      <webElementGuid>dcbd1c21-4ff8-4ca1-b4e7-6891c1f1db25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>1e592f6f-3441-4dbd-9c6b-9de3c86f3ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Submit Query' or . = 'Submit Query')]</value>
      <webElementGuid>5bd8ddcb-52c5-4cb5-a465-865e33cbb83c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
