<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Call 91-9990-614-615_customerMobileNumber</name>
   <tag></tag>
   <elementGuidId>a0bd49d7-cee8-45f1-ad9f-325157177f07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;customerMobileNumber&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='customerMobileNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fe40ff4-8f9d-4f9b-8779-5357a9299686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>bd118171-2705-4064-bf8d-a70e681556d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mob ng-dirty ng-valid-required ng-invalid ng-invalid-pattern</value>
      <webElementGuid>5fd05e81-c401-42bf-968f-8974115815ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerMobileNumber</value>
      <webElementGuid>7d59cbfe-37f1-44c1-81dd-ee8fd18cc2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>validateMobileNumber</value>
      <webElementGuid>d7f5dd8b-4a03-4cf1-aa25-a37ef9fe0171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile Number</value>
      <webElementGuid>bc7517c6-8140-4acf-a566-f6b64c4742a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>leadFormData.customerPhoneNumber</value>
      <webElementGuid>33daef0f-39aa-436d-983e-c1e704e6ef18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-requirederrormessage</name>
      <type>Main</type>
      <value>Please enter your mobile number</value>
      <webElementGuid>621bbcf8-e728-4c39-851c-cb31922d64a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-patternerrormessage</name>
      <type>Main</type>
      <value>Please enter a valid mobile number</value>
      <webElementGuid>913817b9-02f8-4171-aa30-55f8221b5fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>8f521e38-5f5a-4c27-9a90-294c6515e80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths ng-scope&quot;]/body[@class=&quot;hldy-content-display ng-scope hideOverflow&quot;]/div[@class=&quot;ng-scope&quot;]/section[@class=&quot;mob-popup fadeIn&quot;]/div[@class=&quot;sm-popup enq-form&quot;]/div[@class=&quot;step-one clearfix&quot;]/div[@class=&quot;left-column&quot;]/div[1]/form[@class=&quot;form clearfix ng-invalid ng-invalid-required ng-dirty ng-valid-minlength ng-invalid-pattern&quot;]/div[@class=&quot;group&quot;]/input[@class=&quot;mob ng-dirty ng-valid-required ng-invalid ng-invalid-pattern&quot;]</value>
      <webElementGuid>cc228ed3-70f9-4c3a-be0e-bc17ec55868f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='customerMobileNumber']</value>
      <webElementGuid>a46015ff-a1c1-4f38-b412-631593f49306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>8710e4d9-c235-4bc4-a613-f998dcf5e4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'customerMobileNumber' and @placeholder = 'Mobile Number']</value>
      <webElementGuid>c5473ba8-2e9d-43bd-8068-6f35e69cfb6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
