<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_THANK YOU FOR YOUR QUERY_submitQuery-_f10800</name>
   <tag></tag>
   <elementGuidId>7c7d0e11-e189-473f-b175-73f8ffbd6735</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitQuery-otp-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submitQuery-otp-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e7d29cc-03df-404d-b12d-b3a2914f6786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input ng-valid ng-dirty</value>
      <webElementGuid>3b671093-687d-4f4f-8570-e790ca4b7e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitQuery-otp-input</value>
      <webElementGuid>439000c3-c360-4b7f-a45a-2d78983a4904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f7178d8-86d3-45c9-9788-e49e763ecb8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>validateOtp()</value>
      <webElementGuid>50655aaa-5d63-400a-b803-b0fa2d3013a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>87032fbc-d9a3-410b-846a-a06061ab5fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>otp</value>
      <webElementGuid>8dd1ec60-8531-48f4-87c0-5b349955eeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitQuery-otp-input&quot;)</value>
      <webElementGuid>d8a99b35-4afb-4b45-b20b-57130c30cf95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submitQuery-otp-input']</value>
      <webElementGuid>e33b313e-0470-4119-bcb3-60018b7ec756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>22360aa7-6c38-4ae0-9bcc-ff2a8f48508f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'submitQuery-otp-input' and @type = 'text']</value>
      <webElementGuid>56bd0c74-5e2e-4c8b-9c39-3746fd565225</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
