<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Round Trip_bus_leaving</name>
   <tag></tag>
   <elementGuidId>4db364aa-d3b1-4821-ab4d-777d190a23f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_bus_from_station</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_bus_from_station']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ddb5da1-a0c2-4dd0-af8c-f08b1521ed91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>017d211c-f4bc-4cab-9562-76fad32f77b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1e6d9b1f-702c-4beb-8327-25d86820cc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bus_leaving</value>
      <webElementGuid>e028d8cc-5da8-4f25-9408-f8c590dcfc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3d6fb70-3491-4db7-ac51-37adf26fe306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_bus_from_station</value>
      <webElementGuid>1bd73e1a-f6e8-4d5b-a203-def5a1f0a246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.setSelectionRange(0, this.value.length)</value>
      <webElementGuid>4d0be962-8281-487a-91bd-e55973d0e81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required_field cityPadRight ac_input origin_ac</value>
      <webElementGuid>620baad9-86b4-4153-98dc-d43f9e8311a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_bus_from_station&quot;)</value>
      <webElementGuid>8aead010-2e40-4db5-b6e4-7df40e6353bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>469bd423-065f-4137-a17b-de80ff885075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aa5eed30-2717-4654-8c77-b12af87dc13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>40d127e4-69e1-456f-9d55-074a24b48cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bus_leaving</value>
      <webElementGuid>357c16a4-9f0c-43f0-93c7-7e181b5085db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12809589-0cf6-4ba7-98e9-20227c4e4734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_bus_from_station</value>
      <webElementGuid>ac063198-76de-453d-8825-c001552d46d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.setSelectionRange(0, this.value.length)</value>
      <webElementGuid>66841dae-c98b-4e86-95bc-34aeabea9cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required_field cityPadRight ac_input origin_ac</value>
      <webElementGuid>c6b234b0-74af-4dc5-a6cc-ac394fbae764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_bus_from_station&quot;)</value>
      <webElementGuid>1afbdefa-5bbd-44d0-a505-e1b9156bc255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_bus_from_station']</value>
      <webElementGuid>13582940-e758-4065-8454-dc265c32f45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div/div[2]/ul/li/div/label/input</value>
      <webElementGuid>d5752b75-a2eb-43a3-a6f4-6b59813b50c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cbd6f5d1-f84c-4d05-895d-ae3533cc147f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'bus_leaving' and @type = 'text' and @id = 'BE_bus_from_station']</value>
      <webElementGuid>e9804740-b448-44b9-93a5-472d33cf3bae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
