<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Depart Date_BE_bus_search_btn</name>
   <tag></tag>
   <elementGuidId>753f0f64-89fb-43a9-bad7-75c334c4092c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_bus_search_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_bus_search_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14c3d498-589b-42d7-bec7-37db24b7dd2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>81a8dd8f-3730-4959-9c3c-3873360e41b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>45ec8749-7b4d-4f46-814c-09fafa0b14e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Buses</value>
      <webElementGuid>4af43755-9a90-456a-a301-144d65dc9034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_bus_search_btn</value>
      <webElementGuid>3d886a42-9d06-42f0-8712-1306427da032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js_ripple search-btn</value>
      <webElementGuid>48f8f393-b237-4656-8855-f13229b0dd77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_bus_search_btn&quot;)</value>
      <webElementGuid>11161c19-da4c-4584-bbd8-df2cc594348e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>079f6936-4df1-4d6b-8c09-76c1e2333cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>d0803104-bf3e-4bdc-b4b1-3ed9a4511d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3bd284a3-b789-4b75-b2df-5669d20c0ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Buses</value>
      <webElementGuid>efabfc57-4ea0-48fc-af3f-2a1d12e6d189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_bus_search_btn</value>
      <webElementGuid>8d4f582a-698b-4b02-b743-da1eb6cda348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js_ripple search-btn</value>
      <webElementGuid>7f29e16f-73ce-4f82-a4bd-73f52843b548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_bus_search_btn&quot;)</value>
      <webElementGuid>e677076c-67e5-4d5f-9d0b-4c1c1e6f5205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_bus_search_btn']</value>
      <webElementGuid>025f4e7c-dc63-4db1-bc9b-6d62095ffc66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div[2]/div[2]/input</value>
      <webElementGuid>52d29108-9709-4735-b45d-3b8f1acd058c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>53b6139a-d30e-4f4d-b21f-dc2534700d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'BE_bus_search_btn']</value>
      <webElementGuid>ee6644f3-85c7-409c-aa33-c504fec5d219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
