<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Going To_bus_depart_date</name>
   <tag></tag>
   <elementGuidId>3f7ce18e-c470-4744-a884-2941d4c630b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_bus_depart_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_bus_depart_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60608cdf-11aa-4856-8f33-1142f7bbee34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>f3e18e10-4196-4b3b-9507-289614e37fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>6fd57b7d-f77f-45fc-96ca-3b9b87765494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9085b25d-48ce-4be5-abda-daf5e7f86fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b676e5aa-b928-4e08-a7f7-7a622de160a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bus_depart_date</value>
      <webElementGuid>8f4ef29f-4350-4e48-9e86-f992ea66d18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_bus_depart_date</value>
      <webElementGuid>2f1a0a99-f09f-4bf8-b74b-fae5e083f348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-date-input BE_bus_depart_date</value>
      <webElementGuid>b07adfc7-c6d1-4915-88a6-c4b9b0fd95db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_bus_depart_date&quot;)</value>
      <webElementGuid>65e8f44c-f0d7-433f-bb6e-5656c2b07f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af1607e3-2e9a-4162-ac30-e97253e4d75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2f089cb5-687d-472c-83d0-99e149ffd9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>d01ddaa3-4bfa-4f69-833e-d614afa36d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>023b1455-dd27-4db6-9b6c-fe3c9366b38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d5a22d8-1841-43aa-9c8b-fcb8ad1730c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bus_depart_date</value>
      <webElementGuid>8e4bcd1c-bf49-451e-96a4-08eb7cd981a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_bus_depart_date</value>
      <webElementGuid>b2445d68-113a-4702-b578-2b07ba909622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-date-input BE_bus_depart_date</value>
      <webElementGuid>5667a78f-b8b8-496a-9926-dba218d6f72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_bus_depart_date&quot;)</value>
      <webElementGuid>5f278c0e-24e0-4625-94ce-2ac4f304359f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_bus_depart_date']</value>
      <webElementGuid>82a4769a-bc5c-4d93-b08f-1a736691eaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div/div[2]/ul[2]/li/section/label/input</value>
      <webElementGuid>3d0a9a8d-937e-424d-9a39-c263fa0cf5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/label/input</value>
      <webElementGuid>35812831-9ecd-4a6d-900e-79c057a6e641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bus_depart_date' and @id = 'BE_bus_depart_date']</value>
      <webElementGuid>e80d1324-cd35-4889-b759-4e45750ad391</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
