<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_10</name>
   <tag></tag>
   <elementGuidId>4137bcb0-b6c8-4137-861a-350c1ac01138</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='10/05/2022']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e7d7ce06-2b65-4be7-90c4-db50422dd58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>10/05/2022</value>
      <webElementGuid>342483a0-9682-45e9-bb35-bae619741704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tuesday, 10 May 2022</value>
      <webElementGuid>996ca41b-633e-41b5-88d7-ddd48b5b8a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>10/05/2022</value>
      <webElementGuid>e0a7dcfc-b474-4f23-b95f-adbbcfdc5105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        10
                                                         </value>
      <webElementGuid>262fa9e9-7ad3-4527-9165-43694081bbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;10/05/2022&quot;)</value>
      <webElementGuid>1d972b0d-27ae-411f-ab45-c085fe6eaef4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='10/05/2022']</value>
      <webElementGuid>115bfac2-ff07-447b-a4a7-17b2bc45df6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='month-scroll1']/div/div[2]/table/tbody/tr[2]/td[3]</value>
      <webElementGuid>bb6af0dc-0297-4e35-b72f-066ade4bd0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('May', &quot;'&quot;, ' 22')])[1]/following::td[10]</value>
      <webElementGuid>bd7e9c63-7caf-4d04-b2b5-8b5a5e65458c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::td[24]</value>
      <webElementGuid>f4bb9800-eacd-4801-a661-5b47cf17c0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('June', &quot;'&quot;, ' 22')])[1]/preceding::td[26]</value>
      <webElementGuid>84e1312b-90a2-472e-9280-6babc5e02579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('July', &quot;'&quot;, ' 22')])[1]/preceding::td[61]</value>
      <webElementGuid>8288b6c1-42a0-4eac-98c0-9530cdfb41ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10']/parent::*</value>
      <webElementGuid>816c27dc-8f3e-48eb-8b69-9eedc33a06ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[3]</value>
      <webElementGuid>8b4cba4d-41ea-4a09-9d12-5476077d93da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Tuesday, 10 May 2022' and @id = '10/05/2022' and (text() = '
                                                        10
                                                         ' or . = '
                                                        10
                                                         ')]</value>
      <webElementGuid>eb0bbfd9-09bd-4ecc-b9ae-0675e4843151</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
