<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Hi_paymentDesktopLogo</name>
   <tag></tag>
   <elementGuidId>3f29f26a-2a96-4037-afce-b3b808053b6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paymentDesktopLogo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='paymentDesktopLogo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f38032ca-e3ab-4e79-ae16-8cb559696d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentDesktopLogo</value>
      <webElementGuid>2fd05038-3b65-4310-bbf7-7da37a8b4b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-newHeaderLogo </value>
      <webElementGuid>dfa29d16-192a-4d28-89e1-9ae4fb51ffa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentDesktopLogo&quot;)</value>
      <webElementGuid>dbe1e954-c896-4172-a0a3-bc9df3a31530</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='paymentDesktopLogo']</value>
      <webElementGuid>fa214a88-61d4-408c-b2df-eae0c399f26f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frescoHeader']/div/div/div/a/i</value>
      <webElementGuid>8025e8d3-d260-4f19-b643-065bc8a5a6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>1bcb03af-8716-415b-a49c-235822a472fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'paymentDesktopLogo']</value>
      <webElementGuid>0aab6654-f7e5-4cd7-8bd9-9fadb2bf90e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
