<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CVV_dc_cvv_id</name>
   <tag></tag>
   <elementGuidId>a75b0400-fedd-4642-b50c-726e24820ef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dc_cvv_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dc_cvv_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>632257d8-cded-44c9-8f08-28c1d0f2fe3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b02c4c15-4d39-4f67-a85d-610a0ade09ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w100 cvvInput flL ie6Input</value>
      <webElementGuid>6c9013eb-4a67-4246-bd1e-a5f59c0132d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dc_cvv_id</value>
      <webElementGuid>b53f9155-3139-4ff9-94c9-306b5b39aed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e4fb5903-f693-4c4a-8cd3-f6b0f81c6e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation</name>
      <type>Main</type>
      <value>required|regType[number]|lenCheck[3]</value>
      <webElementGuid>33aa2c22-0429-483b-9757-4f359af48ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msginfo</name>
      <type>Main</type>
      <value>* required|* number only|* invalid cvv length</value>
      <webElementGuid>f5bf1489-cca0-4ec8-a3f1-f495ed55655b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>838395cb-723f-401f-909f-9469a99b7461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dc_cvv_id&quot;)</value>
      <webElementGuid>f5b81ab7-7cb2-4b3f-b890-309e029631d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dc_cvv_id']</value>
      <webElementGuid>22f1f63f-d262-48cd-83c9-6ca6e5938059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='dc_newCard']/ul/li[2]/div[3]/input</value>
      <webElementGuid>ff945a7b-b6a7-4b1b-b41b-b143dc39dad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/article/ul/li[2]/div[3]/input</value>
      <webElementGuid>d27190d9-7509-4321-8d15-5b694f3b0189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'dc_cvv_id']</value>
      <webElementGuid>6ad841ed-2a46-4320-bfed-19080fa71a6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
