<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Debit Card Number_cno</name>
   <tag></tag>
   <elementGuidId>5fc71af3-cb66-49eb-a43a-a48a335bcdba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dc_cno_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dc_cno_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e20ee9ed-a8bd-4442-a1aa-782f93c64244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f6df6be-52b4-4d6c-b2c9-c8b669fdbd71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cardNumber w240 ie6Input</value>
      <webElementGuid>c03a54be-42c1-41a1-b3d7-99dd0b9bc3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dc_cno_id</value>
      <webElementGuid>91f08ae2-bdb9-497c-a09a-e7756fdab6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cno</value>
      <webElementGuid>6a340bb8-7195-4b47-91d0-bb4368675d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation</name>
      <type>Main</type>
      <value>required|validateLuhn|cardRegType[VISA]|supportedCard[VISA,dc]|enabledCard[VISA,VISA]</value>
      <webElementGuid>0ae9ebc7-1148-4ec9-88e4-7f23571e54ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msginfo</name>
      <type>Main</type>
      <value>* required|Enter valid card number|Enter valid card number|Enter a debit card|Card Type is temporarily not supported</value>
      <webElementGuid>5cf0d4e0-efa4-439f-8785-ba81f65e3cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>processcardno</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>03a49713-e703-4ffd-9c19-28a6f6aa12bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>3e7074f6-3d6f-4901-beee-9dcde8a238b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d871af35-843f-4dca-a5e1-bd7489eb81a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dc_cno_id&quot;)</value>
      <webElementGuid>c4edbce0-09f4-4926-b537-4e908a3b15f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dc_cno_id']</value>
      <webElementGuid>055e65c7-4999-43c5-b51e-46d06b5c24d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='dc_newCard']/ul/li/div/div/div/input</value>
      <webElementGuid>6fbf8524-0a7c-40cf-8e0d-5c9741fff120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/article/ul/li/div/div/div/input</value>
      <webElementGuid>723bd591-67d4-4244-9709-12005f7280af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dc_cno_id' and @name = 'cno']</value>
      <webElementGuid>29a019df-991a-41f9-b641-5884af276ad1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
