<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rs_payNow</name>
   <tag></tag>
   <elementGuidId>79cab85d-a561-4499-8e43-418e21478414</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payNow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payNow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3d00246-ecc9-4777-a45b-615eab9b95ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>246e9d2d-50b7-43a8-b433-d72aaad84f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytBtn-chek ytBtnOrange-chek eventTrackable</value>
      <webElementGuid>fa28a2d7-636e-46ad-8bb7-f3a2968590b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payNow</value>
      <webElementGuid>21acbe1a-e7ce-4e11-a8ce-bf11794b77e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pay Now</value>
      <webElementGuid>b94081d2-9964-4373-9639-f512540441aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ProcessPayment.payNow();</value>
      <webElementGuid>545497fb-8897-4392-b0b3-ec82ba14bebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackvalue</name>
      <type>Main</type>
      <value>Paynow:</value>
      <webElementGuid>77ec4880-457a-49b9-829c-c4b50c7bf0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackaction</name>
      <type>Main</type>
      <value>Payment</value>
      <webElementGuid>35d3fdc2-6a74-4def-82db-05528561da06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payNow&quot;)</value>
      <webElementGuid>6ba87020-6ce9-43fe-8b0c-59dafae761fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payNow']</value>
      <webElementGuid>57ca0802-a0ee-4e3e-b75f-155fa4bf4845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cpmt-all-payment-div']/div/div[4]/div/div[2]/div[52]/div[2]/input</value>
      <webElementGuid>97b22317-82d0-45e2-bc6d-9b478187404a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[52]/div[2]/input</value>
      <webElementGuid>55b69b25-9234-44b7-aad6-8edec19a8f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'payNow']</value>
      <webElementGuid>b8f64c7b-ba7e-48c5-8ddb-46b2c521a28c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
