<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name On Card_cardholder_name</name>
   <tag></tag>
   <elementGuidId>053e6592-603a-4bfd-af9b-a7c60b77c904</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dc_cardholder_name_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dc_cardholder_name_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c51a6e18-caee-4887-9759-557bef3f5832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fbfc6285-65eb-4bf4-bba3-5820eb9d7d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w188 ie6Input</value>
      <webElementGuid>78efcafa-8dc9-4b9f-9877-89bcbb5122fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dc_cardholder_name_id</value>
      <webElementGuid>6ad67d9e-0912-42ea-bd69-70921d007cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardholder_name</value>
      <webElementGuid>c35b6aef-341c-4bae-99da-5cc16e78a5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation</name>
      <type>Main</type>
      <value>required|regType[alpha]</value>
      <webElementGuid>169df6e9-e56a-4ca8-b6dc-5244a7a3a9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msginfo</name>
      <type>Main</type>
      <value>* required|* alphabets only</value>
      <webElementGuid>706fdc6e-02b4-4e07-8f2e-c7b97aa3cb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4da4b0aa-6454-496f-bca0-ac74c5bfe196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dc_cardholder_name_id&quot;)</value>
      <webElementGuid>bf53c7d9-9906-4e1a-b1b6-cc104176859e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dc_cardholder_name_id']</value>
      <webElementGuid>42a448b3-3b5d-4c5d-90ee-8c31bcaa6dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='dc_newCard']/ul/li/div/div[2]/input</value>
      <webElementGuid>3a078b28-11b0-4078-ade5-a4431ba498ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/article/ul/li/div/div[2]/input</value>
      <webElementGuid>580a9624-7995-4363-960e-d3df764dedc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dc_cardholder_name_id' and @name = 'cardholder_name']</value>
      <webElementGuid>091a3476-50fe-4bf2-bc63-deb5301f486d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
