<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Month010203040506070809101112</name>
   <tag></tag>
   <elementGuidId>b1c85760-b840-44b9-9723-6af0677d23c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dc_expm_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dc_expm_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e52dce1b-c1d3-4176-9949-b0a61432719e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dc_expm_id</value>
      <webElementGuid>80fee3f9-1fec-4881-855a-7df0036c98ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>paramid</name>
      <type>Main</type>
      <value>dc_expMonth_id</value>
      <webElementGuid>55edc09b-0bd8-4d32-bc48-6918d70706f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>115095d1-7b1e-4150-84d2-9aaa940f27d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msginfo</name>
      <type>Main</type>
      <value>* required</value>
      <webElementGuid>69fa0f33-a468-4359-99af-ea92c8f17e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>template</value>
      <webElementGuid>9a8d80f4-62f3-4581-915b-1f3b6b06b1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>44a74358-18d7-4c0e-b289-4f6b26968ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									Month
01
02
03
04
05
06
07
08
09
10
11
12

								</value>
      <webElementGuid>dad52334-d06e-49c4-8b1e-229a4f6edd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dc_expm_id&quot;)</value>
      <webElementGuid>4cf3de71-e338-4d16-9685-2fbd278791d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dc_expm_id']</value>
      <webElementGuid>8bdf001d-11a3-452a-836b-ee4876656c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='dc_newCard']/ul/li[2]/div/label[2]/select</value>
      <webElementGuid>159ca7fa-b045-4e4f-9a9d-82b3493ead98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiry Date'])[2]/following::select[1]</value>
      <webElementGuid>620ef962-e7d2-4d18-a6f6-e626cc4d7518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name On Card'])[2]/following::select[1]</value>
      <webElementGuid>0524e278-4d33-4aa4-9a14-a022f86ca66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete your payment using'])[2]/preceding::select[2]</value>
      <webElementGuid>d1a0d8e9-7368-44ba-964b-78ef38531a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/article/ul/li[2]/div/label[2]/select</value>
      <webElementGuid>8ce79bd9-889d-4c73-8dae-7fb204a59e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dc_expm_id' and (text() = '
									Month
01
02
03
04
05
06
07
08
09
10
11
12

								' or . = '
									Month
01
02
03
04
05
06
07
08
09
10
11
12

								')]</value>
      <webElementGuid>9e656958-a787-4351-be51-be0fd4f2a7ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
