<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Choose Room_1</name>
   <tag></tag>
   <elementGuidId>6abc1682-0d4c-4970-855d-e54472084154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choose-room-disable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='choose-room-disable']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>417810f8-fcf8-4e8b-9bd2-5b2ffa9cce76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choose-room-disable</value>
      <webElementGuid>35a1f837-7ae4-4738-862d-494f67b28aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fr btn new-blue-button</value>
      <webElementGuid>79e236ff-5ef2-4cd1-82e4-418266d24caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>scrollSection('view-room')</value>
      <webElementGuid>c7f1342f-f01d-46f8-ba03-10de995f3530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-ga</name>
      <type>Main</type>
      <value>Select Room|Hotel:Neelams The Grand:Room:Deluxe Room -  Bed &amp; Breakfast:Price:9558.779999999999</value>
      <webElementGuid>af3e7cd8-fe45-4c1e-a59b-d82f385e5806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose Room</value>
      <webElementGuid>9a8da0c8-83a1-4772-9423-b63406f1593d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choose-room-disable&quot;)</value>
      <webElementGuid>c452b003-4e37-4c0b-8829-bfcf06a20859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c6f037a1-54fa-454e-91c8-e5c4e2a92fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choose-room-disable</value>
      <webElementGuid>837f7313-8e97-48a5-b335-c0620866e572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fr btn new-blue-button</value>
      <webElementGuid>74f3d21a-6b00-4b36-bbd3-6e6f095d69bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>scrollSection('view-room')</value>
      <webElementGuid>423cb132-1faa-473e-b2a0-34285702650a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-ga</name>
      <type>Main</type>
      <value>Select Room|Hotel:Taj MG Road, Bengaluru:Room:Best Available Rate:Price:182750</value>
      <webElementGuid>5bd666e5-f109-4c54-a9dc-7f200ca6c6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose Room</value>
      <webElementGuid>9f4764e0-559a-41b0-8658-5dfc548cd4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choose-room-disable&quot;)</value>
      <webElementGuid>8200b05f-de52-46ff-bee0-25fcad444a57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='choose-room-disable']</value>
      <webElementGuid>5c4c3044-616d-47b9-a0b9-4422937664d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-nav-wrapper']/div/div/div[2]/span</value>
      <webElementGuid>1984b419-c515-40f8-8dd8-048118c6ad35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Office Road , Calangute, Bardez,'])[1]/following::span[1]</value>
      <webElementGuid>80442852-89c2-4ad2-8602-6228e090b40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neelams The Grand'])[1]/following::span[4]</value>
      <webElementGuid>c6a7f094-8bb2-4ba2-b698-cd4317ef786a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.'])[2]/preceding::span[1]</value>
      <webElementGuid>7df0a084-f53b-4bda-a99f-ebb239807cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Choose Room']/parent::*</value>
      <webElementGuid>02d15522-3bb0-4d9d-be38-88ee7eb66117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/span</value>
      <webElementGuid>13625e94-df33-41ea-ab60-6636d0eb4d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'choose-room-disable' and (text() = 'Choose Room' or . = 'Choose Room')]</value>
      <webElementGuid>649e4286-ac96-4c90-86df-8e70948c5129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Taj MG Road, Bengaluru'])[1]/following::span[4]</value>
      <webElementGuid>729b6523-925e-4361-bf53-b477b93e34c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GOT IT!'])[1]/following::span[5]</value>
      <webElementGuid>7366a1de-53cb-4197-be00-f61f104c6b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lowest Price Guarantee'])[1]/preceding::span[2]</value>
      <webElementGuid>64e64a16-8a77-408b-8759-8ff9b4a45376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
