<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Utilization</name>
   <tag></tag>
   <elementGuidId>54d268e1-a9ac-4423-9421-594ebda35259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='collapsibleSection']/section[2]/div/div[2]/div/ul/li[2]/div[3]/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>3cfdb1a6-45f0-4a85-bb33-5ea223776d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align1</value>
      <webElementGuid>2fe5ae55-ac82-431e-8dcd-a5c1510beb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Utilization</value>
      <webElementGuid>e8864e1a-731d-4f9d-9ea9-8366b8b62c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapsibleSection&quot;)/section[@class=&quot;fluid-section fluid-full-width&quot;]/div[@class=&quot;link-wrapper&quot;]/div[@class=&quot;full&quot;]/div[@class=&quot;bene main_container&quot;]/ul[1]/li[@class=&quot;dflex centre media-touple&quot;]/div[@class=&quot;touple shadow&quot;]/div[@class=&quot;dflex box2&quot;]/h1[@class=&quot;align1&quot;]</value>
      <webElementGuid>71bc485c-ca68-4d2b-b095-4b9fd90a2061</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='collapsibleSection']/section[2]/div/div[2]/div/ul/li[2]/div[3]/div/h1</value>
      <webElementGuid>23d9a613-a613-4e9f-8ee5-aec9927e0bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Club Together'])[1]/following::h1[1]</value>
      <webElementGuid>c1c2cc20-d0cb-4d58-bc8e-6a446fcb8421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Long Validity'])[1]/following::h1[2]</value>
      <webElementGuid>ba1081ce-7694-4faa-9073-fa70115b6e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::h1[1]</value>
      <webElementGuid>a120252a-19e4-4855-981a-2c702362c826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Utilization']/parent::*</value>
      <webElementGuid>553387cf-da3b-44de-a0a0-1899c643b4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[3]/div/h1</value>
      <webElementGuid>04377f46-910d-4bbe-bbb0-3bd06982b629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Utilization' or . = 'Utilization')]</value>
      <webElementGuid>e0d2019c-3b35-4e57-ab74-37e3c116889a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
