<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Club Together_image6</name>
   <tag></tag>
   <elementGuidId>29bb23fb-1938-4059-b951-60a24c75b2a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.image6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='collapsibleSection']/section[2]/div/div[2]/div/ul/li[2]/div[3]/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3bfb81af-ad21-4e7a-a963-adfe12d7ae58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image6</value>
      <webElementGuid>27af47fb-87a8-423f-8605-1ec2a75911d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapsibleSection&quot;)/section[@class=&quot;fluid-section fluid-full-width&quot;]/div[@class=&quot;link-wrapper&quot;]/div[@class=&quot;full&quot;]/div[@class=&quot;bene main_container&quot;]/ul[1]/li[@class=&quot;dflex centre media-touple&quot;]/div[@class=&quot;touple shadow&quot;]/div[@class=&quot;dflex box2&quot;]/div[@class=&quot;circle&quot;]/i[@class=&quot;image6&quot;]</value>
      <webElementGuid>b27da823-0319-492a-a3e3-4a15a11bd99e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='collapsibleSection']/section[2]/div/div[2]/div/ul/li[2]/div[3]/div/div/i</value>
      <webElementGuid>5905c233-3227-4439-811e-63c962545876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[3]/div/div/i</value>
      <webElementGuid>7ace5cfd-a65e-4dbd-ae11-8d7555a3d1b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
