<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Flat Rs.100 OFF on using Mobikwik Walle_8557a7</name>
   <tag></tag>
   <elementGuidId>05a40f94-f8c1-4ef0-9356-01ecaa83f190</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ajax-loader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='busDesktop']/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>881eeb9f-19b6-485b-b3bf-0638ee4a38b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax-loader</value>
      <webElementGuid>e6650cbe-4518-4801-b6ec-e38511feb6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;busDesktop&quot;)/div[1]/div[@class=&quot;ajax-loader&quot;]</value>
      <webElementGuid>c8899a98-aab7-460a-be66-49d808097352</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='busDesktop']/div/div[3]</value>
      <webElementGuid>6a90ee72-255a-442c-b444-c3094c8743db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flat Rs.100 OFF on using Mobikwik Wallet.'])[1]/following::div[1]</value>
      <webElementGuid>512344c9-2920-4eb0-9413-8d42cd5911da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YAYMBK'])[1]/following::div[2]</value>
      <webElementGuid>85522385-6540-4a2c-b9ff-a1ccd83b8ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed To Payment'])[1]/preceding::div[7]</value>
      <webElementGuid>ef4e7b6f-60ea-468a-8d6e-c73337be5199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Information'])[1]/preceding::div[10]</value>
      <webElementGuid>96787e89-00e5-462f-bdef-e0a3846a19d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]</value>
      <webElementGuid>0c2586a4-6ec7-4829-8568-8ab75c67cc63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
