<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Proceed To Payment</name>
   <tag></tag>
   <elementGuidId>f5275a40-e40b-4954-adde-823cb6916c24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-btn__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='busDesktop']/div/div[3]/div/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cc7a674b-07ca-4274-9fab-1ca2eb6b9616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn__content</value>
      <webElementGuid>d313dd6e-63c7-4073-bf88-3bcc0705ce9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed To Payment</value>
      <webElementGuid>d73824dd-3f93-4607-b5f3-78573154dfc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;busDesktop&quot;)/div[1]/div[@class=&quot;payment-div&quot;]/div[@class=&quot;txt-c resp-btn&quot;]/button[@class=&quot;btn-red v-btn theme--light&quot;]/div[@class=&quot;v-btn__content&quot;]</value>
      <webElementGuid>b1af39a9-9431-4971-81d5-885e5152a84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e87a280-dcef-4749-acae-c25a52a1f8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn__content</value>
      <webElementGuid>c9aa3d6e-1f6f-416f-a7e0-33917797fb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed To Payment</value>
      <webElementGuid>e75e4b97-7084-41b6-a3ef-391b27741999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;busDesktop&quot;)/div[1]/div[@class=&quot;payment-div&quot;]/div[@class=&quot;txt-c resp-btn&quot;]/button[@class=&quot;btn-red v-btn theme--light&quot;]/div[@class=&quot;v-btn__content&quot;]</value>
      <webElementGuid>c4669b44-0805-40e4-8e9d-df7a9a155082</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='busDesktop']/div/div[3]/div/button/div</value>
      <webElementGuid>12b82a84-aebc-4032-b0ab-9df212e88e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flat Rs.100 OFF on using Mobikwik Wallet.'])[1]/following::div[3]</value>
      <webElementGuid>8533bd98-c31f-47c5-8385-bd7293ae5d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YAYMBK'])[1]/following::div[4]</value>
      <webElementGuid>5b0e32e0-2376-4bab-80fa-61fdb680580f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Information'])[1]/preceding::div[1]</value>
      <webElementGuid>53562cee-a852-41e8-986c-1c0b86beb0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investor Relations'])[1]/preceding::div[1]</value>
      <webElementGuid>bf5b2c9d-ef9c-4d35-afb8-7c9e427d04fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proceed To Payment']/parent::*</value>
      <webElementGuid>393800a3-335a-4c98-b75d-f988e0a8246b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>4a7df07e-4e3b-4976-9af6-71c6e83a2e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Proceed To Payment' or . = 'Proceed To Payment')]</value>
      <webElementGuid>695daa24-20af-4c04-8711-5ad6d5d14d2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
