<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__number border-none</name>
   <tag></tag>
   <elementGuidId>d397e25f-a284-4700-84e4-40a1b0be3562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.number.border-none</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>275ebd96-b326-41f8-b8d7-4201445ac6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fff1ab7a-9613-447a-9904-d5c217a6a6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile Number</value>
      <webElementGuid>6500e71c-8690-4001-9a7a-93515f535bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f3c68eff-8924-4c32-b3e1-cdf6f653f31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>44d30dc1-e5f1-437e-8bda-f51ea1a19f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number border-none</value>
      <webElementGuid>c6fbecdd-7be8-4fcb-99de-ec43bb9ca88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;busDesktop&quot;)/div[1]/div[@class=&quot;yatra-review wrapper wrapperwidth&quot;]/section[@class=&quot;fl left-sec&quot;]/div[@class=&quot;flex module-box&quot;]/div[@class=&quot;layout row wrap&quot;]/div[@class=&quot;flex xs10&quot;]/div[@class=&quot;layout layout row wrap travel prel&quot;]/div[@class=&quot;flex xs6&quot;]/div[@class=&quot;layout row wrap input-style mobile-div&quot;]/div[@class=&quot;flex xs8&quot;]/input[@class=&quot;number border-none&quot;]</value>
      <webElementGuid>1ef7a851-1ec9-4277-9c84-b026b38a6042</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>316d7332-d0a6-4008-a006-25d024b9f9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='busDesktop']/div/div[2]/section/div[4]/div/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>a96bdf52-2bee-4fd9-bfd3-1d22ba57030a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6bb94a75-c261-4836-a008-be1c1b84675b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Mobile Number']</value>
      <webElementGuid>31863a73-6e9c-4765-aca3-2e12ee8f3708</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
