<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Book Now</name>
   <tag></tag>
   <elementGuidId>bd98278f-e881-409d-97f7-50ff64355aa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[4]/div/div[2]/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0c720e4a-4ce5-4070-90b7-d5209300f739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>98dd4e2b-c5cf-4a58-af2c-ecca1900d746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book Now</value>
      <webElementGuid>6b124fdd-6939-488a-bdbe-c341209d082a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;srp-tuple&quot;]/div[@class=&quot;dflex&quot;]/div[@class=&quot;right-module&quot;]/div[@class=&quot;inclusion-price&quot;]/div[@class=&quot;price-wrap&quot;]/div[@class=&quot;book&quot;]/div[@class=&quot;btn&quot;]</value>
      <webElementGuid>1621c90e-3ef9-4469-b831-104bba88bbef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div/div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>442ca6fd-ff5e-4ef5-b903-c793af74678b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹50,563'])[1]/following::div[6]</value>
      <webElementGuid>5fbc1da8-077d-436b-b2b4-324f01df4871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Now'])[2]/preceding::div[3]</value>
      <webElementGuid>362834d7-e80b-4f39-bdf6-8776142e88ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Book Now']/parent::*</value>
      <webElementGuid>2fb8a090-0fb0-4879-8b6d-fc2074c93dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>c5aac27f-f68e-4c7f-99fa-33e535d082f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Book Now' or . = 'Book Now')]</value>
      <webElementGuid>6ba9a596-b8e2-4d2a-bcd1-57d341fcbf21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
