<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Outstation Oneway</name>
   <tag></tag>
   <elementGuidId>af6619c7-f402-4edc-87f2-57819b8df0af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='booking_engine_modues']/div/div/div[2]/ul/li/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6ddeecaf-d314-427d-b57b-62b05a209410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>BE_cab_non_stop</value>
      <webElementGuid>2d86708e-7911-4504-bdc5-87bb9b2fb2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Outstation Oneway</value>
      <webElementGuid>edadd860-6dde-4e12-a96d-31ff093a36d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oneway_outsation</value>
      <webElementGuid>6fb11df7-91f1-432f-82c5-84bc1f5f01b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outstation Oneway</value>
      <webElementGuid>241f6b7e-2d60-4263-b6b6-04edaea87bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_engine_modues&quot;)/div[@class=&quot;be-cabs be-form-wrapper be-form-wrapper&quot;]/div[@class=&quot;journey-details clearfix&quot;]/div[@class=&quot;oneway-roundtrip CitySwap safariFix modifyList&quot;]/ul[@class=&quot;clearfix mt5&quot;]/li[1]/ul[@class=&quot;radio-section&quot;]/li[@class=&quot;oneway&quot;]/a[@class=&quot;oneway_outsation&quot;]</value>
      <webElementGuid>561c29aa-3be1-45ab-a4dc-ec4234defda5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div/div[2]/ul/li/ul/li[2]/a</value>
      <webElementGuid>75264897-1c8d-4f85-858a-ada2afe79c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Outstation Oneway')]</value>
      <webElementGuid>503b8ae5-d841-40f6-9f4d-c4f3d910d19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outstation Round Trip'])[1]/following::a[1]</value>
      <webElementGuid>f1599e77-23aa-4b41-bb69-a7f44f193c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='airport transfer'])[1]/following::a[2]</value>
      <webElementGuid>c18a2c64-438a-4d17-8dde-f2f053d161d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Hourly Basis'])[1]/preceding::a[1]</value>
      <webElementGuid>8f167f6c-e344-4430-b592-d2c51dde8e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Airport'])[1]/preceding::a[2]</value>
      <webElementGuid>1614938b-5edd-4b7f-9c19-a6d3f8314912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Outstation Oneway']/parent::*</value>
      <webElementGuid>94fa3763-fe0f-4894-a315-d362614b5b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/ul/li[2]/a</value>
      <webElementGuid>a40c7bcd-8e83-4a8c-a116-f09eeaf14596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Outstation Oneway' and (text() = 'Outstation Oneway' or . = 'Outstation Oneway')]</value>
      <webElementGuid>97062539-7313-4759-9910-82720198cc95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
