<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_rental</name>
   <tag></tag>
   <elementGuidId>d561bb39-5636-404e-ac6f-e33025a7c7a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.blur_class</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='booking_engine_modues']/div/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b9c13c85-b875-40cc-a7b9-2b4de288d426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>1bf91f5e-7447-4649-89bd-ee589eb02ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>rental</value>
      <webElementGuid>8b24bf3d-77a1-49ae-849a-088b134010c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blur_class</value>
      <webElementGuid>a6b4d467-95b0-42c7-8eb6-94f797198043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         rental
                         </value>
      <webElementGuid>c6400b01-7adf-4762-b971-f9ae9872fbb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_engine_modues&quot;)/div[@class=&quot;be-cabs be-form-wrapper be-form-wrapper&quot;]/div[@class=&quot;journey-details clearfix&quot;]/div[@class=&quot;trip-type mor-option&quot;]/ul[@class=&quot;selc-flight-options&quot;]/li[1]/a[@class=&quot;blur_class&quot;]</value>
      <webElementGuid>d0d86cc9-ad61-47f3-8fa3-6b9038bb79e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div/div/ul/li/a</value>
      <webElementGuid>cddf3fec-8674-4a44-8ddd-0708ece7dad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'rental')]</value>
      <webElementGuid>a8d65898-4e15-4d5b-86ac-e293ab97f422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Outstation, Local Cabs and Self Drive Cars'])[1]/following::a[1]</value>
      <webElementGuid>9425cc5b-ed3b-4e5b-aa63-668bec3540db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charter Flights'])[1]/following::a[1]</value>
      <webElementGuid>c18c7eac-1ba0-40db-a473-316cd5cbe5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='airport transfer'])[1]/preceding::a[1]</value>
      <webElementGuid>73ec2222-928f-41be-9b27-5c8421dabd7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Airport'])[1]/preceding::a[2]</value>
      <webElementGuid>2c9ff126-7a7f-4643-a72c-4c48d9cba1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='rental']/parent::*</value>
      <webElementGuid>8a181232-3337-4af9-a1eb-befe1ed6e8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[16]</value>
      <webElementGuid>777117f4-f618-454b-b399-31b56d43afe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/ul/li/a</value>
      <webElementGuid>2e4d5a7e-617a-4d4c-b110-00db94151b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @title = 'rental' and (text() = '
                         rental
                         ' or . = '
                         rental
                         ')]</value>
      <webElementGuid>b48c3b2f-8ea8-4449-b956-0cc3b6db9e5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
