<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Visa NEW</name>
   <tag></tag>
   <elementGuidId>2d1d7570-706f-4bb3-afed-7225b2dfd1b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#booking_engine_visa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='booking_engine_visa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db597693-a1da-49a6-a6b0-80474933170a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>booking_engine_visa</value>
      <webElementGuid>4a4db0ce-063d-4ac5-9fee-0a2ca1a3c1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.yatra.com/visa/</value>
      <webElementGuid>61ade595-0218-4ea4-8e15-07ed443a77f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>9e55566d-a535-47da-bac6-5a82ff7e9131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Visa</value>
      <webElementGuid>76ec2d88-c865-4a60-b510-b2e3c4d74b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>a989d490-d0b0-4326-a1b0-00102cb4c9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative</value>
      <webElementGuid>caa2d9fb-6df3-4091-ad04-fd50c6fce021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Visa NEW</value>
      <webElementGuid>076eee94-38ca-46be-ae5f-9727728bbbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_engine_visa&quot;)</value>
      <webElementGuid>735bba0a-0ab1-4c7f-966c-881c72dc6a0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='booking_engine_visa']</value>
      <webElementGuid>fffaeae7-b986-4df2-a33c-7362676cc92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bEnginePos']/ul/li[7]/div/ul/li/a</value>
      <webElementGuid>34e782e2-2d64-437f-98be-07c7cd93546c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ More'])[1]/following::a[1]</value>
      <webElementGuid>17b751ea-bb2c-4da1-9275-c4f54950edf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW'])[5]/following::a[1]</value>
      <webElementGuid>9dc5792f-693e-4e3f-b763-e0d019d91949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.yatra.com/visa/')]</value>
      <webElementGuid>d66b9937-14c8-497d-a710-825f931ea1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/ul/li/a</value>
      <webElementGuid>05444978-ee72-4d14-be63-80a6d11b4235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'booking_engine_visa' and @href = 'https://www.yatra.com/visa/' and @title = 'Visa' and (text() = ' Visa NEW' or . = ' Visa NEW')]</value>
      <webElementGuid>83cd47f7-14d3-492f-8465-cec1509e5cbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
