<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Select Return Time_demo-icon icon-go</name>
   <tag></tag>
   <elementGuidId>42aa47b6-b4e8-4b30-a24f-83847e1d8349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.opaque-layer.abs.show > div.view-return > i.demo-icon.icon-go</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='booking_engine_modues']/div/div[4]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>944bf478-b401-46f0-88e9-b2832cd23bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demo-icon icon-go</value>
      <webElementGuid>4c7542bc-6368-410c-9628-05a1e4e2cd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_engine_modues&quot;)/div[@class=&quot;be-cabs be-form-wrapper be-form-wrapper&quot;]/div[@class=&quot;opaque-layer abs show&quot;]/div[@class=&quot;view-return&quot;]/i[@class=&quot;demo-icon icon-go&quot;]</value>
      <webElementGuid>f0269b2a-6b17-4e9e-a90f-31525e68b504</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div[4]/div/i</value>
      <webElementGuid>ef7b6ea5-86c2-4caa-90b1-42df250fd130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/i</value>
      <webElementGuid>0021d349-9cd2-499f-ade1-6eb0bb834b4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
