<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Destination_hotel_checkin_date</name>
   <tag></tag>
   <elementGuidId>d9fa809f-66f9-4202-a2e6-d4147cdb35e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_cabs_checkin_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_cabs_checkin_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81999424-8c34-4f68-adcb-9a9bcaa18df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>8a45856f-a426-441e-bf05-024559e9a86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>7e0d98b4-5c72-4426-9069-b8baae8982e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c51fb2ea-bf50-4dfc-9cc9-95966ce74ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a0c2b831-d8c4-4640-bdd0-ebd0ffa191e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hotel_checkin_date</value>
      <webElementGuid>89a75291-1bbb-45f9-8d75-12543a64b9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_cabs_checkin_date</value>
      <webElementGuid>b8e657ba-c0e4-4682-8799-4ebd084aaf67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-date-input BE_cabs_checkin_date</value>
      <webElementGuid>376ead53-8a86-4a4c-9c5e-791dbb0e9cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_cabs_checkin_date&quot;)</value>
      <webElementGuid>aaca02a9-234e-477c-ab25-597b5ed08c68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_cabs_checkin_date']</value>
      <webElementGuid>e59d97a3-7ca4-477b-b055-4639bee6020a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div/div[2]/ul[5]/li/ul/li/section/label/input</value>
      <webElementGuid>5f990a75-b9a8-4ea8-addf-8610726f954b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/label/input</value>
      <webElementGuid>ff7f540f-2a58-48c6-aac5-a44615f01e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'hotel_checkin_date' and @id = 'BE_cabs_checkin_date']</value>
      <webElementGuid>f262bea5-d985-4394-91f5-87cb5ddb5b1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
