<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From Airport_BE_cabs_from_airport_location</name>
   <tag></tag>
   <elementGuidId>1e3e78ae-92ae-4df9-8bf8-fba02be26c50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_cabs_from_airport_location</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_cabs_from_airport_location']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e3ff449-c2c8-4e67-8ce7-1a7377aa83bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4b04c622-a616-453e-a649-21e2da7a78ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d2bbbfb-7368-46e9-9d63-085e5e3fe471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BE_cabs_from_airport_location</value>
      <webElementGuid>c68bbe60-607b-441e-8cdc-a9cd0a438b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2a87f87-1d50-4778-a196-09a67bde7a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_cabs_from_airport_location</value>
      <webElementGuid>aa20a3d1-9dc3-4d1a-bcb2-9549e55f1fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.setSelectionRange(0, this.value.length)</value>
      <webElementGuid>b9bc87f7-bef4-44de-af5e-72a32b6d38fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required_field ac_input cabs_destInput origin_ac</value>
      <webElementGuid>6829513b-a832-46cf-a8e1-bc7d9fda792d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_cabs_from_airport_location&quot;)</value>
      <webElementGuid>8098b2c4-d542-4fb9-b2b3-9141302e9b2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_cabs_from_airport_location']</value>
      <webElementGuid>310a171d-7006-45d9-b570-2a9787ffcd4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div/div[2]/ul[2]/li[2]/div/label/input</value>
      <webElementGuid>b84e1b29-13e8-4b4b-8b32-a55790e7a235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/label/input</value>
      <webElementGuid>0aad4809-253f-4149-a8cc-3ab8d363fbf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'BE_cabs_from_airport_location' and @type = 'text' and @id = 'BE_cabs_from_airport_location']</value>
      <webElementGuid>d52e62c0-a898-4b32-853d-e8c1ac61ccc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
