<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Pickup Time_hotel_checkout_date</name>
   <tag></tag>
   <elementGuidId>874bd4b2-95c2-4256-a4bc-002910b8214f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_cabs_checkout_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_cabs_checkout_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34871c45-6e0a-464f-85fe-aec89a5357b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7ff5cda4-370b-4f70-996d-3e0df12a32d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>83d47d46-133b-4880-a4e1-efb8090e6fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81273c9f-b147-4830-b38b-5f78f692d987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>335e0972-c994-41a0-82f3-04681a825074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hotel_checkout_date</value>
      <webElementGuid>c7333a59-a2c7-4b89-8ebb-368701412654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_cabs_checkout_date</value>
      <webElementGuid>f1c69605-ac99-4d49-b81d-0f7c35aa50d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-date-input BE_cabs_checkout_date</value>
      <webElementGuid>e5289169-fc0e-42d3-809b-82f96282c013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_cabs_checkout_date&quot;)</value>
      <webElementGuid>3456d9b5-ec12-4b53-ad3f-2d857fbd80ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_cabs_checkout_date']</value>
      <webElementGuid>62b879b9-b919-4a2a-a415-a1f218a34573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div/div[2]/ul[5]/li/ul/li[3]/section/label/input</value>
      <webElementGuid>0eda6642-2a1d-4b06-865e-f08528021b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/section/label/input</value>
      <webElementGuid>9b3d10a5-04b4-407b-a2b7-ced4dd442a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'hotel_checkout_date' and @id = 'BE_cabs_checkout_date']</value>
      <webElementGuid>d44d365e-f209-4e5f-b8b7-9f91c33907fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
