<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To Airport_cabs_leaving</name>
   <tag></tag>
   <elementGuidId>130fb277-d5ff-4920-ae71-7959aa570de2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_cabs_from_station</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_cabs_from_station']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f831991a-4836-4ffc-abe9-a0b5be0f08f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a5d6e16d-6968-4c11-a01c-d60aa15919a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b084035c-b158-4b85-ba07-586a713196fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cabs_leaving</value>
      <webElementGuid>cb93fc59-6a75-4606-9780-e4e3fd0755e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e62a7dfa-f40d-45c7-8656-7420147d6e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_cabs_from_station</value>
      <webElementGuid>4b954911-1df0-4af5-9788-aa2eb5586e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.setSelectionRange(0, this.value.length)</value>
      <webElementGuid>7c7dfc6b-003e-4d7b-8fe0-2be32651792a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required_field cityPadRight ac_input origin_ac</value>
      <webElementGuid>e92b9418-d177-422d-8bbf-017de457f0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_cabs_from_station&quot;)</value>
      <webElementGuid>cb431a1e-84f3-4898-95f4-4dd50938345d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_cabs_from_station']</value>
      <webElementGuid>7faced4b-1e04-4062-b77f-adfea6ea06b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div/div[2]/ul[4]/li/div/label/input</value>
      <webElementGuid>d1bae45c-b443-449d-ba69-949dc96068b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[4]/li/div/label/input</value>
      <webElementGuid>60670848-78bf-4b4f-a410-b68f1d4b18b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cabs_leaving' and @type = 'text' and @id = 'BE_cabs_from_station']</value>
      <webElementGuid>efc451ab-a1f3-44be-a1f4-3a1a00005af8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
