<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Get a Quote</name>
   <tag></tag>
   <elementGuidId>09449dba-8c08-4b3b-819f-afb8ad824878</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.Quote</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='collapsibleSection']/section[2]/div/div/div[2]/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3716097e-ee1a-4388-8e77-4e1e7d4c47ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://app.yatrafreight.com/landing/login</value>
      <webElementGuid>903406ee-3ff1-4d9a-9f21-77760294fa73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Quote</value>
      <webElementGuid>a7f39386-5834-4dc3-8326-b413af6b7ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get a Quote</value>
      <webElementGuid>1fc291f8-526e-4c99-a999-6b234b782e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapsibleSection&quot;)/section[@class=&quot;fluid-section fluid-full-width&quot;]/div[@class=&quot;link-wrapper&quot;]/div[@class=&quot;career-wrapper&quot;]/div[@class=&quot;background-item&quot;]/div[@class=&quot;container-wraper mobile-height h400 mb100&quot;]/div[@class=&quot;content-box rightSideContent mobile-flex mt105&quot;]/div[@class=&quot;textContent mobile-center&quot;]/a[@class=&quot;Quote&quot;]</value>
      <webElementGuid>691c0ff6-e503-43af-997e-9e7f698a0701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8602219c-dce6-4ab8-a476-2d9e6ec485e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://app.yatrafreight.com/landing/login</value>
      <webElementGuid>b218e7e3-c396-4b21-97e8-c704d889b53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Quote</value>
      <webElementGuid>7d0a7b98-ef4d-4897-a74e-179c6072bc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get a Quote</value>
      <webElementGuid>a429aa7f-08e7-4da5-838a-1f13872cf992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapsibleSection&quot;)/section[@class=&quot;fluid-section fluid-full-width&quot;]/div[@class=&quot;link-wrapper&quot;]/div[@class=&quot;career-wrapper&quot;]/div[@class=&quot;background-item&quot;]/div[@class=&quot;container-wraper mobile-height h400 mb100&quot;]/div[@class=&quot;content-box rightSideContent mobile-flex mt105&quot;]/div[@class=&quot;textContent mobile-center&quot;]/a[@class=&quot;Quote&quot;]</value>
      <webElementGuid>f74be7bb-0096-49dd-ace1-96dc3b11929d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='collapsibleSection']/section[2]/div/div/div[2]/div/div/div[2]/a</value>
      <webElementGuid>2da983e9-0a03-407c-afc0-3898eb9ea519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Get a Quote')]</value>
      <webElementGuid>1a254ae1-3fc9-4d67-9bdc-e1bb7ec3e06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Persolized Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>9db98f41-26f7-403c-9138-6b2fd38b80cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What We Offer'])[1]/preceding::a[1]</value>
      <webElementGuid>a636f8eb-fcf1-4f15-b52d-f08ab1f93ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ocean Freight'])[1]/preceding::a[1]</value>
      <webElementGuid>094a9542-6aeb-4459-a381-db327ed660e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get a Quote']/parent::*</value>
      <webElementGuid>1cc38ac3-b3c4-4eec-826e-bddb1df17726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://app.yatrafreight.com/landing/login')]</value>
      <webElementGuid>9646bc2a-b42c-4722-b366-36b102c6f19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/a</value>
      <webElementGuid>4ea0c109-e8ef-4ecb-8829-a045f95acc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://app.yatrafreight.com/landing/login' and (text() = 'Get a Quote' or . = 'Get a Quote')]</value>
      <webElementGuid>dbdc898d-e1a7-45db-a276-22a373a4da8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
