<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>277cc63a-6135-4344-8ba3-ac8e16541c1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aboutYt']/ul/li[4]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8743974d-077d-4e22-83ab-078656ac31ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ns.yatracdn.com/common/images/fresco/fresco-footer-images/freight/personalised-dashboard.svg</value>
      <webElementGuid>bfb2af21-4859-494f-988f-9efb1cd3079c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aboutYt&quot;)/ul[@class=&quot;about-box&quot;]/li[4]/img[1]</value>
      <webElementGuid>9ed9449d-36e4-4531-b6bb-cfcc723f7769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a87e2cf6-6e95-4eaa-a312-5be947b80259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ns.yatracdn.com/common/images/fresco/fresco-footer-images/freight/personalised-dashboard.svg</value>
      <webElementGuid>44342348-02b8-4829-b5f0-ed9057afb253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aboutYt&quot;)/ul[@class=&quot;about-box&quot;]/li[4]/img[1]</value>
      <webElementGuid>7dbcc0c1-3f27-4085-af7e-904f5e43e555</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aboutYt']/ul/li[4]/img</value>
      <webElementGuid>78401a89-c5fb-4a5b-8d4b-27c4f4bbdc0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ns.yatracdn.com/common/images/fresco/fresco-footer-images/freight/personalised-dashboard.svg')]</value>
      <webElementGuid>8ae12524-5c4a-4ea9-95b2-f252525893cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/img</value>
      <webElementGuid>0ed67969-5dbf-4ed8-9c13-a6b339806bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ns.yatracdn.com/common/images/fresco/fresco-footer-images/freight/personalised-dashboard.svg']</value>
      <webElementGuid>0f425a45-cfca-45f4-a20e-394fe7776b57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
