<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Persolized Dashboard</name>
   <tag></tag>
   <elementGuidId>d72f534f-2a38-4737-b268-556ae16387ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aboutYt']/ul/li[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>769c0b21-0ff3-4071-a37f-cbbd0f991305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt10</value>
      <webElementGuid>078d6706-b04c-4c4d-b497-b279fcd814aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Persolized Dashboard</value>
      <webElementGuid>4ffdef01-1fe5-401f-ac4b-dc60ec69a920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aboutYt&quot;)/ul[@class=&quot;about-box&quot;]/li[4]/span[@class=&quot;mt10&quot;]</value>
      <webElementGuid>ca966da8-252f-4a8a-acfc-61b056e958ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>637f37be-0f27-4e74-bccd-a4de50f24c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt10</value>
      <webElementGuid>66a5b805-8452-424d-84e1-09bd08164a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Persolized Dashboard</value>
      <webElementGuid>caa0c425-398a-45f7-a87b-8d1c1fd27d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aboutYt&quot;)/ul[@class=&quot;about-box&quot;]/li[4]/span[@class=&quot;mt10&quot;]</value>
      <webElementGuid>931cbd09-b39a-452c-b449-2a321f4678a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aboutYt']/ul/li[4]/span</value>
      <webElementGuid>ed7da8d7-97ef-4352-8d85-911950966ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Documentation'])[1]/following::span[1]</value>
      <webElementGuid>3167f6c4-546c-4d7e-98a5-12b106642307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Real-time Container Tracking'])[1]/following::span[2]</value>
      <webElementGuid>a1f954cc-e6f6-4eed-856e-120380fb4ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get a Quote'])[1]/preceding::span[2]</value>
      <webElementGuid>28413b54-4093-45f1-8a33-4b0b853c7b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Persolized Dashboard']/parent::*</value>
      <webElementGuid>ea831b07-fd10-4109-927a-85259a783ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/span</value>
      <webElementGuid>228f990e-c729-4f48-a1de-694f004e5bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Persolized Dashboard' or . = 'Persolized Dashboard')]</value>
      <webElementGuid>d13caa3f-a78e-456e-83b0-5251dafd8412</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
