<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Depart From   New DelhiMumbaiJaipurBeng_667467</name>
   <tag></tag>
   <elementGuidId>430d0156-903e-457d-af22-7c9baa96fcd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@type='holidays']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.be-holidays.be-fixture.be-form-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73c29eed-7b87-43aa-abbb-0b9ea6aedea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>be-holidays be-fixture be-form-wrapper</value>
      <webElementGuid>d67afe8f-6405-4f5a-9425-f7717918b0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>holidays</value>
      <webElementGuid>35959871-ed73-4df0-a1b9-579308b10220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isnewintsrpenable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4ae30725-a96e-434f-af8b-b2fcda62d637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>istrainsearchblock</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4a514ba8-3db5-44b3-bbb1-728cf90a0fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>smebussearchurl</name>
      <type>Main</type>
      <value>//ebus.yatra.com/busview/bussme/search</value>
      <webElementGuid>d0517376-b3ce-4c39-afad-c659a2f9bb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Depart From   New DelhiMumbaiJaipurBengaluruChennaiHyderabadPuneKolkataLucknowAhmedabad     Going To        Month of Travel (Optional)      
          Select Origin City
        </value>
      <webElementGuid>351e8aea-caee-41f2-ab75-877e3a5fa256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_engine_modues&quot;)/div[@class=&quot;be-holidays be-fixture be-form-wrapper&quot;]</value>
      <webElementGuid>2120279f-f276-4d48-9f4e-b7e18016bed0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@type='holidays']</value>
      <webElementGuid>3b0c0688-bffc-4a73-ac13-e65694b0111b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div</value>
      <webElementGuid>9a9e718a-e3c7-452a-a1a5-180f3c0b1c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Domestic and International Holidays'])[1]/following::div[2]</value>
      <webElementGuid>e8b2e85d-6bb9-47c8-a233-fb85bfa43111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charter Flights'])[1]/following::div[4]</value>
      <webElementGuid>6ba0aa08-a6a0-42ae-9268-53403ad6755e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/section/div/div/div</value>
      <webElementGuid>0f05fdcd-46a3-4d8a-a326-189dee816c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'holidays' and (text() = ' Depart From   New DelhiMumbaiJaipurBengaluruChennaiHyderabadPuneKolkataLucknowAhmedabad     Going To        Month of Travel (Optional)      
          Select Origin City
        ' or . = ' Depart From   New DelhiMumbaiJaipurBengaluruChennaiHyderabadPuneKolkataLucknowAhmedabad     Going To        Month of Travel (Optional)      
          Select Origin City
        ')]</value>
      <webElementGuid>56d15a03-68f1-4778-9a42-54102bfa2b19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
