<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Month of Travel (Optional)</name>
   <tag></tag>
   <elementGuidId>a3388cec-4d9b-4509-9413-7038002791f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ddTitle.borderRadiusTp.holi_passengerBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BE_holiday_destination_details']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>77ad256f-3f35-4250-8ac2-b472a9330481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ddTitle borderRadiusTp holi_passengerBox</value>
      <webElementGuid>ad4ed992-a34a-4e3e-9f32-217f1525df40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Month of Travel (Optional)</value>
      <webElementGuid>6bfd0192-4728-4972-8a52-00cb8b89b0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_holiday_destination_details&quot;)/div[@class=&quot;oneway-roundtrip&quot;]/div[@class=&quot;select-with-bg holi_passengerBox flexB100&quot;]/div[@class=&quot;dd ddcommon borderRadius holi_passengerBox search-height b-btm&quot;]/div[@class=&quot;ddTitle borderRadiusTp holi_passengerBox&quot;]</value>
      <webElementGuid>df9d203a-491b-427e-9852-dbb0e446ddca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d013b388-cb7a-46e8-aee3-3f7a78eca89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ddTitle borderRadiusTp holi_passengerBox</value>
      <webElementGuid>be52c0ad-7564-4547-8ab1-f4f453034a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Month of Travel (Optional)</value>
      <webElementGuid>d09de64b-39da-4393-8410-2242b03b6425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_holiday_destination_details&quot;)/div[@class=&quot;oneway-roundtrip&quot;]/div[@class=&quot;select-with-bg holi_passengerBox flexB100&quot;]/div[@class=&quot;dd ddcommon borderRadius holi_passengerBox search-height b-btm&quot;]/div[@class=&quot;ddTitle borderRadiusTp holi_passengerBox&quot;]</value>
      <webElementGuid>ab90f2d7-876a-4293-8d3c-3daf448f8ff3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BE_holiday_destination_details']/div/div/div/div</value>
      <webElementGuid>3c121188-c4ff-4ce7-adb3-9d3f366a2116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Going To'])[1]/following::div[3]</value>
      <webElementGuid>cec53919-94d7-4a3a-89d7-1dfd8b0982e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Depart From'])[1]/following::div[4]</value>
      <webElementGuid>52412c98-5108-4301-861e-2f61d0bc033d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toast Content'])[1]/preceding::div[6]</value>
      <webElementGuid>03d1d5ba-2dc1-4138-9473-f0592026c7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>458b6afd-8bbb-406c-b68c-905f5aecb9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  Month of Travel (Optional)' or . = '  Month of Travel (Optional)')]</value>
      <webElementGuid>3340876d-6308-468a-8494-b7a9a90a9f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
