<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_May 2022_BE_holiday_search_btn</name>
   <tag></tag>
   <elementGuidId>f55bf229-326f-47ae-b626-10d0fb1e7f62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_holiday_search_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BE_holiday_search_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c896ed8-98ef-460b-90d7-18a96335c4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>8368350d-3b7c-4aef-b039-5646f963e1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3b8c3e49-8078-4fb7-9a10-42d421530e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Holidays</value>
      <webElementGuid>0159fe66-e356-4bce-8ee7-877755ec1a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackcategory</name>
      <type>Main</type>
      <value>Home Page</value>
      <webElementGuid>8f56a155-018f-4748-9809-6571bcca26c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackaction</name>
      <type>Main</type>
      <value>Booking Engine</value>
      <webElementGuid>6aacd14f-8af8-4586-95ee-92904ab80ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackvalue</name>
      <type>Main</type>
      <value>Holidays Tab - Find Holidays</value>
      <webElementGuid>cd716268-2af3-4e24-905f-dcc00de3fc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_holiday_search_btn</value>
      <webElementGuid>8d9b01a8-9b3d-4034-a61d-5c50d99a653c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js_ripple search-btn search-flights-btn eventTrackable js-prodSpecEvtCat</value>
      <webElementGuid>fba55785-f981-4122-b2fe-b69a4cb3aece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_holiday_search_btn&quot;)</value>
      <webElementGuid>47ed2219-0453-4962-9ba0-ebc3fc5d5dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1285c9c8-6406-411f-b345-1ea8ae7a060a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>fb67b4db-23aa-431e-9410-b2f364ddbc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f77dade6-c99a-418b-8f2d-fe01145706f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Holidays</value>
      <webElementGuid>694d1694-5e64-481f-bb05-f37716bc08bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackcategory</name>
      <type>Main</type>
      <value>Home Page</value>
      <webElementGuid>d1653cc6-978b-4835-a94e-ee426a2f8b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackaction</name>
      <type>Main</type>
      <value>Booking Engine</value>
      <webElementGuid>20d858f1-872a-4fe1-9a0b-2de6cc80b27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackvalue</name>
      <type>Main</type>
      <value>Holidays Tab - Find Holidays</value>
      <webElementGuid>d9484f12-6911-4299-9b0b-d48bd969e610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_holiday_search_btn</value>
      <webElementGuid>d2d4c87e-9aca-4d7a-8da8-3e9b10aba6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js_ripple search-btn search-flights-btn eventTrackable js-prodSpecEvtCat</value>
      <webElementGuid>b57f9532-833f-4a2f-8d7b-7f45b541522c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_holiday_search_btn&quot;)</value>
      <webElementGuid>0df233d1-83a9-47ab-a3f8-cf9f2ede9276</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_holiday_search_btn']</value>
      <webElementGuid>8f5d7439-9c7c-4a01-a7e0-bbc0fb50acf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div[2]/div[2]/input</value>
      <webElementGuid>9ab5fb48-1d21-4cb7-8152-54bee4a8ce9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a79a06a1-1a3a-4bde-8603-fa8dcb317fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'BE_holiday_search_btn']</value>
      <webElementGuid>72e683c1-9b1d-46d7-a9f0-9f74de42e011</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
