<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_August 2022_BE_holiday_search_btn</name>
   <tag></tag>
   <elementGuidId>f4ca6b6e-a957-4330-8ec3-83f216f4c589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_holiday_search_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_holiday_search_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>efcd1b3d-97e9-4bf8-b23d-3d007b667a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>8750d84b-5531-4e01-b874-b3d31b9b0cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>55159009-598d-48db-8ea0-3534b3ea6c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Holidays</value>
      <webElementGuid>458a076a-2f97-4593-b748-f0d316642950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackcategory</name>
      <type>Main</type>
      <value>Home Page</value>
      <webElementGuid>6afcdfcf-a948-493c-8b8d-730c6ec4719e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackaction</name>
      <type>Main</type>
      <value>Booking Engine</value>
      <webElementGuid>cce07db0-fb0d-46f0-a66b-ed945742c522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackvalue</name>
      <type>Main</type>
      <value>Holidays Tab - Find Holidays</value>
      <webElementGuid>bd88b892-9c1c-4edb-a86f-af9ba57ffe66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_holiday_search_btn</value>
      <webElementGuid>425a4f6d-4827-49e4-85f4-a86aab734062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js_ripple search-btn search-flights-btn eventTrackable js-prodSpecEvtCat</value>
      <webElementGuid>76c31478-8799-43b8-98fd-22e1e89b3b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_holiday_search_btn&quot;)</value>
      <webElementGuid>fb4a19e4-606d-4039-8937-6873fbff2f17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_holiday_search_btn']</value>
      <webElementGuid>a055e891-b19d-4cb5-b39d-c69c88d98ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div[2]/div[2]/input</value>
      <webElementGuid>349d7c98-e316-48fc-b9ce-c4a79631c43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e69165ee-9e5b-44cd-8fa2-8021f4ba695f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'BE_holiday_search_btn']</value>
      <webElementGuid>143a6edb-bbf1-44c7-bd01-6168eb76bd47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
