<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_July 2022_BE_holiday_search_btn</name>
   <tag></tag>
   <elementGuidId>b6d5cbd0-b683-4436-a6ac-57df64421483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_holiday_search_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_holiday_search_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed794414-a9c1-4b8d-99e4-182ed02af73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>6f5f7cb5-480b-45d0-ac9c-5d608755a44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9a08d78c-4c9d-47d7-8683-0cbda0637496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Holidays</value>
      <webElementGuid>5cf4fbef-765d-4473-bb9a-02b2eafe9608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackcategory</name>
      <type>Main</type>
      <value>Home Page</value>
      <webElementGuid>82ec3e6f-8b1d-4b71-8534-dd9fe19f22a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackaction</name>
      <type>Main</type>
      <value>Booking Engine</value>
      <webElementGuid>bd1dfd5b-1879-43a5-a0c0-458ec91ada36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackvalue</name>
      <type>Main</type>
      <value>Holidays Tab - Find Holidays</value>
      <webElementGuid>e5e87c6b-47f1-4cba-9d5e-9b68bba452cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_holiday_search_btn</value>
      <webElementGuid>324f0ced-44b1-4cf9-92ba-74193e968fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js_ripple search-btn search-flights-btn eventTrackable js-prodSpecEvtCat</value>
      <webElementGuid>899d192f-de93-4458-a70b-39adf447e02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_holiday_search_btn&quot;)</value>
      <webElementGuid>fe01a884-62b4-47cb-98d5-0d637ab585db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_holiday_search_btn']</value>
      <webElementGuid>97d20a7c-12e1-43cc-bcb7-a7ab2336dec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking_engine_modues']/div/div[2]/div[2]/input</value>
      <webElementGuid>14d8eccd-58b1-4cbc-9b6f-86c6f2d2d59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>cdda657c-ed0b-4185-946e-20a09b9533e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'BE_holiday_search_btn']</value>
      <webElementGuid>0b987093-2f5c-4b58-8167-140d0b6ed3a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
