<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Book Domestic and International Holid_3519bd</name>
   <tag></tag>
   <elementGuidId>429fd3fe-137d-4374-a06d-e4ac8e496886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BE_holiday_leaving_city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BE_holiday_leaving_city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e2b4b2c-c77a-4780-9f71-c33099e14259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8e3ba4ff-6b0b-42d8-a659-290dc1e81edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8bcee4f5-4705-4947-b6a5-1115213cc012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BE_holiday_leaving</value>
      <webElementGuid>92508e1a-d45f-46f1-ba42-22af004db1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eac322cc-64c1-439c-a46b-10617802487f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BE_holiday_leaving_city</value>
      <webElementGuid>a46cb402-7c22-4218-a59f-85d82b47c3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.setSelectionRange(0, this.value.length)</value>
      <webElementGuid>9ae6a128-3428-4e1f-8921-f8edb12caaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required_field ac_input hotel_destInput origin_ac</value>
      <webElementGuid>f8282441-bbfa-4c83-94ce-9340a7291be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_holiday_leaving_city&quot;)</value>
      <webElementGuid>43d55f83-dc82-43fd-b7d1-29e6494fda2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BE_holiday_leaving_city']</value>
      <webElementGuid>a4f2c75f-4985-431d-b664-d2e16b89681d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BE_holiday_destination_details']/div/ul/li/div/label/input</value>
      <webElementGuid>ab02480a-2ca1-40cd-9675-9cf6eba944b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bef1d0b7-7107-4043-ad02-14c774373de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'BE_holiday_leaving' and @type = 'text' and @id = 'BE_holiday_leaving_city']</value>
      <webElementGuid>a527770f-c81d-4a5c-b22d-f1c09b50fef3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
