<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Month of Travel (Optional)</name>
   <tag></tag>
   <elementGuidId>e3526742-9f30-4e78-8272-42d98f5d0c33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BE_holiday_destination_details']/div/div/div/div/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ddTitleText-h.holi_passengerBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8dfbd3f2-7011-4fd4-8dcf-5e6ae9dec457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ddTitleText-h holi_passengerBox</value>
      <webElementGuid>e0bb73b7-760a-46ae-b684-c6d452285d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Month of Travel (Optional)</value>
      <webElementGuid>49c6473c-53aa-4160-8d84-b822fd64c5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_holiday_destination_details&quot;)/div[@class=&quot;oneway-roundtrip&quot;]/div[@class=&quot;select-with-bg holi_passengerBox flexB100&quot;]/div[@class=&quot;dd ddcommon borderRadius holi_passengerBox search-height b-btm&quot;]/div[@class=&quot;ddTitle borderRadiusTp holi_passengerBox&quot;]/span[@class=&quot;ddTitleText-h holi_passengerBox&quot;]</value>
      <webElementGuid>4c944e2f-6245-44dc-a85e-9b2895e62f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>27c6c548-7eb1-4b68-99e5-2c9cfa74cb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ddTitleText-h holi_passengerBox</value>
      <webElementGuid>b9f9809c-f9c6-4f87-a44d-f8addcc404f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Month of Travel (Optional)</value>
      <webElementGuid>14ac1f94-34ce-4545-8d0e-65496923f65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BE_holiday_destination_details&quot;)/div[@class=&quot;oneway-roundtrip&quot;]/div[@class=&quot;select-with-bg holi_passengerBox flexB100&quot;]/div[@class=&quot;dd ddcommon borderRadius holi_passengerBox search-height b-btm&quot;]/div[@class=&quot;ddTitle borderRadiusTp holi_passengerBox&quot;]/span[@class=&quot;ddTitleText-h holi_passengerBox&quot;]</value>
      <webElementGuid>ed8e63e9-ddc9-4c39-8744-2178865a68aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BE_holiday_destination_details']/div/div/div/div/span[3]</value>
      <webElementGuid>efa18ef2-4557-40a7-a83a-3888f9891169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Going To'])[1]/following::span[4]</value>
      <webElementGuid>dc8a81c8-dbdb-41c1-a7c2-624ab08b0e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Depart From'])[1]/following::span[6]</value>
      <webElementGuid>0417ab75-dcf2-4516-9097-843705df459d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toast Content'])[1]/preceding::span[3]</value>
      <webElementGuid>b02d4a62-5f05-4e4a-aaad-70a8a7b0568c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>be12b1c5-61a4-417b-b439-c57a55b49367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Month of Travel (Optional)' or . = 'Month of Travel (Optional)')]</value>
      <webElementGuid>b1c65ea6-3754-48aa-b61d-6c1f82ca52ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
