<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit Query</name>
   <tag></tag>
   <elementGuidId>1d423ed5-a68a-4b8b-a575-c2b05111fc2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.hidden-md.btn.black-button.fs-16.hidden-md.pnapop.submitReq_js.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='showleadform({});']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ed61afba-75ec-434b-9104-25285556aad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>(showSpeakToAnExpert)</value>
      <webElementGuid>5c6eeed9-7fc9-4a20-81e6-8801179befbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showleadform({});</value>
      <webElementGuid>5701926b-ecf2-454e-915f-81938cb1e752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden-md btn black-button fs-16 hidden-md pnapop submitReq_js ng-scope</value>
      <webElementGuid>0474b6b2-205e-4754-9b37-05b866e6208e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit Query</value>
      <webElementGuid>f66ede21-1fb5-4f02-8390-0f9977257602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;my-header&quot;]/div[@class=&quot;topbar row&quot;]/div[@class=&quot;route row&quot;]/div[@class=&quot;offer flL&quot;]/button[@class=&quot;hidden-md btn black-button fs-16 hidden-md pnapop submitReq_js ng-scope&quot;]</value>
      <webElementGuid>d1e88943-3b0d-4227-8a7f-a44b37640e06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='showleadform({});']</value>
      <webElementGuid>efed600a-84f5-469a-8d16-dd9ce6d3e890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[2]/div/div/div[2]/button[2]</value>
      <webElementGuid>aa4809c9-2786-4bab-bc28-f04387fc95d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Now'])[1]/following::button[1]</value>
      <webElementGuid>69f82343-54ce-43f2-916b-16e3d1453327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yatra.com'])[2]/following::button[2]</value>
      <webElementGuid>9774fc8f-75c7-4b93-b680-ff474e55f145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photos'])[1]/preceding::button[1]</value>
      <webElementGuid>bfd43221-b362-4cde-8fd3-9356bd7b00be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotels &amp; Transport'])[1]/preceding::button[1]</value>
      <webElementGuid>67ae5d99-dd84-4c43-ac99-57d5c9dbd335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit Query']/parent::*</value>
      <webElementGuid>61ce6c15-dc96-4f97-972b-33bcfe92d1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>137fdbf4-a866-4b5b-81f5-a516166cff22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Submit Query' or . = 'Submit Query')]</value>
      <webElementGuid>1444c8f0-ad9f-4d0b-be09-c9c57e550b24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
