<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please verify your mobile number_otp-input</name>
   <tag></tag>
   <elementGuidId>1b8b8d38-3208-4e64-ae58-f25fd1a3ca80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.otp-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2f13926-3a12-45ae-8118-b97c832ea946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b875473d-e544-4baf-a30d-33923347766f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input</value>
      <webElementGuid>331c9204-da21-40e2-8131-495ed0d3514e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>34edab25-8cda-4d17-86db-d264f1ebc5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Mobile OTP</value>
      <webElementGuid>d79926c4-2ff5-4477-a463-f394636758d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp-popup-overlay&quot;)/div[@class=&quot;popup-otp&quot;]/div[@class=&quot;otp-body&quot;]/div[@class=&quot;content-section mob&quot;]/div[@class=&quot;ui-input-text ui-body-inherit ui-corner-all ui-shadow-inset ui-focus&quot;]/input[@class=&quot;otp-input&quot;]</value>
      <webElementGuid>1fed6328-2f1f-4ac2-af9d-bcc2b3d0e451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3c644f1-2e78-41af-a3cb-44dd58bc1206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7e879a7-97bf-4b95-b50d-938699f3f0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input</value>
      <webElementGuid>8d8cea49-88f3-4f4d-8c71-283fc7710fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>2026ccad-a51a-4631-b399-8348ea2f7e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Mobile OTP</value>
      <webElementGuid>3180d16a-9f58-4991-b139-c2aa819b0e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp-popup-overlay&quot;)/div[@class=&quot;popup-otp&quot;]/div[@class=&quot;otp-body&quot;]/div[@class=&quot;content-section mob&quot;]/div[@class=&quot;ui-input-text ui-body-inherit ui-corner-all ui-shadow-inset ui-focus&quot;]/input[@class=&quot;otp-input&quot;]</value>
      <webElementGuid>ebefac6f-5149-42e8-a1d4-1c4925b7b9b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='']</value>
      <webElementGuid>1fdd769c-c1f6-4697-bca2-747a6bbdbc24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otp-popup-overlay']/div/div/div[2]/div/input</value>
      <webElementGuid>0a3d9f95-7149-4260-9075-3003bce80217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2f12f90c-1cbb-4562-abce-2ab52b899cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter Mobile OTP']</value>
      <webElementGuid>e87a2f27-a3df-4fdc-b386-6e66fb52803b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
