<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_X</name>
   <tag></tag>
   <elementGuidId>68870e15-db74-43f8-8ea4-528ae11f3f0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.cross.j-close-popup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='otp-popup-overlay']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>138acf37-14dc-456d-b19b-8a7118cd0165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cross j-close-popup</value>
      <webElementGuid>4e5fded2-189b-45d0-9a7d-d7d83a245370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>cffc7470-7cb6-4f92-bb45-a34341baec03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp-popup-overlay&quot;)/div[@class=&quot;popup-otp&quot;]/span[@class=&quot;cross j-close-popup&quot;]</value>
      <webElementGuid>461cf9cb-caae-457a-b5e1-ab025e02ec7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a2a77515-3872-4c25-8974-c9d73e07ba3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cross j-close-popup</value>
      <webElementGuid>acb9fe13-415c-4907-a6c7-8c6e77b2e8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>53aa3616-1174-42fc-ab29-250e63a2ade1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp-popup-overlay&quot;)/div[@class=&quot;popup-otp&quot;]/span[@class=&quot;cross j-close-popup&quot;]</value>
      <webElementGuid>73774ac4-9aae-4236-8920-e3aedd4e4ed6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otp-popup-overlay']/div/span</value>
      <webElementGuid>7b203951-521d-4d5c-94d7-efa387305750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE'])[2]/following::span[1]</value>
      <webElementGuid>e591e8ac-6569-4788-a810-6ad68e9a14bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRAINS'])[2]/following::span[1]</value>
      <webElementGuid>490bf281-e537-41b2-95c1-d63ea2503b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='srivishnu thatha'])[1]/preceding::span[1]</value>
      <webElementGuid>59ad70b9-8f62-49a7-916b-8a92cc6eb03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>96e7e45d-00c8-47d6-859d-2af548ba56a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'X' or . = 'X')]</value>
      <webElementGuid>095a22fb-9409-4445-8b1a-05a0bbd04477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='srivishnu thataha'])[1]/preceding::span[1]</value>
      <webElementGuid>ab93eb2c-c7b8-4ed2-9c25-98c1005b7e9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
