<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Logout_ico-newHeaderLogo</name>
   <tag></tag>
   <elementGuidId>95c6f8f6-4819-4a97-8d50-df3b71f7b252</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.logo > i.ico-newHeaderLogo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerSnipe']/div/div/div[3]/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>73ad1c5d-6657-44a1-b4b3-fad3d513fd6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-newHeaderLogo</value>
      <webElementGuid>7801735f-d70f-4b75-a526-06bdb8897d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerSnipe&quot;)/div[@class=&quot;yatra-header service-header secure-header&quot;]/div[1]/div[@class=&quot;header-container desktop-only&quot;]/div[@class=&quot;header-left-menu ftL&quot;]/a[@class=&quot;logo&quot;]/i[@class=&quot;ico-newHeaderLogo&quot;]</value>
      <webElementGuid>9d6d23d5-af48-496b-b681-9d9bfde9c79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f3b79300-abcf-4937-86e0-59a016de0d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-newHeaderLogo</value>
      <webElementGuid>b8185d46-6f2a-42a1-a076-46c14a0b7ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerSnipe&quot;)/div[@class=&quot;yatra-header service-header secure-header&quot;]/div[1]/div[@class=&quot;header-container desktop-only&quot;]/div[@class=&quot;header-left-menu ftL&quot;]/a[@class=&quot;logo&quot;]/i[@class=&quot;ico-newHeaderLogo&quot;]</value>
      <webElementGuid>ad50ed0d-477a-4c5a-93a6-42959f4c340a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerSnipe']/div/div/div[3]/div/a/i</value>
      <webElementGuid>7a9312a2-501c-4d5c-9773-3bc81a6a4203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
      <webElementGuid>43c84c4e-5504-44c1-8e44-6a2b3d18dba0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
