<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Offers_login-input</name>
   <tag></tag>
   <elementGuidId>aefa0782-0f2f-4ea2-af36-8a74b15fabf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1bec7473-49a2-4f6f-9144-cc0a29d87be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dabc0acb-5f19-40c1-84dd-33490616c7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter your email id/mobile to continue.</value>
      <webElementGuid>f4e30351-de62-488f-8bca-1646593ef178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yt-sme-mobile-input required_field email-login-box</value>
      <webElementGuid>b6472216-3a2f-48d8-a20a-a1e6fa9d1c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-input</value>
      <webElementGuid>070879d9-98fa-4b8b-8f06-753fa2c2ec41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regtype</name>
      <type>Main</type>
      <value>phoneno</value>
      <webElementGuid>3e8bab06-f05f-448b-a4fb-4823d9130754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login-input</value>
      <webElementGuid>c556c42d-10b5-48b7-a4af-76928bfe8f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>2f50b316-9b7f-4592-9f21-fbd7e488e5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email ID / Mobile Number</value>
      <webElementGuid>af0ff75a-716c-4663-a341-29bfcb63552f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-input&quot;)</value>
      <webElementGuid>9b828a3e-ff14-4844-b0b3-29678049e202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8e44b3f-bc72-4dbf-ae88-02eb5b1ae0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>46e47626-0364-4819-804e-0eb678ac2bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter your email id/mobile to continue.</value>
      <webElementGuid>c5d6efb1-a7ed-4cdc-9757-478d73dcb968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yt-sme-mobile-input required_field email-login-box</value>
      <webElementGuid>cb1392d0-cb5e-4e31-ab50-f84d1532fc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-input</value>
      <webElementGuid>ad61107d-af1c-4d7e-b319-d36adaee325f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regtype</name>
      <type>Main</type>
      <value>phoneno</value>
      <webElementGuid>ec0c1644-2745-4e44-a96b-fbeda26b7a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login-input</value>
      <webElementGuid>f7274314-a0af-4bef-b4f2-10d1d00d4750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>1924ab28-9be4-4ead-ba5b-9ae07be4f77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email ID / Mobile Number</value>
      <webElementGuid>af72815a-a42b-4c24-b0b0-4cb4b2d8e140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-input&quot;)</value>
      <webElementGuid>dea65ae9-7b12-4348-8b06-8da11832c5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03c99e3b-612a-4c7c-a8a1-87db9dd2f1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01481f3b-6acd-4fb0-8722-f5079fd71c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter your email id/mobile to continue.</value>
      <webElementGuid>af143959-a59c-4b2f-a484-cbe50926eb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yt-sme-mobile-input required_field email-login-box</value>
      <webElementGuid>64452ab2-2079-43ee-93f5-162f8e5fce6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-input</value>
      <webElementGuid>106d9694-2f2e-465c-931e-339ef79937e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regtype</name>
      <type>Main</type>
      <value>phoneno</value>
      <webElementGuid>ef4950db-f9a8-45cf-99e6-aa4326320bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login-input</value>
      <webElementGuid>bd5474c1-73ab-426d-a177-97ba75f29180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>598eef0a-a55d-420b-b070-19a492c41408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email ID / Mobile Number</value>
      <webElementGuid>4b7e95e7-e311-4173-9056-55008adb6e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-input&quot;)</value>
      <webElementGuid>b6eac0e8-20c7-4370-b3d4-ec91dbfb6304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf55b345-8aae-4755-8bdf-25cc5b7ede2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d2a7f0b-0edc-4f75-8ca9-c3401d8d8d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter your email id/mobile to continue.</value>
      <webElementGuid>ab0b4671-df66-4520-ae74-58637e4e30a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yt-sme-mobile-input required_field email-login-box</value>
      <webElementGuid>107c9454-fd9a-4c25-8c93-cfa3629ff1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-input</value>
      <webElementGuid>5dbabed2-de51-4f62-9231-2c73e4cce57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regtype</name>
      <type>Main</type>
      <value>phoneno</value>
      <webElementGuid>d7cb370e-a39f-46bf-a72d-32a3622fbf48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login-input</value>
      <webElementGuid>f95d35d7-a1a9-4487-99a2-588fed9b657b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>82432d9e-1b5f-4cbe-809f-a77b1281475c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email ID / Mobile Number</value>
      <webElementGuid>4b2daa8d-49c3-46f6-aab5-2e896d6c7d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-input&quot;)</value>
      <webElementGuid>bddc4f71-e7fb-4086-a989-c7713967d917</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-input']</value>
      <webElementGuid>b21f51f3-f32f-4d76-b5e6-cfac5cf78bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-input-wrapper']/input</value>
      <webElementGuid>526040f3-e44c-4d6d-8718-b390b5b0ceaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>574ddad7-50ee-4c0a-9bc2-20d0198bdee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'Enter your email id/mobile to continue.' and @id = 'login-input' and @name = 'login-input' and @placeholder = 'Email ID / Mobile Number']</value>
      <webElementGuid>d65470a1-ac4f-43d4-8a58-d929dc23c068</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
