<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_railyatra.com</name>
   <tag></tag>
   <elementGuidId>d0dbca09-3539-4906-86d9-d40e724563d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='phone-suppprt']/div[2]/div/table/tbody/tr[6]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e3dd306d-665c-4ed4-85e2-be013c8bded6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:rail@yatra.com</value>
      <webElementGuid>515a6d2f-a332-4892-888a-3a6ea96a1af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rail@yatra.com</value>
      <webElementGuid>c163acbd-cf82-46dd-883b-0cb1c50a1078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-suppprt&quot;)/div[@class=&quot;cont_tab&quot;]/div[@class=&quot;new-table&quot;]/table[@class=&quot;my-table&quot;]/tbody[1]/tr[6]/td[2]/a[1]</value>
      <webElementGuid>c3c64df7-5d8c-47a6-83b1-df57c890f2b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='phone-suppprt']/div[2]/div/table/tbody/tr[6]/td[2]/a</value>
      <webElementGuid>231bb06e-3857-4e65-b75a-ba15189a3d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'rail@yatra.com')]</value>
      <webElementGuid>092ac18a-8e84-414e-95f0-7abb6cc9831c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rail Support'])[1]/following::a[1]</value>
      <webElementGuid>742a6659-430c-41d9-9759-a5ee27ce8f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='International Holidays'])[1]/following::a[1]</value>
      <webElementGuid>a7375b05-1360-4ef3-a677-b425d2cb897a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Online'])[4]/preceding::a[1]</value>
      <webElementGuid>f361b1ae-f65b-46a8-9fc4-766c57a5556f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bus and Cab Support'])[1]/preceding::a[2]</value>
      <webElementGuid>360bc05f-947c-4bb9-8cec-1d73035ae644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='rail@yatra.com']/parent::*</value>
      <webElementGuid>6fa356db-3720-46a5-a24a-1bba12f48552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:rail@yatra.com')]</value>
      <webElementGuid>b6e51659-92f8-4b86-b906-3ad4790ddd08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/a</value>
      <webElementGuid>f5e983aa-84a1-4f50-bf05-9ce925925b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mailto:rail@yatra.com' and (text() = 'rail@yatra.com' or . = 'rail@yatra.com')]</value>
      <webElementGuid>fea5b9c6-3181-4e80-a46f-cc42efee11ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
