<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Is there any speed limit for self-drive cars</name>
   <tag></tag>
   <elementGuidId>d33993be-37fa-4487-bd12-d23753e4e979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.item-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yatra-faq-right']/ul/li/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>bab06db7-3ab2-4d76-bc62-071aad8ac365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-title</value>
      <webElementGuid>2d1ec752-e7f7-41b2-b872-0ab5589bb1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>bdac8a31-26c4-455e-bf9a-aed6c3f503f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#question-0</value>
      <webElementGuid>515cb063-8962-4034-9189-a949b4d5691f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qid</name>
      <type>Main</type>
      <value>130</value>
      <webElementGuid>934c43a4-e89c-44a9-ba18-227efb85b254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Is there any speed limit for self-drive cars?</value>
      <webElementGuid>b4feff0f-b4de-47f1-ab60-224acda9958b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yatra-faq-right&quot;)/ul[@class=&quot;items-list collapsed-group&quot;]/li[@class=&quot;item&quot;]/h3[@class=&quot;item-title&quot;]</value>
      <webElementGuid>966e406c-86df-4880-80bb-37cf7329f0a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yatra-faq-right']/ul/li/h3</value>
      <webElementGuid>c974bfbc-cb15-475b-a169-388b4aab6326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::h3[1]</value>
      <webElementGuid>205f3ea4-8f62-4578-a859-b26bf6e1c158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[1]/following::h3[1]</value>
      <webElementGuid>336d531d-22eb-46d3-9ad7-61517a181445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What are the benefits of through Yatra?'])[1]/preceding::h3[1]</value>
      <webElementGuid>a8a4a483-b4a2-48a4-86b1-b20fb2d5969d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You Could Also'])[1]/preceding::h3[2]</value>
      <webElementGuid>3af2eedf-2942-44bb-a87c-9ef829c63b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Is there any speed limit for self-drive cars?']/parent::*</value>
      <webElementGuid>399ccd96-7350-40ea-aefb-52e7c3353ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>00425e50-1687-44a9-805c-e5deaaf23388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Is there any speed limit for self-drive cars?' or . = 'Is there any speed limit for self-drive cars?')]</value>
      <webElementGuid>cbc769a6-9397-4b04-b69a-bd5b654cfe29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
