<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_What are the benefits of through Yatra</name>
   <tag></tag>
   <elementGuidId>b6db2f8a-3226-47e9-b7dc-29c4027b820b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yatra-faq-right']/ul/li[2]/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>882888f0-9473-4033-8570-1c7b34e8d79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-title</value>
      <webElementGuid>a8648cb4-f1ae-4e4f-a600-7dcbe619840b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>72f473df-6e59-4b4c-9193-682939bc4deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#question-1</value>
      <webElementGuid>3d63125e-57a9-47de-8976-fb815e6b3c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qid</name>
      <type>Main</type>
      <value>125</value>
      <webElementGuid>1c686fca-418a-4846-bfa0-3d8233710892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What are the benefits of through Yatra?</value>
      <webElementGuid>af50f078-7615-4562-8242-e8e5f68c3046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yatra-faq-right&quot;)/ul[@class=&quot;items-list collapsed-group&quot;]/li[@class=&quot;item&quot;]/h3[@class=&quot;item-title&quot;]</value>
      <webElementGuid>ebae5f76-bede-4bea-8ff8-336f4d0a4aff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yatra-faq-right']/ul/li[2]/h3</value>
      <webElementGuid>12eaaf55-061e-4133-82b6-02f008e29120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is there any speed limit for self-drive cars?'])[1]/following::h3[1]</value>
      <webElementGuid>5e06fec8-5886-4819-bc1d-7be2057646e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::h3[2]</value>
      <webElementGuid>98a872f6-2d7f-426a-a96e-c29baf956da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You Could Also'])[1]/preceding::h3[1]</value>
      <webElementGuid>b2cbee84-9114-491c-8792-17c097eb7958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::h3[1]</value>
      <webElementGuid>629b8359-7757-4b71-a227-aab80e82c53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='What are the benefits of through Yatra?']/parent::*</value>
      <webElementGuid>05819d80-f6bb-4032-8335-0fc48051fbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/h3</value>
      <webElementGuid>697009f3-e653-424a-ae8a-8f29c259aaf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'What are the benefits of through Yatra?' or . = 'What are the benefits of through Yatra?')]</value>
      <webElementGuid>acb78efb-c63e-4083-9147-913e102fa495</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
