<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_More_ico-newHeaderLogo</name>
   <tag></tag>
   <elementGuidId>b21212e3-12d2-4832-a8ed-92e23ac09f19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ico-newHeaderLogo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frescoHeader']/div/div/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3f962e6a-0cd5-4175-b7d1-fb790b720f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-newHeaderLogo</value>
      <webElementGuid>734f7f36-1c43-47d1-8dc1-bce19bc9be31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frescoHeader&quot;)/div[@class=&quot;desktop-only js_frescoHeader_hide clearfix&quot;]/div[@class=&quot;main-nav&quot;]/div[@class=&quot;header-container&quot;]/a[@class=&quot;logo&quot;]/i[@class=&quot;ico-newHeaderLogo&quot;]</value>
      <webElementGuid>9c1479fe-a1df-46d5-bf9b-78a164447d4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frescoHeader']/div/div/div/a/i</value>
      <webElementGuid>647e6c73-3603-4237-b8c4-5de935fdf608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>eba1d22c-4eca-48ed-9694-cf86278b9fe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
