<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Booking</name>
   <tag></tag>
   <elementGuidId>e2d38661-abb8-45ed-a4bb-a7e52ec18222</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.item-title.selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='undefined']/li/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1e848801-a573-4ebe-8b81-d01b33c8b467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-title selected</value>
      <webElementGuid>9fe2b850-1a18-4cc5-8616-0a248de55e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ef8e858e-102c-433a-b486-4b62addb5c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Booking</value>
      <webElementGuid>a4a926b6-74df-4414-894f-8ab9bd293b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>dc50e50f-0353-4050-a9a3-090430a0d094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>booking</value>
      <webElementGuid>9bcaf874-fd59-44e0-87ea-af330b42316c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>self-drive</value>
      <webElementGuid>80ddea6f-e7c2-46a6-aad7-ce4ffd7d9ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#booking</value>
      <webElementGuid>38f38bf9-0d44-4f3e-a936-d2a326daf6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-self</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8ec650b3-f9b7-4471-bedd-67cbaa745323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Booking</value>
      <webElementGuid>ce183bc8-490f-40bd-80a0-1ec066b41433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;undefined&quot;)/li[@class=&quot;cat-item item-level-1 in&quot;]/p[@class=&quot;item-title selected&quot;]</value>
      <webElementGuid>3147bbb9-8db0-4627-a872-242ee1341a3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='undefined']/li/p</value>
      <webElementGuid>0df02de5-1f48-46d9-a273-d598fa702a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::p[1]</value>
      <webElementGuid>f75567e2-3a6f-4dc4-a3a0-74d3264d069f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Booking'])[1]/following::p[1]</value>
      <webElementGuid>44c9577b-29ca-440d-b6c7-775a360122fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You Could Also'])[1]/preceding::p[4]</value>
      <webElementGuid>aeef8a2c-1fc7-4dbf-b293-fadb571770dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::p[4]</value>
      <webElementGuid>b119a9a5-38a6-492d-bbd9-e56a44aadc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/p</value>
      <webElementGuid>bf158a40-4c34-4c82-8fc3-026f3979d872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Booking' or . = 'Booking')]</value>
      <webElementGuid>85618d34-e307-4ab2-b5f4-e8809a39ce65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
